### ISSUE TITLE
Internal call

### ISSUE THREAD

**Issue by bickus** [blak3r/yaai#101]
Hello! I have a newbie question:)
Yaai detects call as internal if 

   Channel --> SIP/5061-b7803708 ! <---- this is 5061 (detected as internal)

So, if after SIP/here_go_numbers
But if 

   Channel --> SIP/some_words-b7803708 ! 

it works fine.
But! In our system channel names starts from numbers, so yaai doesn't work for me...
Well, is it possible to make yaai working for me without changing chanell name?
Thnx!

**Comment by blak3r** [comment]
Can you paste some stuff from your asterisk logger output. 

I think I made the regex configurable. 

Seeing the log output including the part that is like astMatchInternal will jog my memory

~blake

**Comment by bickus** [comment]
! --- Event ----------------------------------------------------------- !
Event --> Dial !
Privilege --> call,all !
SubEvent --> Begin !
Channel --> SIP/5061-b7803708 ! <---- this is 5061 
Destination --> SIP/7073-09f2b3b8 ! <---- this is 7073 
CallerIDNum --> 0506003006 !
CallerIDName --> 506003006 !
UniqueID --> 1350974265.16335 !
DestUniqueID --> 1350974271.16336 !
Dialstring --> 7073
! --------------------------------------------------------------------- !
Dial Event src=SIP/5061-b7803708 dest=SIP/7073-09f2b3b8 !
Successfully created CALL record with id=9a2f81b2-aa9b-2f95-97b0-50863b3e4593 Stripping callout prefix: Stripping callin prefix: CallerID is: 0506003006
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685
INTERNAL call detected, Deleting Call Record 9a2f81b2-aa9b-2f95-97b0-50863b3e4593

and call wasn't internal.

I've asked you here somewhile ago about other
https://github.com/blak3r/yaai/issues/81

And there you point me that 
Channel --> SIP/5061-b7803708 ! <---- this is 5061 (detected as internal)

**Comment by blak3r** [comment]
I looked at #81, and it appears your external call always appears as "SIP/7073-09f2b3b8 ! <---- this is 7073 

You could modify the isCallInternal method and that would work.  Just add an if statement to the top of it and say.... If( channel or destination startsWith(SIP/7073) then return false.

I think that'll probably get you a call popup but then they might all be detected as an incoming call... I'm not sure.
^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)

**Comment by blak3r** [comment]
I'm closing this.  If you could post a followup on how this issue was resolved that'd be helpful.
