### ISSUE TITLE
Add configurator option that allows user to choose phone fields

### ISSUE THREAD

**Issue by askhogan** [blak3r/yaai#106]
I have some code from another project that looks through the sugar bean stack for all "phone" type fields in each module that is selected by the user.  I am going to donate it to this project.

The goal would be to have a configurator panel where a user would select each phone fields (in any module) that they want to be involved in the query.  Then these options would get passed to the call listener query.  

Challenge:
The only challenge here would be the UI.  Currently the UI has hardcoded values for "Contact" or "Account" - It would not be too hard to handle this by just passing the module name through.

**Comment by blak3r** [comment]
Implemented a lower tech version.  I added two new config fields which let people specify a comma separated list of phone fields.  By default it's set to the default sugar phone fields for account and contact.
It supports custom phone fields as long as you put the _c suffix.
