### ISSUE TITLE
queue asterisk

### ISSUE THREAD

**Issue by Internetchik** [blak3r/yaai#114]
Hello! What with queues of asterisk? Today i installed yaai v 2.6b (asterisk 1.8.20, sugarCE 6.5.9), and see what this don't work with queues! But with extensions and ring group work excellent! asteriskLogger.php : 
[1360125493.37] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)
whats a problem?

**Comment by blak3r** [comment]
Yeah I think 2.6b has a bug.  Queues aren't officially supported.
I know it works with V3 which hasn't been officially released.  You can grab the code off github in the V3 branch if you want.

**Comment by Internetchik** [comment]
Oh.. It's bad. where i can get this code?

**Comment by Internetchik** [comment]
I think it's he. =) https://github.com/blak3r/yaai/tree/V3 . It was hard to find

**Comment by Internetchik** [comment]
Can you help me with installation this code? module loader not installedd v3. I copy and replace some files, and after starting asteriskLogger.php popups not work, again FAILED TO FIND A CALL, and new:
PHP Notice:  Undefined index:  YAAI in /var/www/html/sugarcrm/custom/modules/Asterisk/asteriskLogger.php on line 439 , 443
PHP Warning:  mysql_fetch_array(): supplied argument is not a valid MySQL result resource in /var/www/html/sugarcrm/custom/modules/Asterisk/asteriskLogger.php on line 60

**Comment by blak3r** [comment]
@Internetchik sorry this issue slipped through the cracks... are you still having issues?  Send me an email and I can give you the V3 beta version.

**Comment by Internetchik** [comment]
Hello! yes I need this! I would be happy to test v3! I send you my e-mail.

**Comment by stelst** [comment]
hello! Can I pouchavstvovat in beta testing version 3. Please if you can send it to me by email tarasov.artjom@gmail.com

**Comment by blak3r** [comment]
I don't have your email. 

~blake

**Comment by stelst** [comment]
tarasov.artjom@gmail.com

**Comment by pstmra** [comment]
Hi blak3r, great work! I'd like to test the V3 version with asterisk queue support. Can I have a .zip that I can load in sugar via module loader? My mail is pstmra@gmail.com. Thanks

**Comment by omejiasq** [comment]
Hi, excellent work. can you send me please to my email please: omejiasq@gmail.com

Thank you very much

**Comment by bickus** [comment]
Did someone tested queues?
I can't make it working.
 Event --> Hangup ! 
 Privilege --> call,all ! 
 Channel --> SIP/124-00001735 ! 
 Uniqueid --> 1371561272.5972 ! 
 CallerIDNum --> ! 
 CallerIDName --> !
 ConnectedLineNum --> 0506*****\* ! 
 ConnectedLineName --> 5060****\* ! 
 Cause --> 16 ! 
 Cause-txt --> Normal Clearing ! 

---

 Deprecated: Function eregi() is deprecated in /var/www/crm_test/custom/modules/Asterisk/asteriskLogger.php on line 1940 
 ## Deleting callid = because it didn't match any user extension

**Comment by blak3r** [comment]
Just posted a new version on sugarforge here: http://www.sugarforge.org/frs/?group_id=773

**Comment by Internetchik** [comment]
Hello I tested new version of the connector. It really works with queues. Big thenks and great work! But there are a few moments. It only works with Sugar version 6.5.14 below. I also kept a mistake [1374652720.18] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error). And popup rises just after lifting the handset.  I thought that you should report it. Goodbye.

**Comment by blak3r** [comment]
I don't understand. 

If your saying the bug is the popup doesn't show until the call is answered, this is expected behavior. It's complicated. 

~blake

**Comment by omejiasq** [comment]
Vladimir please, which sugarcrm 6.5.\* versions are supported for this yaai
version ?

2013/7/22 Blake Robertson notifications@github.com

**Comment by blak3r** [comment]
All of them are supported. 

The popup not showing up until call is answered is a result of the limitations in AMI for bridge events.  It's complicated, I think I've gone into more detail about this in a different thread here.

~blake
