### ISSUE TITLE
Problem with getJSON in checkForNewStates V3

### ISSUE THREAD

**Issue by micha3009** [blak3r/yaai#115]
I tryed Yaii V3 with Sugar 6.55 an my Asterisklog looks fine but there is no POPUP.
When I look in the Console there is this Message

extending
callPopups.js:881ready() hist_loaded: undefined ajaxUIEnabled = true
jquery.dropdown.js:12extending
callPopups.js:881ready() hist_loaded: true ajaxUIEnabled = true
callPopups.js:886loading yaai...
callPopups.js:809there is a problem with getJSON in checkForNewStates()

My Yaai LOG

! AMI Event 'Newchannel suppressed.
[2013-02-22 09:11:51]
! --- Event -----------------------------------------------------------
!                Event --> NewAccountCode  
!            Privilege --> call,all  
!              Channel --> SIP/202-000000a6  
!             Uniqueid --> 1361524311.177  
!          AccountCode -->  
!       OldAccountCode -->  
! ---------------------------------------------------------------------
[2013-02-22 09:11:51]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid  
!            Privilege --> call,all  
!              Channel --> SIP/202-000000a6  
!          CallerIDNum --> 01785095144  
!         CallerIDName --> 202  
!             Uniqueid --> 1361524311.177  
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
! ---------------------------------------------------------------------
 CallerID Changed to: 01785095144
! AMI Event 'ExtensionStatus suppressed.
! AMI Event 'Newstate suppressed.
! AMI Event 'ExtensionStatus suppressed.
! AMI Event 'Newstate suppressed.
[2013-02-22 09:11:52]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid  
!            Privilege --> call,all  
!              Channel --> SIP/202-000000a6  
!          CallerIDNum --> 620  
!         CallerIDName -->  
!             Uniqueid --> 1361524311.177  
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
! ---------------------------------------------------------------------
 CallerID Changed to: 620
! AMI Event 'Newchannel suppressed.
[2013-02-22 09:11:52]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid  
!            Privilege --> call,all  
!              Channel --> SIP/620-000000a7  
!          CallerIDNum --> 01785095144  
!         CallerIDName -->  
!             Uniqueid --> 1361524312.178  
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
! ---------------------------------------------------------------------
 CallerID Changed to: 01785095144
[2013-02-22 09:11:52]
! --- Event -----------------------------------------------------------
!                Event --> Dial  
!            Privilege --> call,all  
!             SubEvent --> Begin  
!              Channel --> SIP/202-000000a6  
!          Destination --> SIP/620-000000a7  
!          CallerIDNum --> 7985677  
!         CallerIDName --> <unknown>  
!     ConnectedLineNum --> 01785095144  
!    ConnectedLineName --> <unknown>  
!             UniqueID --> 1361524311.177  
!         DestUniqueID --> 1361524312.178  
!           Dialstring --> 620/01785095144  
! ---------------------------------------------------------------------
! Dial Event src=SIP/202-000000a6 dest=SIP/620-000000a7
! Successfully created CALL record with id=eedddb74-ccd8-4497-eff9-512736b8ba8c
 CallerID set from Dialstring to: 01785095144
 Stripping callout prefix: 
 Stripping callin prefix: 
 CallerID is: 01785095144
Looking for user extension number in: SIP/202-000000a6
Channel Matched SIP/### style regex. Ext is:202
OUTBOUND state detected... /^(SIP\/[1-3][0-9][0-9]?-|Local)/i is astMatchInternal eChannel= SIP/202-000000a6 eDestination=SIP/620-000000a7
! AMI Event 'Newstate suppressed.
[2013-02-22 09:11:59]
! --- Event -----------------------------------------------------------
!                Event --> NewAccountCode  
!            Privilege --> call,all  
!              Channel --> SIP/620-000000a7  
!             Uniqueid --> 1361524312.178  
!          AccountCode -->  
!       OldAccountCode -->  
! ---------------------------------------------------------------------
[2013-02-22 09:11:59]
! --- Event -----------------------------------------------------------
!                Event --> Bridge  
!            Privilege --> call,all  
!          Bridgestate --> Link  
!           Bridgetype --> core  
!             Channel1 --> SIP/202-000000a6  
!             Channel2 --> SIP/620-000000a7  
!            Uniqueid1 --> 1361524311.177  
!            Uniqueid2 --> 1361524312.178  
!            CallerID1 --> 7985677  
!            CallerID2 --> 01785095144  
! ---------------------------------------------------------------------
DEBUG: Entered Bridge
Bridge isn't internal to internal
Internal Queue Event Detected
Internal Queue: SELECT id FROM asterisk_log WHERE remote_channel like 'SIP/202-000000a6' and direction='I' and (channel = '' OR channel is NULL) 
DEBUG: NO Queue BRIDGE ROWS found
[2013-02-22 09:12:08]
! --- Event -----------------------------------------------------------
!                Event --> Unlink  
!            Privilege --> call,all  
!             Channel1 --> SIP/202-000000a6  
!             Channel2 --> SIP/620-000000a7  
!            Uniqueid1 --> 1361524311.177  
!            Uniqueid2 --> 1361524312.178  
!            CallerID1 --> 7985677  
!            CallerID2 --> 01785095144  
! ---------------------------------------------------------------------
[2013-02-22 09:12:08]
! --- Event -----------------------------------------------------------
!                Event --> Hangup  
!            Privilege --> call,all  
!              Channel --> SIP/620-000000a7  
!             Uniqueid --> 1361524312.178  
!          CallerIDNum --> 01785095144  
!         CallerIDName --> <unknown>  
!     ConnectedLineNum --> 7985677  
!    ConnectedLineName --> <unknown>  
!                Cause --> 16  
!            Cause-txt --> Normal Clearing  
! ---------------------------------------------------------------------
# +++ findCallByAsteriskId(1361524312.178)

! Found entry in asterisk_log recordId=eedddb74-ccd8-4497-eff9-512736b8ba8c
### [1361524312.178] FOUND outbound CALL

Looking for user extension number in: SIP/202-000000a6
Channel Matched SIP/### style regex. Ext is:202
### +++ findUserByAsteriskExtension(202)

! Assigned user id set to 1
 [1361524312.178] Measured call duration is 10 seconds
# +++ find AccountByPhoneNumber(01785095144)

! No results returned
### +++ find ContactByPhoneNumber(01785095144)

 findSugarObjectByPhoneNumber: Contact query components- Phone: 5095144 RegEx: (5[^\d]_0[^\d]_9[^\d]_5[^\d]_1[^\d]_4[^\d]_4[^\d]*)$
 Establishing relation to Contacts... Call ID: eedddb74-ccd8-4497-eff9-512736b8ba8c to Bean ID: 97731ee0-d166-68ca-12b9-5127305d31e7
! No results returned
### +++ findAccountForContact(97731ee0-d166-68ca-12b9-5127305d31e7)

! No results returned
 Call start was 2013-02-22 09:11:53
 [1361524312.178](OUTBOUND) Now updating record in /Calls/ id=eedddb74-ccd8-4497-eff9-512736b8ba8c...
NAME: *\* Automatic record **
DESCRIPTION: 
[2013-02-22 09:12:10]
! --- Event -----------------------------------------------------------
!                Event --> Dial  
!            Privilege --> call,all  
!             SubEvent --> End  
!              Channel --> SIP/202-000000a6  
!             UniqueID --> 1361524311.177  
!           DialStatus --> ANSWER  
! ---------------------------------------------------------------------
[2013-02-22 09:12:11]
! --- Event -----------------------------------------------------------
!                Event --> Hangup  
!            Privilege --> call,all  
!              Channel --> SIP/202-000000a6  
!             Uniqueid --> 1361524311.177  
!          CallerIDNum --> 7985677  
!         CallerIDName --> <unknown>  
!     ConnectedLineNum --> 01785095144  
!    ConnectedLineName --> <unknown>  
!                Cause --> 16  
!            Cause-txt --> Normal Clearing  
! ---------------------------------------------------------------------
# +++ findCallByAsteriskId(1361524311.177)

! Warning, results set was empty!
[1361524311.177] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)
! AMI Event 'ExtensionStatus suppressed.

What is my Problem. Sugar is on xampp on a Windows Xp Machine.

Thanks for your Help

Micha

**Comment by blak3r** [comment]
Probably a bug in the code. It's not stable yet. I think I saw that same thing happen on my box yesterday. Standby

~blake

**Comment by askhogan** [comment]
Sounds like the get_calls PHP call is not working.  Please check entry
point to make sure the controller file is accessible

**Comment by blak3r** [comment]
Yeah, this just started happening again on my box.
Weird... The problem is definitely in the php (hence the response 500).

I tried adding some logLine's to the top of my controller.php and it was never getting to them.  So, I'm not really sure what to make of it.  It was working an hour ago so doubt it's my entryPoint config... 

Everything was working an hour ago... I tried clearing out my asterisk_log database to see if something was weird in there... no dice.

**Comment by blak3r** [comment]
Also, my click to dial seems to not work... but when I debug in chrome it says "successful" to the originate command.  Might be something with my PBX.
@micha3009 does click to dial work on your box?

**Comment by askhogan** [comment]
That's all your code.  V3 only inbound.

**Comment by blak3r** [comment]
@micha3009 I made a bunch of changes to the V3 branch this weekend.  Maybe it's resolved the bug you were having.  I'm not having issues anymore.

**Comment by micha3009** [comment]
So I found my Problem but no Solution,
on my Sugar on Xampp with php 5.3 i have a deprecated warning which is in the catched getjson Array.
I tried to put off the error logging but in Chrome and Safari it doesnt work. In Firefox it runs great. i doesn't no why.
Is it possible to catch error messages in a getJson querry? And ignore them?
Gretings
Micha

**Comment by blak3r** [comment]
What is the error?

In System Settings there is a setting called: Display stack trace of errors:
turn that off maybe.

There is also some php.ini settings which enable errors to be shown which
you could turn off.

Either way...
Do inspect element, go to the network tab and paste me what the raw output
that's coming through is...

So, we can be aware of what method is causing the error so we can use a non
deprecated method going forward.

**Comment by mic3009** [comment]
I Have a Google Calender Sync Module which is has a deprecates Warning like tho Screenshot show. When I get a Call or start a Call then the Warning is in the index.php?entryPoint=AsteriskController&action=get_calls. When I reload the Page there is no Warning an the CallPopup is shown. 

Stack Trace of Errors is off
My php.ini 
display_errors =off

 error_reporting= E_ALL & ~E_DEPRECATED

An the Output
![Bildschirmfoto 2013-02-26 um 22 15 08](https://f.cloud.github.com/assets/1729350/198382/b2b990c2-8059-11e2-87c5-9b95fb050f4b.png)

**Comment by blak3r** [comment]
Ahh, well I'm surprised that you're getting those Deprecated lines in there based on how you have php configured.  Must be some other setting that's 

Maybe try setting it to
// Report simple running errors
error_reporting(E_ERROR | E_WARNING | E_PARSE);

or just 0 (no errors are reported)....

But, asides from that... I'm not sure why google calendar module would be showing up in my modules ajax requests.... If they're using a after_ui_frame logic hook... there are a lot of things you need to filter out... Here's the list that we use.  Perhaps the plugin should ignore more.

```
if ((!isset($_REQUEST['sugar_body_only']) || $_REQUEST['sugar_body_only'] != true) && $_REQUEST['action'] != 'modulelistmenu' &&
             $_REQUEST['action'] != "favorites" && $_REQUEST['action'] != 'Popup' && empty($_REQUEST['to_pdf']) &&
            (!empty($_REQUEST['module']) && $_REQUEST['module'] != 'ModuleBuilder') && empty($_REQUEST['to_csv']) && $_REQUEST['action'] != 'Login'
            && $_REQUEST['module'] != 'Timesheets')
```

**Comment by blak3r** [comment]
Did you ever resolve this issue?
