### ISSUE TITLE
How "Magic button" works?

### ISSUE THREAD

**Issue by mkmv** [blak3r/yaai#116]
Good day!

I just install yaai 2.6.0 to sugarcrm ce 6.5.10 (b8716) and asterisk 1.8.20.1. That works. Popup showing. Calls in journal. But I can't understand - when I press "Magic button" near phone number (in XXXXXXXXXXX format) in contact my internal softphone (with number ext. 1000) ringing, I am pick up the softphone and  it's hangup (phone XXXXXXXXXXX not ringing). I am press redial button in history of softphone and normal call to XXXXXXXXXXX. Why it dont call to XXXXXXXXXXX and ext. 1000 simultaneously or dont call to ext. 1000 first and then i pick up the soft phone - automatic call to  XXXXXXXXXXX?

p.s. In manual https://github.com/blak3r/yaai/wiki/User-Manual Step 4 and farther formatting is broken. I fixed.

**Comment by blak3r** [comment]
Do you use a custom dial command?
You might need to edit the dial command in the asterisk config.  It's the
one that by default is SIP/###.

**Comment by mkmv** [comment]
I am sorry. Seen sip debug in asterisk I understand - I am don,t set Dial Context in Call Configuration in YAAI Module Configuration and call go to "nothing". Set it right - and all works! Thank you. Issue resolved :)

**Comment by blak3r** [comment]
Great!  Could you be a little more explicit as to what you had to do?
You were using a dial context other then from-internal?
