### ISSUE TITLE
Dial Out and call popup

### ISSUE THREAD

**Issue by spidersab** [blak3r/yaai#118]
Hi blak3r,

First thanks for this conector, i think its realy useful

Second I have a problem, the system is recording in call modules all the calls that i make, but i cant use the dial out button and the pop up menu,

What can i first see, to begin debugging the connector?

thanks for all, i hope you can help me.

Im using sugar CE 6.5.2

Using the debuggin tool of chrome i cant see tha ami response i see a html page on network -> response tab

**Comment by blak3r** [comment]
There is a troubleshooting section in the manual which should be able to
guide you to the problem.

Do you have an extension configured and have call notification checkbox
checked?  That's the most obvious issue.
Check the troubleshooting section and should be able to find the issue.

~blake

**Comment by spidersab** [comment]
All the error was the memory limit in php.ini, i change it to 60M, and all work!!!!!!

Thanks for all

**Comment by blak3r** [comment]
Hmm... I wonder if you're going to run into the "memory" leak problem...Issue #96 

I really doubt the memory limit had anything todo with you not being able to make outbound calls... unless you were getting an out of memory error when you clicked to make one... if that's the case Sugar was probably pretty close to the limit as it was.

**Comment by blak3r** [comment]
Added this to the pre-reqs in case it's definitely an issue... Please let me know if you run into issues in a few days.
