### ISSUE TITLE
Popup after refresh page

### ISSUE THREAD

**Issue by bickus** [blak3r/yaai#119]
Well, I catch this bug again and what i found in log:

 Uncaught exception: TypeError: Cannot convert 'document.getElementById("3b7e0253-7ca1-7ee9-ba1c-510f97df91af_offset")' to objectError thrown at line 10, column 4 in refreshDashlet3b7e02537ca17ee9ba1c510f97df91af() in http://**_/index.php?action=ajaxui:
 if ( SUGAR.mySugar && document.getElementById("3b7e0253-7ca1-7ee9-ba1c-510f97df91af_offset").value == '0' )
 called from line 1, column 0 in http://**_/index.php?action=ajaxui:
 refreshDashlet3b7e02537ca17ee9ba1c510f97df91af()
 Uncaught exception: TypeError: Cannot convert 'document.getElementById("d9632c56-caa8-d790-c466-510149d14e7f_offset")' to objectError thrown at line 11, column 3 in refreshDashletd9632c56caa8d790c466510149d14e7f() in http://**_/index.php?action=ajaxui:
 if (SUGAR.mySugar && document.getElementById("d9632c56-caa8-d790-c466-510149d14e7f_offset").value == '0')
 called from line 1, column 0 in http://**_/index.php?action=ajaxui:
 refreshDashletd9632c56caa8d790c466510149d14e7f()
 Uncaught exception: TypeError: Cannot convert 'document.getElementById("4a77a89d-5988-bd2b-97cb-50ffe2a050a1_offset")' to objectError thrown at line 11, column 3 in refreshDashlet4a77a89d5988bd2b97cb50ffe2a050a1() in http://**_/index.php?action=ajaxui:
 if (SUGAR.mySugar && document.getElementById("4a77a89d-5988-bd2b-97cb-50ffe2a050a1_offset").value == '0')
 called from line 1, column 0 in http://**_/index.php?action=ajaxui:
 refreshDashlet4a77a89d5988bd2b97cb50ffe2a050a1()

**Comment by blak3r** [comment]
This started as a result of yaai?

Doesn't seem to be yaai code throwing the error.  What's the yaai issue?  
Is this a continuance of a previous issue?

**Comment by bickus** [comment]
Yes, it is of a previous issue. And it isn't yaai issue, but maybe someone faced it before.

**Comment by blak3r** [comment]
Oh, well you're better off posting that on the forms.  I think i'm the only one that'll see it here.

You probably have an extension which uses an "after_ui_frame" logic hook and they aren't filtering out everything they need to be.  There are sooo  many conditions that need be taken into consideration.

After_UI_Frame hooks allow developers to print html/javascript to the form.  There are certain times like ajax requests where the developer must not put stuff onto the page.

So, you could look up after_ui_frame logic hook and find the file where they're all defined.  Look in there at all your extensions that show up in there... disable each one.

OR probably the easiest thing would be to just disable ajax ui.  (Admin -> System Settings -> Ajax ui... and remove "home" from the modules.  Then, see if that makes the error go away... 

```
if ((!isset($_REQUEST['sugar_body_only']) || $_REQUEST['sugar_body_only'] != true) && $_REQUEST['action'] != 'modulelistmenu' &&
             $_REQUEST['action'] != "favorites" && $_REQUEST['action'] != 'Popup' && empty($_REQUEST['to_pdf']) &&
            (!empty($_REQUEST['module']) && $_REQUEST['module'] != 'ModuleBuilder') && empty($_REQUEST['to_csv']) && $_REQUEST['action'] != 'Login' )
```
