### ISSUE TITLE
i have MS SQL and don't get any call popups , direct dial works

### ISSUE THREAD

**Issue by josemfernandezozono** [blak3r/yaai#120]

**Comment by blak3r** [comment]
Mssql is not supported. 

~blake

**Comment by blak3r** [comment]
Quick to dial doesn't touch the database at all hence why it works. 

AsteriskLogger runs outside of sugar so it can't leverage the db factory layer and uses MySQL functions. 

If you're interested in funding MS SQL support, get in touch with me. Email is on github profile. 

~blake
