### ISSUE TITLE
YAAI and Sugar On Demand

### ISSUE THREAD

**Issue by poukill** [blak3r/yaai#121]
Hi,

In the user manual, it is specified that  "**Sugar OnDemand aka Sugar Cloud is not supported**".
Is there any workaround to make it work on Sugar Cloud ? Or is there any road map about this ?

I just suscribed a few weeks ago to Sugar On Demand. Perhaps I can change that but in that case I will have to watch & maintain another server at home.

**Comment by blak3r** [comment]
Not at this time. 

If your willing to pay, then might have something for ya in the near future. Get in touch by email.
