### ISSUE TITLE
Inbound calls don't display

### ISSUE THREAD

**Issue by gr33tx** [blak3r/yaai#125]
Please help me with issue/
I have inbound route from PSTN via D-Link 6008S directly to internal ext: 101
When I call it from out number from PSTN my SIP phone rings and show me 'from:some_out_num' but there is no popup in sugar. But when I call the same ext 101 from internal ext: some_int_num (with more than 4 digits) its popupping fine... 

[2013-03-14 10:09:51]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/701-00000035
!          CallerIDNum --> 735797
!         CallerIDName --> 735797
!             Uniqueid --> 1363255791.53
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
  1363255791.53 CallerID  Changed to: 735797
[2013-03-14 10:09:51]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/701-00000035
!          CallerIDNum --> 735797
!         CallerIDName --> 735797
!             Uniqueid --> 1363255791.53
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
  1363255791.53 CallerID  Changed to: 735797
! AMI Event 'Newchannel suppressed.
! AMI Event 'ExtensionStatus suppressed.
[2013-03-14 10:09:51]
! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> Begin
!              Channel --> SIP/701-00000035
!          Destination --> SIP/101-00000036
!          CallerIDNum --> 735797
!         CallerIDName --> 735797
!     ConnectedLineNum --> <unknown>
!    ConnectedLineName --> <unknown>
!             UniqueID --> 1363255791.53
!         DestUniqueID --> 1363255791.54
!           Dialstring --> 101
! ---------------------------------------------------------------------
! Dial Event src=SIP/701-00000035 dest=SIP/101-00000036
! Successfully created CALL record with id=69d16f2d-dce8-f4bb-5fd9-5141a1ac9ca8
  Stripping callout prefix:
  Stripping callin prefix:
  CallerID is: 735797
INTERNAL call detected, Deleting Call Record 69d16f2d-dce8-f4bb-5fd9-5141a1ac9ca8
! AMI Event 'Newstate suppressed.
! AMI Event 'Newstate suppressed.
! AMI Event 'ExtensionStatus suppressed.
! AMI Event 'Newstate suppressed.
[2013-03-14 10:09:59]
! --- Event -----------------------------------------------------------
!                Event --> NewAccountCode
!            Privilege --> call,all
!              Channel --> SIP/101-00000036
!             Uniqueid --> 1363255791.54
!          AccountCode -->
!       OldAccountCode -->
! ---------------------------------------------------------------------
[2013-03-14 10:09:59]
! --- Event -----------------------------------------------------------
!                Event --> Bridge
!            Privilege --> call,all
!          Bridgestate --> Link
!           Bridgetype --> core
!             Channel1 --> SIP/701-00000035
!             Channel2 --> SIP/101-00000036
!            Uniqueid1 --> 1363255791.53
!            Uniqueid2 --> 1363255791.54
!            CallerID1 --> 735797
!            CallerID2 --> 101
! ---------------------------------------------------------------------
Internatl Bridge Event Detected
RG-Bridge didn't match regex.
[2013-03-14 10:10:01]
! --- Event -----------------------------------------------------------
!                Event --> Unlink
!            Privilege --> call,all
!             Channel1 --> SIP/701-00000035
!             Channel2 --> SIP/101-00000036
!            Uniqueid1 --> 1363255791.53
!            Uniqueid2 --> 1363255791.54
!            CallerID1 --> 735797
!            CallerID2 --> 101
! ---------------------------------------------------------------------
[2013-03-14 10:10:01]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SIP/101-00000036
!             Uniqueid --> 1363255791.54
!          CallerIDNum --> 101
!         CallerIDName --> 101
!     ConnectedLineNum --> 735797
!    ConnectedLineName --> 735797
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
# +++ findCallByAsteriskId(1363255791.54)

! Warning, results set was empty!
[1363255791.54] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)
[2013-03-14 10:10:01]
! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> End
!              Channel --> SIP/701-00000035
!             UniqueID --> 1363255791.53
!           DialStatus --> ANSWER
! ---------------------------------------------------------------------
! AMI Event 'ExtensionStatus suppressed.
[2013-03-14 10:10:01]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SIP/701-00000035
!             Uniqueid --> 1363255791.53
!          CallerIDNum --> 735797
!         CallerIDName --> 735797
!     ConnectedLineNum --> 101
!    ConnectedLineName --> 101
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
# +++ findCallByAsteriskId(1363255791.53)

! Warning, results set was empty!
[1363255791.53] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)

**Comment by gr33tx** [comment]
! ConnectedLineNum --> 
! ConnectedLineName --> 

Why script can't connect at first to 101 ext?
And this: FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)

**Comment by gr33tx** [comment]
Sorry, I found out what it was. My channel consisted of 4 digits. I changed it to 10001 and it works fine. :) Thanks a lot for your module!

**Comment by blak3r** [comment]
Technically, Inbound calls aren't even supposed to popup.  I always test
using some cell phone.
