### ISSUE TITLE
Calls not assigned to related field & Outgoing call Issue

### ISSUE THREAD

**Issue by diptikothari** [blak3r/yaai#126]
Hi,

I am new to yaai.I have installed yaai & having few issues.
1. When i make outgoing call,in "View Calls(Sugarcrm)" i am getting call as incoming call not as outgoing call.
2. I am making call from lead.In "View Calls(Sugarcrm)" related to field is coming as blank.
3. For out going call i am not able to see popup.
4. Can we listen to recorded calls from yaai/sugar?

What am i missing.

Thanks

**Comment by blak3r** [comment]
You must have something that isn't completely stock about your setup.  As a
result, calls aren't being detected as going in the right direction
(inbound, vs outbound, vs. internal)...

Make a call and log the output.

As for your lead issue, leads are not related to at this time.

**Comment by blak3r** [comment]
@diptikothari Leads are supported in callinize basic and callinize pro (along with a bunch of other goodies)
See http://www.callinize.com/
