### ISSUE TITLE
Config.php cannot be found, how to set sugar root

### ISSUE THREAD

**Issue by dinaras** [blak3r/yaai#128]
Hello,
I am using latest version of sugar 6.5.11
I downloaded and installed the module from sugarforge. I am currently using asterisk 1.4 :-(

When i first tried everything out of the box, click to call feature worked, i was able to get pop up, but it was empty, no info in it. Empty records get logged in sugar calls,

Then i started messing with the asterisklogger.php script.

Since i couldnt make it work, then i tried to make it work as a service Same result.

Then i downloaded asterisklogger_5.1.php for manager 1.0. No change. Also i tried to to use asterisklogger.php that was included in the module, but just commented AMI 1.1 and uncomented AMI 1.0

When running it i get 
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/sugarcrm/custom/modules/Asterisk/../config.php' (include_path='.:/usr/share/pear:/usr/share/php:/var/www/html/yubotocrm/custom/modules/Asterisk/../include') in /var/www/html/sugarcrm/custom/modules/Asterisk/asterisklogger_1_0.php on line 69

in the script i see
// Determine SugarCRM's root dir (we'll use this to find the config filez
$scriptRoot = dirname(**FILE**);

am i supposed to add something there? 

Final question.

It is difficult for me to upgrade asterisk at the minute. Is there a way to get full functionality of yeea, with AMI 1.0?

Thank you very much in advance

best Regards

Dinos

**Comment by blak3r** [comment]
Dinos,

I have improved support for AMI 1.0 in the dev branch.  Send me an email
and I'll get you a build to test with.

**Comment by dinaras** [comment]
Hello Blake,

This is great thing to hear.

Please send me this build to try, and i will get back to you with comments.

Please also let me know if i have to do any hacks in the module i have 
already installed.

Also please tell me if i should use default asterisklogger.php.

If all work well, i plan to run this as a service on the server.

Thank you very much in advance

Looking forward for your reply

Best regards

Dinos

On 3/4/2013 5:56 μμ, Blake Robertson wrote:

> Dinos,
> 
> I have improved support for AMI 1.0 in the dev branch. Send me an email
> and I'll get you a build to test with.
> 
> On Wed, Apr 3, 2013 at 10:43 AM, dinaras notifications@github.com 
> wrote:
> 
> > Hello,
> > I am using latest version of sugar 6.5.11
> > I downloaded and installed the module from sugarforge. I am currently
> > using asterisk 1.4 :-(
> > 
> > When i first tried everything out of the box, click to call feature
> > worked, i was able to get pop up, but it was empty, no info in it.
> > 
> > Then i started messing with the asterisklogger.php script.
> > 
> > Since i couldnt make it work, then i tried to make it work as a service
> > Same result.
> > 
> > Then i downloaded asterisklogger_5.1.php for manager 1.0. No change. 
> > Also
> > i tried to to use asterisklogger.php that was included in the 
> > module, but
> > just commented AMI 1.1 and uncomented AMI 1.0
> > 
> > When running it i get
> > PHP Fatal error: require_once(): Failed opening required
> > '/var/www/html/sugarcrm/custom/modules/Asterisk/../config.php'
> > 
> > (include_path='.:/usr/share/pear:/usr/share/php:/var/www/html/yubotocrm/custom/modules/Asterisk/../include')
> > in 
> > /var/www/html/sugarcrm/custom/modules/Asterisk/asterisklogger_1_0.php on
> > line 69
> > 
> > in the script i see
> > // Determine SugarCRM's root dir (we'll use this to find the config 
> > filez
> > $scriptRoot = dirname(**FILE**);
> > 
> > am i supposed to add something there?
> > 
> > Final question.
> > 
> > It is difficult for me to upgrade asterisk at the minute. Is there a 
> > way
> > to get full functionality of yeea, with AMI 1.0?
> > 
> > Thank you very much in advance
> > 
> > best Regards
> > 
> > Dinos
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/blak3r/yaai/issues/128
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/blak3r/yaai/issues/128#issuecomment-15841476.
> 
> No virus found in this message.
> Checked by AVG - www.avg.com http://www.avg.com
> Version: 2012.0.2240 / Virus Database: 2641/5723 - Release Date: 04/03/13

## 

Direct:     (+30) 211 11 44 101
E-mail:     kliadakis@yuboto.com mailto:kliadakis@yuboto.com
Website:    www.yuboto.com http://www.yuboto.com/

Click2Call and I will call you back 
https://services.yuboto.com/click2call/new/c2t.aspx?id=6355B9C7-03BF-4828-963E-C43239B4058D

**Comment by blak3r** [comment]
Here ya go.  Hopefully it works for ya.  If you have any issues, please
post a new thread related to AMI 1.0 on the issue tracker.

**Comment by dinaras** [comment]
Hello Blak3r

Where can i download your improved AMI1.0 script?

Thank you in advance

Dinos

**Comment by blak3r** [comment]
Send me an email.  Address is in my profile

**Comment by dinaras** [comment]
Hello Blake, 

Although you had asked me to write all my comments here, i had forgotten to, and today that i saw you close the ticket i remembered and s i posted. Apologies for my delay in posting

After your comment I have added callerid column, and i can see caller id in calls list view.\

I have found 2 problems so far:
1. When i click the little icon from sugar and i make a call, then in the record created in the call, i see the outbound call, i see who made the call, but it doesnt match the contact or account i called
2. When having received and finished a call, when adding a memo on the pop up (which shows a unique correct contact ) the record created shows the note, DOES NOT show who wrote it, and also it doesnt show the related contact or account

Also i see some outbound calls with *\* Automatic Record *_. WHy is this record different from other inbound calls? On top of the screen shot you can see *_ Automatic Record *\* with matched account, and also far below another *\* Automatic Record *\* which is not matched

Some background about our setup

Everybody in the office has his own incoming number,  but there is also a main number for incoming calls. I created a user with this phonenumber as office number in order to match it, but still no joy

I had a screenshot as well but i am unable to upload it.

Thnak you very much in advance

Regards

Dinos

**Comment by blak3r** [comment]
Explain your setup again... They don't have extensions configured?

~blake

**Comment by dinaras** [comment]
Everybody in the office has his own account on sugar and his own 
extension and his own direct number that is configured in yaai settings. 
The main company number does not belong to any user, and in fact it is 
going to a ring group. Members of the ringroup are people that are 
configured in sugar crm.

Does this give a clear picture?

Regards

Dinos

**Comment by blak3r** [comment]
Contact matching will fail if you don't have any custom fields in either account or contact.  Create a dummy one if you don't need one.  I bet that's why you're not getting who it's related to.

As for who wrote the note, that's usually handled by the assigned_user if that's not happening look at your logs to find the lines around findUserForAsteriskExtension and see what it's saying there for insight.

**Comment by blak3r** [comment]
Oh i just realized you have AMI 1.0... Umm... yeah that's not supported completely.  I don't have an AMI 1.0 box to test with so gonna take some work on your end I'm afraid or make a nice donation to the project.
