### ISSUE TITLE
No info about account in popup

### ISSUE THREAD

**Issue by Aleks305** [blak3r/yaai#129]
Hello!
I installed sugarcrm 6.5.11, asterisk-1.8.20 and yaai 2.6.0b, CentOS 6.4.
I begin to test, added account with number 10005 and user with number 10004. Login with new user(number 1004).
I call from 1005 to 1004 and:
 php asteriskLogger.php

*******\* Asterisk Logger Starting [2013-04-19 08:52:23]**************
[Config Settings]
  Sugar root set to [/var/www/sugarcrm/custom/modules/Asterisk/../../../]
PHP Notice:  Undefined index: asterisk_log_file in /var/www/sugarcrm/custom/modules/Asterisk/asteriskLogger.php on line 122
  Logging to:
  Callout prefix is []
  Callin prefix is []
  Match Internal Regex = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i
[Database Connection]
  Selecting DB Name: sugarcrm
[SOAP Connection]
  Trying SOAP login endpoint=[http://151.248.122.76/soap.php] user=[astercon] pa
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/incl
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/incl
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/incl
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/incl
  Successfully logged into Sugar via SOAP!  SessionId=npf3ssmkcv6v26sgeqivvs9910
[Asterisk Manager Interface (AMI) Connection]
  Successfully opened socket connection to 151.248.122.75:5038
  AMI Version Info:
    `
    Asterisk Call Manager/1.1
`
  Supported AMI version: 1.1 Detected
  AMI Login action raw response:
    `
    Response: Success
    Message: Authentication accepted
`
  AMI Login was a _success!_
Waiting for call events...
! AMI Event 'Newchannel suppressed.
! AMI Event 'Newstate suppressed.
! AMI Event 'ExtensionStatus suppressed.
! AMI Event 'Newchannel suppressed.
! AMI Event 'ExtensionStatus suppressed.
[2013-04-19 08:52:43]
! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> Begin
!              Channel --> SIP/10005-00000037
!          Destination --> SIP/10004-00000038
!          CallerIDNum --> 10005
!         CallerIDName --> Aleks2
!     ConnectedLineNum --> 10004
!    ConnectedLineName --> Aleks1
!             UniqueID --> 1366361563.55
!         DestUniqueID --> 1366361563.56
!           Dialstring --> 10004
! ---------------------------------------------------------------------
! Dial Event src=SIP/10005-00000037 dest=SIP/10004-00000038
! Successfully created CALL record with id=e5b6608b-6e24-1679-7cc1-51710500016d
  Stripping callout prefix:
  Stripping callin prefix:
  CallerID is: 10005
Inbound state detected... /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i is astMatchIn                                                                                                                                ternal eChannel= SIP/10005-00000037 eDestination=SIP/10004-00000038
! AMI Event 'Newstate suppressed.
! AMI Event 'ExtensionStatus suppressed.
! AMI Event 'Newstate suppressed.
! AMI Event 'Newstate suppressed.
[2013-04-19 08:52:50]
! --- Event -----------------------------------------------------------
!                Event --> NewAccountCode
!            Privilege --> call,all
!              Channel --> SIP/10004-00000038
!             Uniqueid --> 1366361563.56
!          AccountCode -->
!       OldAccountCode -->
! ---------------------------------------------------------------------
[2013-04-19 08:52:50]
! --- Event -----------------------------------------------------------
!                Event --> Bridge
!            Privilege --> call,all
!          Bridgestate --> Link
!           Bridgetype --> core
!             Channel1 --> SIP/10005-00000037
!             Channel2 --> SIP/10004-00000038
!            Uniqueid1 --> 1366361563.55
!            Uniqueid2 --> 1366361563.56
!            CallerID1 --> 10005
!            CallerID2 --> 10004
! ---------------------------------------------------------------------
[2013-04-19 08:53:01]
! --- Event -----------------------------------------------------------
!                Event --> Unlink
!            Privilege --> call,all
!             Channel1 --> SIP/10005-00000037
!             Channel2 --> SIP/10004-00000038
!            Uniqueid1 --> 1366361563.55
!            Uniqueid2 --> 1366361563.56
!            CallerID1 --> 10005
!            CallerID2 --> 10004
! ---------------------------------------------------------------------
! AMI Event 'ExtensionStatus suppressed.
[2013-04-19 08:53:01]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SIP/10004-00000038
!             Uniqueid --> 1366361563.56
!          CallerIDNum --> 10004
!         CallerIDName --> device
!     ConnectedLineNum --> 10005
!    ConnectedLineName --> Aleks2
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
# +++ findCallByAsteriskDestId(1366361563.56)

! FindCallByAsteriskDestId - Found entry in asterisk_log recordId=e5b6608b-6e24-                                                                                                                                1679-7cc1-51710500016d
Looking for user extension number in: SIP/10004-00000038
Channel Matched SIP/### style regex.  Ext is:10004
### +++ findUserByAsteriskExtension(10004)

! Assigned user id set to 47dda6fd-b8e1-275e-eeb6-516ee3293afc
  Measured call duration is 12 seconds
# +++ find AccountByPhoneNumber(10005)

Found a matching account, relating to account instead of contact
  Establishing relation to Accounts... Call ID: e5b6608b-6e24-1679-7cc1-51710500                                                                                                                                016d to Bean ID: 4a9795b2-04ff-7f30-43ad-51704e4ab72e
! No results returned
! Call start was 2013-04-19 08:52:43
 Updating record in /Calls/ id=e5b6608b-6e24-1679-7cc1-51710500016d...
  NAME: *\* Automatic record **
  DESCRIPTION:
Cleaning up Failed Calls part1, asterisk_id = 1366361563.55

Why can not I see a popup customer information if it is added? In this case, in the Calls in the field "Related to" i see it.
Please,help me!

**Comment by blak3r** [comment]
Nothing springs to mind. Kinda distracted though. It does appear to be finding a matching user. 

Did you look through all the troubleshooting sections? 

~blake

**Comment by Aleks305** [comment]
Hello, Blake!
Thanks for your reply!Yes, I looked through all the troubleshooting sections (this section "Inbound Calls aren't being properly matched to a contact (Call window is appearing though)"), but I could not find the cause. When I start 
php asterisklogger.php
I see:
PHP Notice:  Undefined index: asterisk_log_file in /var/www/sugarcrm/custom/modules/Asterisk/asteriskLogger.php on line 122
and 
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/include/nusoap/nusoap.php on line 6166
First waning (on line 122), in my opinion, is not described troubleshooting section, and I don't know what to do.

122 line from asteriskLogger.php:
logLine( "  Logging to: " . $sugar_config['asterisk_log_file'] . "\n");
6166 line from asteriskLogger.php:
?> (end or script)

Dear Blake, please tell my , my debug from the previous post does not contain any errors?

**Comment by Aleks305** [comment]
In /var/log/httpd/sugarcrm-error_log I see this error log:
[Sun Apr 21 01:59:11 2013] [error] [client xxxx] PHP Notice:  Undefined index: asterisk_prefix in /var/www/sugarcrm/custom/modules/Asterisk/include/callListener.php on line 74, referer: http://x.x.x.x/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DContacts%26action%3Dindex%26parentTab%3DMarketing
[Sun Apr 21 01:59:11 2013] [error] [client xxxx] PHP Notice:  Undefined index: asterisk_dialinPrefix in /var/www/sugarcrm/custom/modules/Asterisk/include/callListener.php on line 75, referer: http://x.x.x.x/index.php?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DContacts%26action%3Dindex%26parentTab%3DMarketing

**Comment by Aleks305** [comment]
Installed on another VM Sugarcrm. PHP 5.3.3 . The situation is similar, pop-ups do not include information about the client. The logs are now visible error:
PHP Deprecated: Function eregi () is deprecated in / var / www / sugar / custom / modules / Asterisk / asteriskLogger.php on line 1674
Also, notice that the outgoing calls without pop-ups.Maybe the problem in version PHP?

**Comment by blak3r** [comment]
Those warnings are there on my box too. So, I don't think that's it. 

~blake

**Comment by Aleks305** [comment]
I'm testing with the internal numbers Asterisk (not yet vulture trunk).Numbers: 10001 and 10002.
10001 - sugarcrm user
10002 - sugarcrm contact
Perhaps because of this non-displayed information about the contact?
Do I have to prefix fields outgoing incoming prefixes indicate when tested with the internal numbers any value?

**Comment by blak3r** [comment]
That's the problem. Gotta test with external numbers otherwise its detected as an internal call and therefore no popup. Internal calls are ignored as its very hard to differentiate them from all the dial events that occur naturally for every call. 

I thought this was in the user manual somewhere but a quick search for internal didnt reveal anything. 

The manual is public (anyone can edit) if you could add a note that'd be great. 

~blake

**Comment by Aleks305** [comment]
Thank you.I'll try to test the external number. If this was a problem, complementing manual

**Comment by blak3r** [comment]
Hi Aleks, doing some housekeeping... Was the problem internal to internal calls?

**Comment by Aleks305** [comment]
Hi Blake.
 Please excuse me, that did not fulfill my promise and did not answer.
Indeed, when calling from internal to internal the customer card is not shown.  When Asterisk connected SIP trunk and began to call out, everything was ok. When connected to an asterisk vulture a trunk and began to call the city, everything was ok.
Thank you!

Понедельник, 20 мая 2013, 23:29 -07:00 от Blake Robertson notifications@github.com:

**Comment by blak3r** [comment]
Thanks for posting back.
