### ISSUE TITLE
Issue after modifying manifest.php and rebuilding package

### ISSUE THREAD

**Issue by arm123** [blak3r/yaai#130]
Hi All,

I have downloaded yaai, and it seems cool to have such features with asterisk.

I am using below versions:

SugarCE-6.5.10
yaai-2.6.0b

First Case: 

I installed module yaai-2.6.0b.zip as it it downloaded and could not find fields like specifying asterisk extension etc in user section. So i uninstalled it.

Second Case:

I extracted yaai-2.6.0b.zip and modified manifest.php file where it said "//UNCOMMENT THIS SECTION IF YOU WANT TO OVERWRITE YOUR USER CUSTOMIZATIONS"
 and uncomment those lines and generated zip package and installed that. 

Module got installed successfully, and also its showing me fields to specify asterisk extension number, and 2 checkboxes. But its not allowing me to save user section now and throwing javascript error as below:

"Error: ReferenceError: set_chooser is not defined
Source File: http://localhost/sugarcrm/index.php?module=Users&offset=2&stamp=1368781698087262200&return_module=Users&action=EditView&record=seed_chris_id
Line: 1"

Can anyone please provide me step by step information on how to fix this?

Thanks,
Arm

**Comment by blak3r** [comment]
In order to get the stock install working you have to add the fields to the user views in studio.  See manual for more. 

As for how to fix the problem now...

I've never in my life tried that. The user manual warns against this. Those were for pre 6.4 versions. And now they're pretty out of date. (Added new variables since then). But, that's not the cause of your issue. 

Sounds like your gonna have to get your hands dirty. 

~blake

**Comment by arm123** [comment]
Hi,

Thanks for your response.
So as i am using sugarCE 6.5.10 , i do not need to replace any existing module files and just create custom fields from studio for user section?

Earlier i had tried this on sugarCE 5.0 before few years, and i had got this totally working. but in newer version i am facing some issues as i am not much familiar with sugarcrm. I am ready to get my hands dirty :)

Please keep guiding me.

Thanks,
Arpit

**Comment by blak3r** [comment]
Arpit,

It just takes patience.  Follow the user manual step by step and it'll work.

You don't have to create fields on user.  You just have to add them to the
layouts where you want them.  (they'll show up in studio in the left bar
after install).

If you can rollback to a time before overwriting your User modules, that'd
probably be a good idea as I have no idea what that did in the grand scheme
of things.

**Comment by arm123** [comment]
Hey Thanks Blake,

I reinstalled sugarcrm and added from layout and now it seems to be showing in GUI atleast.
I haven't been able to test calls yet. But i will configure extensions and try it out.

Thanks for your help.

Thanks,
Arpit

**Comment by blak3r** [comment]
Great.
