### ISSUE TITLE
Undefined index in asterisk configurator [YAAI module]

### ISSUE THREAD

**Issue by jappie11** [blak3r/yaai#131]
PHP Notice: Undefined index: type in \custom\modules\Configurator\asterisk_configurator .php on line 113

**Comment by blak3r** [comment]
I think this is harmless. Haven't been able to fully figure out the Configurator / Administrative stuff. 

For example it doesn't display the product title at the tip of admin page. Pretty annoying and I've spent a lot of time on it in the past. 

~blake
