### ISSUE TITLE
Firewalls and YAAI problem

### ISSUE THREAD

**Issue by cubicova17** [blak3r/yaai#133]
After installing Vipre antivirus software, asteriskLogger script stopped to receive data from the Asterisk Call Manager. Although the script connects to the Asterisk machine successfully it prints "Patiently Waiting!.." every minute and as far as I understand, the socket connection is open but something blocks data transferring.

Strange thing is that after Vipre deinstallation the problem is not resolved.

Did anyone faced with similar problems?

**Comment by blak3r** [comment]
Interesting... have you tried to stop the script and then restart it?
It should get some data on initial connection about what AMI version it is.

What asterisk version do you have?  I remember reading at some point that
AMI didn't handle multiple connections very well....

The other thing to note is the logger script will automatically reconnect
to AMI if it hasn't seen anything in 1 hour... or gets 60 failed attempts.

~blake

**Comment by cubicova17** [comment]
Definitely, I restarted script and machine few times. AMI version 1.1. As for reconnection - it is exactly what happens, script does not get any data and reconnects:
![screen shot 2013-06-11 at 10 19 35 am](https://f.cloud.github.com/assets/860284/635842/2100d6c0-d268-11e2-910e-62db8d2d9e05.png)

Any ideas how can I understand where can be a problem?

**Comment by blak3r** [comment]
The script is getting some info back from asterisk on connection. (It's printing the version string)

Is it possible you changed the AMI permissions? Set read = all 

That would explain why you aren't getting dial events. Or... You are connecting to the wrong asterisk box altogether. 

~blake

**Comment by blak3r** [comment]
@cubicova17 did you ever figure out what the problem was?
