### ISSUE TITLE
Caller information doesn't show up

### ISSUE THREAD

**Issue by attaxia** [blak3r/yaai#135]
When receiving a call or calling outbound the popup shows the number, but not the information of the coupled contact.

I've checked the troubleshooting, didn't help. The phone number is added to the contact exactly as it appears in the SIP phone and the popup. Doesn't matter if I manually create the contact or if I do it from the popup.

I've edited out my number in the log below. There is a contact with the exact number shown in the terminal output, but somehow it isn't found. It's driving me crazy!
# +++ find AccountByPhoneNumber(064398****)

! No results returned
### +++ find ContactByPhoneNumber(064398****)

 findSugarObjectByPhoneNumber: Contact query components- Phone: 064398***\* RegEx: (0[^\d]_6[^\d]_4[^\d]_3[^\d]_9[^\d]_8[^\d]_0[^\d]_0[^\d]_0[^\d]_0[^\d]_)$
 Establishing relation to Contacts... Call ID: 8650d824-0cc6-19ca-3dec-51c24afe1985 to Bean ID: 3bebffdb-508f-d0e5-4534-51c248ae8e7a
! No results returned

**Comment by attaxia** [comment]
I would like to add that if you go to the contact all the calls are shown properly there. Also, when making an account with the same phone number this shows up:

Found a matching account, relating to account instead of contact
 Establishing relation to Accounts... Call ID: e169fb83-491c-0266-ec34-51c250ed08fd to Bean ID: 5ad99d23-519f-fa6c-ac7c-51c24f6b5456
! No results returned

Somehow still no name in the popup.

**Comment by blak3r** [comment]
What version of yaai? Make sure you have at least one custom field for account and contact. 

I bet the joins are failing. 

~blake

**Comment by blak3r** [comment]
If that doesn't fix it look at your php logs. 

~blake

**Comment by attaxia** [comment]
Hi, 

Thanks for the quick reply! I really really appreciate this. I have tried with the V3 and the main branch. Both are giving the same problem. 

As for the custom fields, I'm quite new to SugarCRM (just installed it yesterday, newest Community Edition). Do you have any suggestion for a custom field that should work? If it has to do with joining I can imagine some auto generated ID field would be best, can I do that? I'll go check my log and get back if I find something. 

Thanks again for the help, and the great software. I hope to get it fully working.

**Comment by attaxia** [comment]
Could any of these be the problem?
[Thu Jun 20 02:52:05 2013] [error] [client 192.168.1.3] PHP Notice:  Undefined index: type in /var/www/custom/modules/Configurator/asterisk_configurator.php on line 77, referer: http://192.168.1.5/index.php?module=Configurator&action=asterisk_configurator
[Thu Jun 20 02:52:51 2013] [error] [client 192.168.1.3] PHP Notice:  Undefined index: asterisk_prefix in /var/www/custom/modules/Asterisk/include/controller.php on line 547, referer: http://192.168.1.5/index.php?action=ajaxui
[Thu Jun 20 02:52:51 2013] [error] [client 192.168.1.3] PHP Notice:  Undefined index: asterisk_dialinPrefix in /var/www/custom/modules/Asterisk/include/controller.php on line 548, referer: http://192.168.1.5/index.php?action=ajaxui

I got hundreds of the first line.

**Comment by attaxia** [comment]
It was the custom field. I made a field named test and now it works. Maybe you should add it to the manual!

Thanks.

**Comment by blak3r** [comment]
Yeah.  Needs to get there.  Feel free to add it.
