### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by gl1tchh** [blak3r/yaai#139]
Hi,

When starting the installation of the module using the Sugar module loader, I get past the license agreement screen (I click accept), and I am then presented with the following line:

Including: /var/www/html/crm/cache/upload/upgrades/temp/1XMwz8/scripts/pre_install.php 

I'm running SugarCRM 6.3.0RC2 (Build 6943), PHP 5.3 and MySQL version 5.1 - any ideas as to what the issue could be? Running pre_install.php manually produces no output or errors.

Thanks in advance.

**Comment by blak3r** [comment]
Perhaps it's a memory limit issue or post limitation?

What version were you installing?

Any php errors in your log?

~Blake

**Comment by gl1tchh** [comment]
Hi,

I'm installing 6.2.0b, although I've tried with 6.2.0 as well.

upload_max_filesize and post_max_size are both set to 100MB, so I don't think it's that. I enabled the PHP error log (set error_log to /var/log/php_error.log) and re-ran, but it didn't produce any output.

**Comment by gl1tchh** [comment]
Hi, okay, got some output from the PHP error log:

Call to undefined method MysqliManager::get_columns() in /var/www/html/crm/cache/upload/upgrades/temp/UdBLDQ/scripts/pre_install.php on line 111

Any ideas?

**Comment by blak3r** [comment]
Try the new release: 
http://www.sugarforge.org/frs/?group_id=773

I don't depend on get_columns anymore.  But, honestly the fact that you don't have that method worries me... it's a standard PHP mysql method so not sure why you'd be getting that error.

**Comment by gl1tchh** [comment]
Hi,

So, I figured it must be something else on the system, as it installed perfectly on another instance of Sugar I have - I completely reinstalled Sugar (and the latest version of it), and it's working perfectly now. Thanks for all the feedback, I appreciate it! Fantastic plugin you've got here :)
