### ISSUE TITLE
no magic dial button sugar 6.5.14

### ISSUE THREAD

**Issue by davidzpe** [blak3r/yaai#145]
steps to reproduce
1. install sugarcrm 6.5.14
2 755 to cache directory for css 
3. upload callinize 3.6 and install
( after install u cant uninstall it )
4. create a new example account 
5. add fields to user edit layout
6. activate magic button field and others on the user panel
7. optional configure callinize to connect to your asterisk ( connection ok and waiting for calls )

and there is no buttons for magic dial
if u find dialout.js on the web it says this (i have to delete <> to show you)

> script src="custom/modules/Asterisk/include/javascript/dialout.js" type="text/javascript"
> Recargar la página para obtener la fuente: http://mysite.com/Sugar/custom/modules/Asterisk/include/javascript/dialout.js
> /script

same for callpopups

> script src="custom/modules/Asterisk/include/javascript/callPopups.js" type="text/javascript"
> Reargar la página para obtener la fuente: http://mysite.com/Sugar/custom/modules/Asterisk/include/javascript/callPopups.js
> /script

checked fields

> div align="left" width="100%" style="white-space: normal;"
> a class="listViewThLinkS1" href="javascript:sListView.order_checks("ASC", "phone_office" , "Accounts2_ACCOUNT_ORDER_BY")"
> /div

tried the thing with ListView.tpl copying to the other folder and change the last line

is there anything more that i have to do
and sorry for my english isnt the best.
Thanks for your hard work

**Comment by blak3r** [comment]
See if setting your language to English fixes the problem.  Maybe a mod
string issue or something.

I don't understand what you mean by (after install u cant install it)

**Comment by davidzpe** [comment]
srry i mean uninstall
and tested on another server works great
the server who doesnot works was using nginx instead of apache

**Comment by blak3r** [comment]
@davidzpe that's interesting... I can't think of a reason why nginx would have any impact on click to dial buttons.  You probably had a javascript error of some sort.
