### ISSUE TITLE
Delay with call popup

### ISSUE THREAD

**Issue by gl1tchh** [blak3r/yaai#147]
I'm having an issue when calls come in to the system - the call popup only appears a few seconds after the call has been answered, and not immediately, and this is a problem because I want to be able to see client information before the call gets answered - is there anything that could be causing this delay?

I also have a question in the same vein - when a call comes through to a ring group/queue with ringall as the strategy, is it possible to have the popup appear on each member of the group's system? Or doesn't the system allow for this?

**Comment by blak3r** [comment]
Paid versions resolves both issues.

The delay for ring groups and queues has been explained here before.  There is a good reason for it. 

I'm assuming the delay your seeing has todo with RingGroup calls?  

~blake

**Comment by felipro** [comment]
Hi,

I have delays of 10 seconds between incomming call to an extension and popup, is this an unsolved error or is a condition of the community version?

**Comment by blak3r** [comment]
If you have a lot of calls, then it's more of a limitation of the entire
architecture based around PHP.
PHP isn't multithreaded and there are webservice calls that happen in
response to requests...

Our new architecture is based on Node.js so we're able to do all that
processing async.

~blake
ᐧ

On Tue, Apr 8, 2014 at 12:35 AM, felipro notifications@github.com wrote:

> Hi,
> 
> I have delays of 10 seconds between incomming call to an extension and
> popup, is this an unsolved error or is a condition of the community version?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/blak3r/yaai/issues/147#issuecomment-39810980
> .

## 

Blake Robertson
blake@callinize.com
Callinize
