### ISSUE TITLE
cant get popups to work

### ISSUE THREAD

**Issue by davidzpe** [blak3r/yaai#148]
Hi there and thnx for yours hard work
i got some errors and hope maybe u could help me
calls with the magic dial button works but there is no popup
This syntax errors means something important?

> SyntaxError: syntax error
> window.callinize_relate_to_lead_enabled = ;
> SyntaxError: syntax error
> window.callinize_create_new_lead_enabled = ;
> SyntaxError: syntax error
> window.callinize_recording_enabled = ;

And this line:

> ready() hist_loaded: true ajaxUIEnabled = false

it needs to be true? do you know how? because on others post i see that value on true

And before i finish the call this lines appear:

> Logout Response: Response: Goodbye
> Message: Thanks for all the fish.
> is that fine or it should wait till my call finish?

thnx for all

This is the complete debug from firebug
104 is not an internal number is an external telephone operator

> SyntaxError: syntax error
> window.callinize_relate_to_lead_enabled = ;
> index....443d299 (línea 962, columna 42)
> 
> SyntaxError: syntax error
> window.callinize_create_new_lead_enabled = ;
> index....443d299 (línea 962, columna 43)
> 
> SyntaxError: syntax error
> window.callinize_recording_enabled = ;
> index....443d299 (línea 962, columna 37)
> 
> ready() hist_loaded: true ajaxUIEnabled = false
> callPopups.js (línea 913)
> loading yaai...
> 
> GET https://127.0.0.1/Sugar/index.php?entryPoint=...28e6-f326-edb1-f63a-5184c443d299&module=Accounts
> 200 OK     12.61s  
> sugar_...C0fW1mw (línea 4)
> 
> GET https://127.0.0.1/Sugar/index.php?entryPoint=AsteriskController&action=get_calls
> 200 OK     396ms  
> sugar_...C0fW1mw (línea 4)
> 
> CreateCall Action Response: Originate Params: Number: 9104, Channel: SIP/526, >Context: from-internal, Exten: 9104...
> Login Response: Asterisk Call Manager/1.3
> Response: Success
> Message: Authentication accepted
> Originate Response: Response: Success
> Message: Originate successfully queued
> Logout Response: Response: Goodbye
> Message: Thanks for all the fish.
> dialout.js (línea 70)
> 
> callPopups.js (línea 913)
> GET https://127.0.0.1/Sugar/index.php?entryPoint=AsteriskController&action=get_calls
> 200 OK     377ms

**Comment by davidzpe** [comment]
ok i got it sugar v6.5.14 works great with callinize 3.5 click dial works fine and popups and relationships.

**Comment by MazZzaka** [comment]
Hello! How exactly you resolved your problem, i have a similar problem using sugarsrm CE 6.5.14 and callinize community 3.6.0.

**Comment by davidzpe** [comment]
dont use callinize 3.6.0, instead use callinize 3.5.5
http://www.sugarforge.org/frs/?group_id=773
and if u use firefox u will need to turn off "mixed content block"

**Comment by MazZzaka** [comment]
Thank you bro,that helped me a lot, i still have the syntax error messages but pop ups work fine.I have a problem with the redirection functionality ,does it work on your crm?The message i get with chrome's debugger when try to redirect a call is  : 500 Internal Server Error.

**Comment by davidzpe** [comment]
it doesnt work for me either. but i didnt work on it, because the developer of the project callinize says he was going to release a new version.

**Comment by blak3r** [comment]
Hey guys,

I was on vacation for the past 10 days.  Sorry I didn't get the new release
out before I left.  I'll try and have this buttoned up by the weekend.
 Thanks for your patience.

**Comment by blak3r** [comment]
3.6.6 is out

**Comment by MazZzaka** [comment]
## "no popups at all" issue appears on 3.6.6 ,in chrome console it says this: 

Resource interpreted as Document but transferred with MIME type image/gif: "http://XXXXXXX/sugarcrm/index.php?entryPoint=getImage&imageName=blank.png".
ready() hist_loaded: undefined ajaxUIEnabled = false callPopups.js:924
loading yaai... callPopups.js:924
["."] callPopups.js:924
["."] callPopups.js:924
start renderTue Oct 08 2013 15:47:21 GMT+0300 (FLE Daylight Time) callPopups.js:924

## ["."]

**Comment by blak3r** [comment]
["."] --> there are no messages for the user to display.  So, issue would be further up the chain.  Check asterisk logger is spitting out events and is detecting the right extension etc etc.  See troubleshooting section.
