### ISSUE TITLE
Is AMI 1.3 supported?

### ISSUE THREAD

**Issue by jamski68** [blak3r/yaai#149]
With Asterisk 11.5 not getting calls logged or popups appearing, any help would be appreciated.

 AMI Version Info:

```
 Asterisk Call Manager/1.3
```

 AMI Login action raw response:

```
 Response: Success
 Message: Authentication accepted
```

 AMI Login was a _success!_
Waiting for call events...
[2013-08-22 16:06:54]
! --- Event -----------------------------------------------------------
!                Event --> Newchannel
!            Privilege --> call,all
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!         ChannelState --> 0
!     ChannelStateDesc --> Down
!          CallerIDNum --> 02079999999
!         CallerIDName --> 02079999999
!          AccountCode -->
!                Exten --> 12345566*222
!              Context --> from-pstn
!             Uniqueid --> 1377187710.157
! ---------------------------------------------------------------------
! AMI Event 'Newstate suppressed.
[2013-08-22 16:06:54]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!          CallerIDNum --> 02079999999
!         CallerIDName --> 02079999999
!             Uniqueid --> 1377187710.157
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
 CallerID Changed to: 02079999999
[2013-08-22 16:06:54]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!          CallerIDNum --> 02079999999
!         CallerIDName --> 02079999999
!             Uniqueid --> 1377187710.157
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
 CallerID Changed to: 02079999999
[2013-08-22 16:06:54]
! --- Event -----------------------------------------------------------
!                Event --> Newchannel
!            Privilege --> call,all
!              Channel --> SCCP/8261-00000053
!         ChannelState --> 0
!     ChannelStateDesc --> Down
!          CallerIDNum --> 8261
!         CallerIDName --> John Smith
!          AccountCode -->
!                Exten -->
!              Context --> from-internal
!             Uniqueid --> 1377187710.158
! ---------------------------------------------------------------------
[2013-08-22 16:06:54]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SCCP/8261-00000053
!          CallerIDNum --> 8261
!         CallerIDName -->
!             Uniqueid --> 1377187710.158
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
- Stripping prefix: 8
  CallerID Changed to: 261
  ! AMI Event 'Newstate suppressed.
  PHP Notice:  Undefined index: DialString in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1352
  [2013-08-22 16:06:54]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial
  !            Privilege --> call,all
  !             SubEvent --> Begin
  !              Channel --> SIP/VOIPFONE-SIP-0000004a
  !          Destination --> SCCP/8261-00000053
  !          CallerIDNum --> 02079999999
  !         CallerIDName --> 02079999999
  !     ConnectedLineNum --> <unknown>
  !    ConnectedLineName --> <unknown>
  !             UniqueID --> 1377187710.157
  !         DestUniqueID --> 1377187710.158
  !           Dialstring --> 8261
  ! ---------------------------------------------------------------------
  ! Dial Event src=SIP/VOIPFONE-SIP-0000004a dest=SCCP/8261-00000053
  ! Successfully created CALL record with id=-1
  Stripping callin prefix: 8
  CallerID is: 02079999999
  Looking for user extension number in: SCCP/8261-00000053
  Channel Matched SIP/### style regex. Ext is:8261
  Looking for user extension number in: SCCP/8261-00000053
  Channel Matched SIP/### style regex. Ext is:8261
  inbound_extension = 8261
  Inbound state detected... /^(sccp\/[1-9][0-9][0-9]?[0-9]?-|Local)/i is astMatchInternal eChannel= SIP/VOIPFONE-SIP-0000004a eDestination=SCCP/8261-00000053
  ! AMI Event 'ExtensionStatus suppressed.
  ! AMI Event 'Newstate suppressed.
  ! AMI Event 'ExtensionStatus suppressed.
  ! AMI Event 'Newstate suppressed.
  ! AMI Event 'Newstate suppressed.
  [2013-08-22 16:06:57]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewAccountCode
  !            Privilege --> call,all
  !              Channel --> SCCP/8261-00000053
  !             Uniqueid --> 1377187710.158
  !          AccountCode -->
  !       OldAccountCode -->
  ! ---------------------------------------------------------------------
  The AccountCode is
  Account Code ID is: 1377187710.158
  SELECT COUNT(id) as found FROM asterisk_log WHERE asterisk_id =1377187710.158
  Results are: Resource id #164

PHP Notice:  Undefined offset: 1 in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1865
SELECT \* FROM  WHERE id=''
UPDATE asterisk_log SET bean_module='', bean_id='', bean_name='' WHERE asterisk_id='1377187710.158'
[2013-08-22 16:07:02]
! --- Event -----------------------------------------------------------
!                Event --> Bridge
!            Privilege --> call,all
!          Bridgestate --> Link
!           Bridgetype --> core
!             Channel1 --> SIP/VOIPFONE-SIP-0000004a
!             Channel2 --> SCCP/8261-00000053
!            Uniqueid1 --> 1377187710.157
!            Uniqueid2 --> 1377187710.158
!            CallerID1 --> 02079999999
!            CallerID2 --> 8261
! ---------------------------------------------------------------------
DEBUG: Entered Bridge
DEBUG: bridge inbound, updating the Link state
Bridge isn't internal to internal
Internal Queue Event Detected
Internal Queue: SELECT id FROM asterisk_log WHERE remote_channel like 'SIP/VOIPFONE-SIP-0000004a' and direction='I' and (channel = '' OR channel is NULL)
DEBUG: NO Queue BRIDGE ROWS found
[2013-08-22 16:07:10]
! --- Event -----------------------------------------------------------
!                Event --> HangupRequest
!            Privilege --> call,all
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!             Uniqueid --> 1377187710.157
! ---------------------------------------------------------------------
[2013-08-22 16:07:10]
! --- Event -----------------------------------------------------------
!                Event --> Bridge
!            Privilege --> call,all
!          Bridgestate --> Unlink
!           Bridgetype --> core
!             Channel1 --> SIP/VOIPFONE-SIP-0000004a
!             Channel2 --> SCCP/8261-00000053
!            Uniqueid1 --> 1377187710.157
!            Uniqueid2 --> 1377187710.158
!            CallerID1 --> 02079999999
!            CallerID2 --> 8261
! ---------------------------------------------------------------------
DEBUG: Entered Bridge
Bridge isn't internal to internal
Internal Queue Event Detected
Internal Queue: SELECT id FROM asterisk_log WHERE remote_channel like 'SIP/VOIPFONE-SIP-0000004a' and direction='I' and (channel = '' OR channel is NULL)
DEBUG: NO Queue BRIDGE ROWS found
! AMI Event 'Newstate suppressed.
! AMI Event 'ExtensionStatus suppressed.
[2013-08-22 16:07:10]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SCCP/8261-00000053
!             Uniqueid --> 1377187710.158
!          CallerIDNum --> 8261
!         CallerIDName --> <unknown>
!     ConnectedLineNum --> 02079999999
!    ConnectedLineName --> 02079999999
!          AccountCode -->
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
 In DialEnd... 1377187710.158
PHP Notice:  Undefined index: asterisk_only_log_calls_matching_user_extension in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 710
# +++ findCallByAsteriskId(1377187710.158)

! Warning, results set was empty!
PHP Notice:  Undefined index: DestUniqueID in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1352
PHP Notice:  Undefined index: Destination in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1352
PHP Notice:  Undefined index: CallerIDNum in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1352
PHP Notice:  Undefined index: DialString in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1352
[2013-08-22 16:07:10]
! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> End
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!             UniqueID --> 1377187710.157
!           DialStatus --> ANSWER
! ---------------------------------------------------------------------
 In DialEnd... 1377187710.157
PHP Notice:  Undefined index: asterisk_only_log_calls_matching_user_extension in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 710
# +++ findCallByAsteriskId(1377187710.157)

! Found entry in asterisk_log recordId=-1
PHP Warning:  Invalid argument supplied for foreach() in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1561
Looking for user extension number in: SCCP/8261-00000053
Channel Matched SIP/### style regex. Ext is:8261
### +++ findUserByAsteriskExtension(8261)

! Assigned user id set to f3d818bc-aeac-4feb-60b1-4b6afb9252a8
 Measured call duration is 9 seconds
PHP Notice:  Undefined index: id in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 995
! Call is not related to any record (no matches)
! Call start was 2013-08-22 16:06:55
PHP Notice:  Undefined index: id in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1007
 Updating record in /Calls/ id=...
PHP Notice:  Undefined index: name in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1010
 NAME:
PHP Notice:  Undefined index: description in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1011
 DESCRIPTION:
PHP Notice:  Undefined index: id in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1021
Cleaning up Failed Calls part1, asterisk_id = 1377187710.157
[2013-08-22 16:07:13]
! --- Event -----------------------------------------------------------
!                Event --> SoftHangupRequest
!            Privilege --> call,all
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!             Uniqueid --> 1377187710.157
!                Cause --> 16
! ---------------------------------------------------------------------
[2013-08-22 16:07:13]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SIP/VOIPFONE-SIP-0000004a
!             Uniqueid --> 1377187710.157
!          CallerIDNum --> 02079999999
!         CallerIDName --> 02079999999
!     ConnectedLineNum --> 8261
!    ConnectedLineName --> John Smith
!          AccountCode -->
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
 In DialEnd... 1377187710.157
PHP Notice:  Undefined index: asterisk_only_log_calls_matching_user_extension in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 710
# +++ findCallByAsteriskId(1377187710.157)

! Found entry in asterisk_log recordId=-1
PHP Warning:  Invalid argument supplied for foreach() in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1561
Looking for user extension number in: SCCP/8261-00000053
Channel Matched SIP/### style regex. Ext is:8261
### +++ findUserByAsteriskExtension(8261)

! Assigned user id set to f3d818bc-aeac-4feb-60b1-4b6afb9252a8
 Measured call duration is 12 seconds
PHP Notice:  Undefined index: id in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 995
! Call is not related to any record (no matches)
! Call start was 2013-08-22 16:06:55
PHP Notice:  Undefined index: id in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1007
 Updating record in /Calls/ id=...
PHP Notice:  Undefined index: name in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1010
 NAME:
PHP Notice:  Undefined index: description in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1011
 DESCRIPTION:
PHP Notice:  Undefined index: id in /home/devcrm/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1021
Cleaning up Failed Calls part1, asterisk_id = 1377187710.157

**Comment by blak3r** [comment]
Please provide more info. Please see the troubleshooting section in user manual.

I haven't officially tested with 11.5 but as far as I know it's still AMI v1.1 so should work. 

~blake

**Comment by jamski68** [comment]
I have pasted the log on the post, SugarCRM 6.5.12 and Elastix 2.4 and Asterisk 11.5.0

**Comment by jamski68** [comment]
Got this working by downgrading to 3.5.5 :)

**Comment by blak3r** [comment]
Good to know... we should have a new build coming out soon.

**Comment by jamski68** [comment]
Great, let me know if you want any logs from my efforts with 3.6.0

**Comment by blak3r** [comment]
@jamski68 I have a new build.  If you shoot me an email to blake.robertson [at] gmail.com I could give it to you for testing.  Would like to see if it fixes your issues prior to making it public.

**Comment by intuitivevoice** [comment]
I'm having the same issue running on asterisk 1.4.42. I will try downgrading to 3.5.5.

**Comment by blak3r** [comment]
Asterisk 1.4 is ami 1.0. Not 1.3. 
Ami 1.0 isn't fully supported. 

What issue are you having?

**Comment by intuitivevoice** [comment]
I have an 11.5 box I will try this morning. I am not getting call matches, no call notifications… I am seeing these errors.

PHP Notice:  Undefined index: asterisk_only_log_calls_matching_user_extension in /var/www/html/cloudcrm/custom/modules/Asterisk/asteriskLogger.php on line 683

# +++ findCallByAsteriskId(PBX-1379662715.16917)

! Warning, results set was empty!

PHP Notice:  Undefined index: CallerIDNum in /var/www/html/cloudcrm/custom/modules/Asterisk/asteriskLogger.php on line 1360

PHP Notice:  Undefined index: ConnectedLineNum in /var/www/html/cloudcrm/custom/modules/Asterisk/asteriskLogger.php on line 1360

**Comment by blak3r** [comment]
None of those things are really errors per se.  Try the fake call utility
and see if that creates a popup.

Did you configure your user profile in studio etc?

**Comment by jamski68** [comment]
3.6.6 now can't connect to Sugar FATAL: SOAP login failed,

**Comment by blak3r** [comment]
Didn't make any significant changes to soap code.  So, check your
password... is your system language english?  Someone mentioned that having
dutch as their language broke soap login.

**Comment by jamski68** [comment]
Language is English same username and password on staging and live sugar install works when rolling back to 3.5.5, we are using LDAP

**Comment by blak3r** [comment]
@jamski68 btw 3.6.7 should work for you.

**Comment by intuitivevoice** [comment]
Thanks I’ll check it out.. Been swamped. We really do need to connect soon though.
