### ISSUE TITLE
fonality compatibility

### ISSUE THREAD

**Issue by arm123** [blak3r/yaai#150]
Hi,

Can you please let me know how to make fonality work with yaai?
Is there any possibility? 

Please let me know.

Thanks,
Arm

**Comment by blak3r** [comment]
Does fonality expose AMI?  I heard in the past they do not.
AMI == Asterisk Manager Interface 

If they do, then it'll work.

**Comment by askhogan** [comment]
Fonality does not have an API.  They want you to use their own desktop
product HUD.

**Comment by arm123** [comment]
Ohh, that's a big problem for me then.
Any possibility on using AMI with fonality?

Thanks,
Arm

**Comment by blak3r** [comment]
We're not fonality customers.  Please ask Fonality to see if they can expose it for you.
Let us know what they say.

**Comment by blak3r** [comment]
I'm closing.  If you hear from fonality, please let us know.  We'd be interested.
