### ISSUE TITLE
YAAI with SugarCRM Enterprise 6.7.2

### ISSUE THREAD

**Issue by ozirescruz** [blak3r/yaai#152]
I'd like to install YAAI in Sugar 6.7.2, I can't load the module. Is it possible? How?

Thank You.

**Comment by blak3r** [comment]
If it' an on premise version of sugar then yes.  I wasn't aware 6.7 was out yet so it hasn't been tested on it.
I'm close to putting a new release on sugarforge anyway... I'll put this in the next version.
1. Open Zip file.
2. Open manifest.php 
3. Find this code block and change the [0-6] to [0-7]
                         'regex_matches' =>
                         array (
                           1 => '6.4.\d',
                           2 => '6.[0-6].\d',  /*\* matches 6.1.x,6.2.x,6.3.x,6.4.x,6.5.x,6.6.x **/
                                ),
                         ),
