### ISSUE TITLE
what version of sugarcrm works perfect with what version of yaai

### ISSUE THREAD

**Issue by davidzpe** [blak3r/yaai#153]
Since i give up with trying and getting new issues, i wanna ask what version of yaai with what version of sugarcrm and with what version of php works perfect?, so i dont get any errors like deprecated, no popups, no redirected calls, or no users extensions match on incoming calls, etc.

**Comment by blak3r** [comment]
Hi David,

What kind of issues are you having.  I just put a new release up. 3.6.5.
6.5.x in Sugar is the most tested...
2.6.0b is very stable.
3.5.5. is known good.
3.6.5 is less proven but fixed some issues on 3.6.0... but not major ones
like popups don't work at all....

~blake

**Comment by blak3r** [comment]
Try 3.6.6. released it a week or two ago.
