### ISSUE TITLE
asterisk+yaai+sugar example

### ISSUE THREAD

**Issue by ozirescruz** [blak3r/yaai#154]
I've been trying to make it works but no success. Everything installed and seems to be ok. I need sip.conf, extensions.conf examples and what to fill in SugarCRM callinize config and in Users field Personal extension(s). When I click in dial icon this message appears:

Click to Dial Failed:

---

Originate Params: Number: 2000, Channel: SIP/2000, Context: from-internal, Exten: 2000...
Login Response: Asterisk Call Manager/1.3

Response: Success

Message: Authentication accepted
Originate Response: Response: Error
Message: Extension does not exist.
Logout Response: Response: Goodbye

Message: Thanks for all the fish.

Thank you.

**Comment by blak3r** [comment]
That is coming from asterisk...

Message: Authentication accepted
Originate Response: Response: Error
Message: Extension does not exist.  <-----

Sounds like you don't have an extension in your asterisk box

**Comment by ozirescruz** [comment]
This is my /etc/asterisk/sip.conf

[2000]
type=friend
context=my-phones
secret=1234
host=dynamic

[2001]
type=friend
context=my-phones
secret=1234
host=dynamic

and my /etc/asterisk/extensions.conf:

[my-phones]
exten => 2000,1,Dial(SIP/2000)
exten => 2001,1,Dial(SIP/2001)

**Comment by blak3r** [comment]
dunno man inspect what is getting sent to asterisk.  If it's sending your
extension as 2000.... and it's saying invalid extension then the issue is
with asterisk not callinize.

I'd look in your asterisk logs.

I did just notice that "Number: 2000" and your Extension is 2000... that
could be the problem.  Are you clicking on a user that has their phone
number as 2000?

Try with external number

**Comment by ozirescruz** [comment]
Sugar configs:

![sc1](https://f.cloud.github.com/assets/5469222/1186642/40b077d2-2312-11e3-9050-4f7ca485aee8.jpg)
![sc3](https://f.cloud.github.com/assets/5469222/1186643/40b90e92-2312-11e3-9f04-2f7eb590db8d.jpg)
![sc2](https://f.cloud.github.com/assets/5469222/1186644/40b96842-2312-11e3-978d-6729c9660534.jpg)

**Comment by blak3r** [comment]
You need to figure out why Number = 2000.
Your config isn't the problem.  I suspect your clicking to dial on a users
object where the phone number is 2000.

See previous response.

**Comment by ozirescruz** [comment]
This number 2000 is only for testing. Don't you have an example config that works and I can use to connect with x-lite or zoiper user from sugarcrm Contact for example? Just for testing, localy.

**Comment by blak3r** [comment]
Never tried calling myself. Through click to dial. Internal to internal calls aren't supported in the rest of the code base. 

I dunno what your doing.
