### ISSUE TITLE
Clicking on the contact name sends to localhost

### ISSUE THREAD

**Issue by ghost** [blak3r/yaai#155]
We have sugarcrm 6.5 and asterisk 1.6 on two different servers.
After I get a incoming call popup, the section of the popup where it shows the contact's name
If I click on the contact name it sends me to a link that looks like "http://localhost/....." instead of "http://xxx.xxx.xxx.xxx/...."

**Comment by blak3r** [comment]
Check your site_url in your config.php. Pretty sure that's what is used to create those URLs.

**Comment by ghost** [comment]
Thank you blak3r.
The site_url and host_name both were set to localhost in the machine.
Changing them to the IP solved it.

**Comment by blak3r** [comment]
Thanks for letting me know that fixed it!
