### ISSUE TITLE
asteriskLogger.php MySQLmysql_connect(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by zoumhussein** [blak3r/yaai#159]
Hello Blak3r,

First of all thanks for this wonderful middle-ware!
I'm facing some errors (my apologies if eventually this is not link to your code... I've been looking for days, trying few things which do not work...so if you can help)

The error is: PHP Warning:  mysql_connect(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /opt/sugarcrm-6.5.15/apps/sugarcrm/htdocs/custom/modules/Asterisk/asteriskLogger.php on line 177
(See the full log in attached)

SugarCRM: 6.5.15
Yaai: 3.6.5 (i've tried also the latest 3.6.6 with the same result)

I did not get any pop-ups when receiving well configured calls. 
(the asteriskLogger suddenly stop when receiving call event )

SOAP Login is OK
Click2Dial Is OK and works great
AMI connection is OK too (According to the previous point and to the asteriskLogger logs)
Call notification checkbox added in studio and checked
PopUp not working when receiving call (i used firefox 22-24 and Chrome 30)

Regards,
![21-10-2013 01-48-56](https://f.cloud.github.com/assets/2742871/1369268/3a93db00-39e2-11e3-8464-845d66e34179.jpg)
![21-10-2013 01-48-30](https://f.cloud.github.com/assets/2742871/1369269/3a980978-39e2-11e3-9976-c07b8ac091d8.jpg)
![Uploading 21-10-2013 01-47-22.jpg . . .]()

**Comment by blak3r** [comment]
mysql_connect uses the settings in your config.ini.
You shouldn't be getting an error like that.

**Comment by zoumhussein** [comment]
After digging again a lil bit that's was due to "Full Stack Installation mode" which brings it's own MySQL instance...
I've done new install based on .zip instead of installer bin: script goes well but no popup still. 
I'm closing then this false issue (for the popup matter i will search in the previous issues for solution before opening new one)

Regards,

**Comment by blak3r** [comment]
try 3.6.7 i hope that fixes the popup issue... if not then 3.5.5 works for
people.  Please let me know if 3.6.7 fixes it for you.

**Comment by zoumhussein** [comment]
Yes the 3.6.7 solved the issue. 
Pop up OK right now. 

Thanks

**Comment by blak3r** [comment]
Thanks for confirming
