### ISSUE TITLE
Calls related to just an account don't show account on the Call Popup.

### ISSUE THREAD

**Issue by superles** [blak3r/yaai#16]
AMI 1.1
Sugarcrm 6.4.4
Yaai 2.3.0.9 for v6.x

Before i added relate to account
# +++ findCallByAsteriskDestId(1336693188.49)

! FindCallByAsteriskDestId - Found entry in asterisk_log recordId=39021f57-59ef-0017-5dbf-4fac514153df
Looking for user extension number in: SIP/100-00000031
Channel Matched SIP/### style regex.  Ext is:100
# +++ findUserByAsteriskExtension(100)

! Assigned user id set to 1
# Measured call duration is 12 seconds

Adding INBOUND Failed Call, id=1336693188.49, call_id = 39021f57-59ef-0017-5dbf-4fac514153df
# +++ find AccountByPhoneNumber(0555559975)

! No results returned
# +++ find ContactByPhoneNumber(0555559975)

  findSugarObjectByPhoneNumber: Contact query components- Phone: 0555559975   RegEx: (0[^\d]_5[^\d]_5[^\d]_5[^\d]_5[^\d]_5[^\d]_9[^\d]_9[^\d]_7[^\d]_$
Found multiple contacts -- all belong to same account, associating call with account.
! Invalid Arguments passed to setRelationshipBetweenCallAndBean# (INBOUND) now updating record in /Calls/ id=39021f57-59ef-0017-5dbf-4fac514153df...
NAME: *_ Automatic record **
DESCRIPTION:
Cleaning up Failed Calls part1, asterisk_id = 1336693188.48

After i added relate to account
# +++ findCallByAsteriskDestId(1336731984.103)

! FindCallByAsteriskDestId - Found entry in asterisk_log recordId=1af3307c-ca07-7341-b31a-4face91b502e
Looking for user extension number in: SIP/100-00000067
Channel Matched SIP/### style regex.  Ext is:100
# +++ findUserByAsteriskExtension(100)

! Assigned user id set to 1
# Measured call duration is 27 seconds

Contact Id already set by callListener to: 7f1c2f7a-eeea-0b2a-acf2-4fabf93f6b95
# Establishing relation to Contacts... Call ID: 1af3307c-ca07-7341-b31a-4face91b502e to Bean ID: 7f1c2f7a-eeea-0b2a-acf2-4fabf93f6b95

PHP Notice:  Undefined index: error in /var/www/custom/modules/Asterisk/asteriskLogger.php on line 1353
PHP Notice:  Undefined index: result_count in /var/www/custom/modules/Asterisk/asteriskLogger.php on line 1357
! No results returned
# +++ findAccountForContact(7f1c2f7a-eeea-0b2a-acf2-4fabf93f6b95)

PHP Notice:  Undefined index: result_count in /var/www/custom/modules/Asterisk/asteriskLogger.php on line 1357
! No results returned
# Associated account is dcb0fa78-818a-e87c-aa68-4face542a163

! Call start was 2012-05-11 10:26:25
# (INBOUND) now updating record in /Calls/ id=1af3307c-ca07-7341-b31a-4face91b502e...

**Comment by superles** [comment]
Also, if your phone is related to account, then the company name does not appear in popup window.

**Comment by blak3r** [comment]
Please explain how many contacts had a matching phone number and what account they were set to in case 1.

Then explain what was happing for case 2.

**Comment by superles** [comment]
accounts and contacts have one phone number each, and they are different 

1 case:

in sugarcrm only 1 contact(test base) and 0 account

2 case:

1 account and 1 contact related to this account

3 case:

1 account and 1 contact related to this account. Incoming call on phone related to account

In 1 case when receive inbound call , pop up box without contact_id and account_id

In 2 case - alright, in pop up box name(contact_id) and Account(account_id)

In 3 case when receive inbound call , pop up box without account_id and contact_id

**Comment by blak3r** [comment]
Case 1 is a bug in callListener... I actually have a TODO in there... I think I just need to make it an OUTER JOIN... I didn't test that yet.  Kind of thought contacts without accounts were an extremely rare case.

For case 2 i'm assuming you're saying you have one contact with the phone number and it is related to an account.  The result is correct the call popup has name + account so there is no issue with this case.

Your case 3 is the same as case 2...

**Comment by superles** [comment]
In the second case everything is OK. I wrote it for comparison.

I think that in third case popup box must have Account name. Because the phone number belongs to Account.

**Comment by blak3r** [comment]
I don't understand the difference between your case 2 & case 3. 

Both say: 
"1 account and 1 contact related to this account" 

Please explain case 3 better.

**Comment by superles** [comment]
Sorry for my English. This is not my native language. I mean that in the second case, we called on the number of contact and it worked. In the third case, we called on the phone account, and popupbox was empty (not work)

**Comment by blak3r** [comment]
Ahh Ha.  Yes this is indeed a bug.  Thanks for reporting.

**Comment by blak3r** [comment]
===CASE 1: Number matches Phone number of Contact.  Contact is not related to any account===
I kind of fixed it by added some is null cases.
and (ac.deleted='0' OR ac.deleted is null) and (a.deleted='0' or a.deleted is null)

There is still a problem with the query such that if a Contact was related to account.  Then that relation was deleted... the query will not return results.  In order to make that case work, the query would have to be broken up into subqueries I think.  I'm not very strong with SQL so i'm not really sure how to fix it.

=== CASE 3: Phone matching Account doesn't appear in notification popup ===

This case is tricky as it'll require adding another expensive query to callListener.  I'll have to duplicate the phone number lookup query to only look in accounts.  Then, i'll need to add a new database column to asterisk_log to cache the result in.  

The problem with adding this feature in is it has potential to be a big performance.  Doing phone number lookups requires a full table scan which in certain cases would happen each time callListener was invoked if the number didn't match any contacts or accounts.

I dont know when I'll be able t

**Comment by superles** [comment]
Account is not so important, we can return to it later. Other changes introduced.

**Comment by blak3r** [comment]
Improvements to query were suggested here.  I haven't incorporated them yet... it'll fix case 1 completely.

https://github.com/blak3r/yaai/commit/6e24e2df62ade78c2135ff8756952761faa0c452#commitcomment-1472245

**Comment by blak3r** [comment]
This should be completely resolved now... cept case 3 which i'm not going to attempt to implement right now.

Probably needs more testing in other cases. 

@superles thanks again!
