### ISSUE TITLE
Pop-ups are not working

### ISSUE THREAD

**Issue by spookyx** [blak3r/yaai#160]
Fresh install
Callinize Yaai 3.6.7
SugarCE 6.5.16

Asterisk_logger working properly.
Calls are appearing in the Calls module.
I can dial from within Sugar.
## From the console:

[11:37:15.365] GET .../sugarce/index.php?entryPoint=AsteriskController&action=get_calls&_=1383039435313 [HTTP/1.1 200 OK 127ms]

I dont see any error? Any ideea?

**Comment by zoumhussein** [comment]
Hi spookyx, 

I don't know if that can help you, but i've successfully validate the 3.6.7 version with sugarCE 6.5.15
(in a previous issue https://github.com/blak3r/yaai/issues/159): Every features were just running fine. 
If you are not obliged in some way to use the 3.6.16, you may consider the previous one. 
I can share my settings if wanted. 

That was my little (maybe useful) contribution.

Regards,
Zoumana

**Comment by spookyx** [comment]
From asteriskLogger.log:
Notice: Undefined index:  event in ...../sugarce/custom/modules/Asterisk/asteriskLogger.php on line 439
Notice: Undefined index:  event in ...../sugarce/custom/modules/Asterisk/asteriskLogger.php on line 613
Notice: Undefined index:  asterisk_only_log_calls_matching_user_extension in ...../sugarce/custom/modules/Asterisk/asteriskLogger.php on line 716
Notice: Undefined index:  Cause-txt in ...../sugarce/custom/modules/Asterisk/asteriskLogger.php on line 1005

and this, which may not be an error after all:
[1383055838.4219] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)

Hi Zoumana.
Thanks for the response. I am looking through the logs... can't find such an issue like you had. I will keep searching for the problem.
At the moment I was able to find those notices in the asteriskLogger log.

**Comment by spookyx** [comment]
Does this has to do with the fact that it is showing improper call information?

For example:
Inbound call from a cell phone. PBX rings multiple groups and then into several extensions and even goes to follow-me settings (as in ringing other cell phone). The Follow Me Ring gets a busy tone and call is answered by one of the extensions in the group.
Yaai logs 2 events like this:   Inbound     *\* Automatic record **
No callerid is displayed, with status In Limbo. No other information appears for these two records.

**Comment by blak3r** [comment]
@spookyx a) make sure you're not doing internal to internal calls (ie call in from a cell phone)....

I'd start by doing outbound calls... If you're not getting call popups then it must be something with extracting the user's extension.  You should see some lines in your log saying something to the effect of "Extracting user extension from channel.... XXX found..."

If it's not finding the correct extension, then a regex needs to be tweaked.

**Comment by spookyx** [comment]
I was just looking and found this:
Matched User REGEX. Regex: 400
This is my ring group, but my extensions are 401, 402 and so on. Then I have added 400 as well to my info and immediately the pop-up appeared. I think that solves the mystery.

So, if anyone has this issue, try to set your ring group number as well to your extension list like this: 400,401,402.

**Comment by blak3r** [comment]
That's gonna only work for one user... All calls are going to get assigned
to that user.
In the pro version there is better support for ring groups and queues...
you can set specific ring groups for each user.

In the community edition, you shouldnt need to do that though... it should
create call events for each user it calls and in those bridge events it
gets linked to the user extension.
