### ISSUE TITLE
How to match phone numbers with Targets instead of just Accounts & Contacts?

### ISSUE THREAD

**Issue by ViktorNova** [blak3r/yaai#163]
Finally just got this working! 

I noticed that it only matches dialed numbers to existing _contacts_ and _accounts_, but what would I need to do to make it match existing _targets_? I am setting this up for a call center calling off of a massive list of imported targets and need to make Yaii pull up those records instead of just matching contacts. 

It's interesting, even when dialed from a click-to-dial button from the Targets list, it still says that no record is matched. Thanks! This software is rad!

**Comment by blak3r** [comment]
Glad you like it!

Checkout callinize pro... handles leads and more.  www.callinize.com

**Comment by blak3r** [comment]
Shoot me an email blake [at] callinize.com

On Wed, Nov 13, 2013 at 11:04 PM, Blake Robertson <blake.robertson@gmail.com

> wrote:
> 
> Glad you like it!
> 
> Checkout callinize pro... handles leads and more.  www.callinize.com
>

**Comment by ViktorNova** [comment]
Aww, I was hoping that wasn't the answer ;)

**Comment by blak3r** [comment]
Pro is so rad though... just wait and see in 1 month.

**Comment by ViktorNova** [comment]
Will do! I am open to it but want to explore the possibilities of CE first. Thank for responding so fast!
