### ISSUE TITLE
Possible to add more fields to call popups?

### ISSUE THREAD

**Issue by ViktorNova** [blak3r/yaai#164]
Is it possible to add custom fields created in Studio to the call popup window? I got a drop down menu I need to add to every call and require it to be updated before allowing the user to save/close the popup 

Is this possible now, even if it means modifying a php file or something? If not could you point me in the right direction of where to begin some hackery? =D

**Comment by blak3r** [comment]
@ViktorNova This is pretty complex.  Gonna have to say no.  It'd requiring editing a lot of files from the controllers --> handlebars templates --> javascript code that posts it.... etc.

If you are interested in this type of thing, I suggest checking out callinize pro.  
It's a completely rewritten architecture and doing that there might be more feasible.

**Comment by ViktorNova** [comment]
Thank you for the honest answer, sounds like something I don't want to get in to =) 
Callenize Pro sounds really cool, I will check it out in the future!
