### ISSUE TITLE
How to add Magic Dial button to Edit View?

### ISSUE THREAD

**Issue by ViktorNova** [blak3r/yaai#167]
This maybe sounds like a weird question, but I need to add magic dial buttons to Edit View for Contacts. This has to be possible, how might I try to get that working?

**Comment by blak3r** [comment]
Ehhhh sounds like a bad idea. But, edit dialOut.js. Figure out the appropriate JavaScript selector for jquery

**Comment by ViktorNova** [comment]
Cool, I will start there!

I only have a loose grasp at how Sugar actually works on the inside, but would it make sense to put 

```
<span class='phone'>{sugar_phone value=$phone usa_format=$usa_format}</span>
```

somewhere in the edit view's php file?

I tried putting it at the top of modules/Contacts/views/view.edit.php but got a blank page ;)

I only know enough to be dangerous at this point, but am determined to figure it out!

**Comment by blak3r** [comment]
Ehhh. No. Don't think so. 
Just do it with jquery somehow. 

If dialout.js isn't loaded on edit view look at AsteriskJS.php. That controls what pages the JavaScript is loaded on. I don't think edit view is filtered but it might.

**Comment by ViktorNova** [comment]
Got it working perfectly! I first tried the jquery route, but it was already looking for the class "phone", which is what the input field in edit view was already set as. The reason it doesn't render a call button is because there's no actual "normal" html text displaying the phone number in edit mode, instead it is an input field with the phone number pre-populated using value=""

Here's what I did to get it working - 

In /custom/modules/Contacts/metadata/editviewdefs.php

```
      1 => 
      array (
        'name' => 'some_unique_name',
        'comment' => 'Work phone number of the contact',
        'label' => 'some_unique_label',
        'customCode' => '<div class="phone" name="phone_work" /> {$fields.phone_work.value}',

      ),
```

I added this to the top panel (named "DISPOSITON" in this screenie) which is a custom panel made in studio that previously only had one thing in it. If 'name' and 'label' are set to something unique, you can still mess with Edit View in the studio and not lose this customization

This setup is awesome, it allows telemarketers to cruise through callback lists in edit mode and still have click-to-dial functionality 

![image](https://f.cloud.github.com/assets/3234333/1710971/b763bd0a-6140-11e3-82cf-5bf9d778a96c.png)

Very nice!

**Comment by ViktorNova** [comment]
Ok, there is still a little problem here - when an outgoing call is made via the edit interface with my above little hack, the call popup is not saving any changes. 

In fact, the call popup for a call made while in edit mode doesn't ever go away! Like it thinks I never clicked Save Memo. It goes away when clicked, but then comes back, sometimes on it's own, but always when the page is refreshed or a new page is loaded. So after making a few calls, the screen begins to endlessly stack up with call boxes that won't go away

Call popups are working and saving notes just fine otherwise, through  list view and detail view. 

Any idea where to look next?

**Comment by blak3r** [comment]
I don't think this issue is related to your change.  I've heard others
report issues with the popups disappearing as well.

Since you're a developer... could you look to see if there are any PHP
errors or javascript errors when you try and do the save.

**Comment by ViktorNova** [comment]
Sorry for the radio silence, I have been focused on other things here and this was put on the back burner, but I am about to tackle this again and will absolutely help debug the problem

**Comment by blak3r** [comment]
Great thanks!

**Comment by ViktorNova** [comment]
I'm closing this issue since the original problem is fixed, a la my mini hack above 

(and I'm going to open a new issue about the call popups not saving, as I'm running into that in normal view too)
