### ISSUE TITLE
SugarCRM on WebServer, Asterisk/FreePBX on AWS

### ISSUE THREAD

**Issue by doggiedaddy1** [blak3r/yaai#168]
I'm running on separate servers, SugarCRM on my hosting account as SAAS and FreePBX latest distro on AWS.  I realize (now) that asteriskLogger is the brains of this, operates as a service, and should be on the same server as SugarCRM.  Any workarounds?  Could the asteriskLogger be ran from the AWS server?

**Comment by blak3r** [comment]
No.  But, our new SaaS platform will work for you perfectly.

Should me an email blake [at] callinize.com and I'll get you an invite!
