### ISSUE TITLE
Localization support in asteriskLogger

### ISSUE THREAD

**Issue by trustmaster** [blak3r/yaai#17]
Non-English speaking users complain that they cannot use this module in production because it is not localized. I would update the Russian locale, but asteriskLogger.php should support localization of SOAP fields sent to SugarCRM first.

**Comment by blak3r** [comment]
I don't know what you mean by localization of soap fields. 

There are definitely some thing that need to be resolved in call listener. Especially any JavaScript generated items like "save" etc.

**Comment by trustmaster** [comment]
Examples:
https://github.com/blak3r/yaai/blob/master/SugarModules/modules/Asterisk/asteriskLogger.php#L528
https://github.com/blak3r/yaai/blob/master/SugarModules/modules/Asterisk/asteriskLogger.php#L529
https://github.com/blak3r/yaai/blob/master/SugarModules/modules/Asterisk/asteriskLogger.php#L712

These are displayed in Calls module literally as "Held", "Missed", etc.

**Comment by blak3r** [comment]
I see.  I'm not sure what the proper way is to do that.

I thought that those were standard drop down values.  I assumed that each language just had a different label.
(In other words, when you look in the drop down editor you have a name/value).  I thought the names were all in English.

Did you already solve this problem in your fork of my code?

**Comment by superles** [comment]
+1 It would be super.

**Comment by trustmaster** [comment]
Well, in SugarAsterisk I simply include the localization file from asterisk module and put the strings there:

https://github.com/trustmaster/SugarAsterisk/commit/f33332ce704fdb5957cca3515923eb681056bc11
https://github.com/trustmaster/SugarAsterisk/blob/master/SugarModules/modules/Asterisk/language/en_us.lang.php
https://github.com/trustmaster/SugarAsterisk/blob/master/SugarModules/modules/Asterisk/asteriskLogger.php#L408

**Comment by blak3r** [comment]
Any chance you submit a pull request with those changes?

**Comment by trustmaster** [comment]
As soon as I eventually install myself an asterisk instance :)

**Comment by blak3r** [comment]
@trustmaster any progress on getting an asterisk instance?

**Comment by trustmaster** [comment]
Finally got it running. Sorry, been busy with other projects. I'll try to hack it today.

**Comment by miksir** [comment]
Please, look this issue: https://github.com/blak3r/yaai/issues/44
blak3r was right - Held, Missed etc - it's values, not display text. It cant be translated. This text must be translated in Calls module of  Sugar (and it translated well for me).
