### ISSUE TITLE
PHP Warning:  fopen(): & fclose()

### ISSUE THREAD

**Issue by Vario1979** [blak3r/yaai#172]
Hi guys, 

I was getting many error, but finally all of them are solved. 
All I'm getting now are these two: 

PHP Warning:  fopen(): Filename cannot be empty in /home/sales/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1498
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /home/sales/public_html/custom/modules/Asterisk/asteriskLogger.php on line 1505

Sugarcrm CE 6.5.
Callinize 3.6.9 
Asterisk 1.8 set up on different box. 
AMI and SOAP are correct.

**Comment by blak3r** [comment]
What's the problem your having. Those are harmless. 

Sent via mobile

**Comment by Vario1979** [comment]
Well, 
I do not receive any calls, outbound is also not working.
This is yet testing environment, had to be configured before going live.

**Comment by blak3r** [comment]
Ok.  Did you look at the troubleshooting section?

It's not that error that is causing you problems.

**Comment by Vario1979** [comment]
hi again, 
I dont get any errors in output, but nothing seems to be working. No popup, no call notification. 
Do You have experience of setting it up with kerio operator?
