### ISSUE TITLE
Add "Create new Contact" link to the popup

### ISSUE THREAD

**Issue by trustmaster** [blak3r/yaai#18]
If there is no contact/account found for the inbound caller, a link to create a new contact for that number should appear in the popup.

I know it is somewhere on the TODO list and I once sent Blake the snippet with implementation from SugarAsterisk module, but I open this ticket so it's easier to track.

**Comment by superles** [comment]
Version 2.3 has a link to create a contact and link relate to an existing

**Comment by trustmaster** [comment]
Thanks, I'm not very up2date :)

**Comment by blak3r** [comment]
Thanks for your help @superles
