### ISSUE TITLE
Can not install  the module Callinize - community Edition, 3.6.9 (Oct 29, 2013) in sugarcrm Version 6.5.16 (Build 1082) - amazon aws (cloud) 

### ISSUE THREAD

**Issue by fsb2099** [blak3r/yaai#192]
When i try to upload the Callinize - community Edition module in the sugarcrm Version 6.5.16 (Build 1082) - amazon aws (cloud) the instalation starts and stops beacuse it never leave the first screen with 100% to fulfil. Please advise me what i need to do!

**Comment by blak3r** [comment]
It's probably a permission issue.  Make sure you have all your permissions
set properly as per sugar's guidelines.
