### ISSUE TITLE
Step 1.. 

### ISSUE THREAD

**Issue by dogatemycomputer** [blak3r/yaai#197]
I am positive this is going to be flagged as a dumb question but I have zero experience with SugarCRM (or any CRM package at all).  I'm trying to get Asterisk to integrate with SugarCRM for a single user (small business).   Asterisk and SugarCRM installations were both easy and I am comfortable with AMI, Apache, MySQL and PHP.     

Here is where my confusion starts:

Step 1:
Installation is done using the "Module Loader" from within SugarCRMs Admin section.

I have read through all the other manuals and forums.   Just about everything else makes perfect sense to me.  I can find the "Module Loader" in SugarCRM.   It prompts me for a file.. but I have no idea what file to select.   

Thank you for any responses.

**Comment by blak3r** [comment]
Grab the zip file off sugar forge. 

Blake Robertson
Callinize
blake@callinize.com

**Comment by dogatemycomputer** [comment]
I downloaded the zip from Github.  Let me try the one from SugarForge.   Thanks!

**Comment by blak3r** [comment]
Either in theory would work. But go Sugarforge to be sure. 

Blake Robertson
Callinize
blake@callinize.com

**Comment by dogatemycomputer** [comment]
For the next guy...
- http://<your sugarcrm installation ip address>/sugarcrm
- login as admin
- Click ADMIN on top right
- click "Module Loader"
- Download this file (or latest alternative):  http://www.sugarforge.org/frs/download.php/10997/callinize-community-3.6.9.zip
- Select the downloaded file
- Click INSTALL 
- Follow the prompts

Thanks for the help Blake!

**Comment by blak3r** [comment]
No problem. If you want an easier install. Checkout www.callinize.com

Blake Robertson
Callinize
blake@callinize.com

**Comment by dogatemycomputer** [comment]
We're a "not-for-profit" ITSP (meaning we aren't in the business of ripping off our customers).  We're trying to get a basic package for smaller customers working so we can showcase your product then move customers onto your platform as they grow (rather than handling the larger customers in-house).   The initial demo product for new customers will be 100% free (we're going to eat the entire cost including the monthly server costs).   As customers outgrow the basic product or want more functionality (like Ring Group support) we'll have pre-written documentation explaining how they can move over to your hosted solution.   We don't really want to be in the CRM business but we are tired of loosing business to larger vendors.  Your free edition will help us get customers started on your platform.  We're happy to move bigger customers over to your platform once they understand the value of paying per-seat every month for a quality solution.

**Comment by blak3r** [comment]
If you're hosting both side of it, then I might be interested.
Lets talk offline.  blake [at] callinize.com

The new product is such a better first impression.
ᐧ

On Tue, Jul 8, 2014 at 7:22 PM, dogatemycomputer notifications@github.com
wrote:

> We're a "not-for-profit" ITSP (meaning we aren't in the business of
> ripping off our customers). We're trying to get a basic package for smaller
> customers working so we can showcase your product then move customers onto
> your platform as they grow (rather than handling the larger customers
> in-house). The initial demo product for new customers will be 100% free
> (we're going to eat the entire cost including the monthly server costs). As
> customers outgrow the basic product or want more functionality (like Ring
> Group support) we'll have pre-written documentation explaining how they can
> move over to your hosted solution. We don't really want to be in the CRM
> business but we are tired of loosing business to larger vendors who offer
> it so as long as you have a free solution that we can work with initially
> then we're happy to move the bigger customers to you once they've gotten
> their feet off the ground.
> 
> —
> Reply to this email directly or view it on GitHub
> http://r.clb.pt/r/e71f460af0d6327ce20a02ee2150cfea?d=https%3A%2F%2Fgithub.com%2Fblak3r%2Fyaai%2Fissues%2F197%23issuecomment-48412073
> .

## 

Blake Robertson
blake@callinize.com
Callinize

**Comment by Nkunzis** [comment]
Hi Blake
I followed above instructions but still have issue with uploading the Zip, tried yaai-master.zip from your account here, tried SugerCE-add-ons.master.zip from "sugarcrm" account. Here is the message i got after upload:

"ZIP Error(0): Status(9): Arhive(upload://SugarCE-Add-ons-master.zip): Directory(/tmp/kKh3jF)"

I see no error in it. 

Thank you for ur help

**Comment by Nkunzis** [comment]
Found the solution....
I should share it here, it may help someone else:
Then downloaded zip file, has  sub folder with the same name once it s uncompressed. Module Loader fails to find the manifest file in the first layer of the uploaded zip file

Structure after zip file:
-Yaai-master.zip
  --Yaai-master
     --manifest.php
     --Other files and folders

The correct Structure is:
--Yaa-master.zip
   --Manifest.php
   --Other files and folders
