### ISSUE TITLE
Can't see the "ASTERISK Configuration:" screen

### ISSUE THREAD

**Issue by lucasumberto** [blak3r/yaai#202]
It appears all white when i press it on admin menu, and i have this error on apache:

 PHP Warning:  require_once(include/Sugar_Smarty.php): failed to open stream: No such file or directory in /var/www/sugarcrm/custom/modules/Configurator/asterisk_configurator.php on line 89, referer: http://xxx.xx.xx.xxx/sugarcrm/index.php?module=Administration&action=index&bwcFrame=1

 PHP Fatal error:  require_once(): Failed opening required 'include/Sugar_Smarty.php' (include_path='/var/www/sugarcrm:/var/www/sugarcrm/vendor:.:/usr/share/php:/usr/share/pear') in /var/www/sugarcrm/custom/modules/Configurator/asterisk_configurator.php on line 89, referer: http://xxx.xx.xx.xxx/sugarcrm/index.php?module=Administration&action=index&bwcFrame=1

any clues?

**Comment by blak3r** [comment]
what version of sugar?  doesn't look like Sugar Smarty exists...

On Tue, Dec 2, 2014 at 2:42 PM, lucasumberto notifications@github.com
wrote:

> It appears all white when i press it on admin menu, and i have this error
> on apache:
> 
> PHP Warning: require_once(include/Sugar_Smarty.php): failed to open
> stream: No such file or directory in
> /var/www/sugarcrm/custom/modules/Configurator/asterisk_configurator.php on
> line 89, referer:
> http://xxx.xx.xx.xxx/sugarcrm/index.php?module=Administration&action=index&bwcFrame=1
> 
> PHP Fatal error: require_once(): Failed opening required
> 'include/Sugar_Smarty.php'
> (include_path='/var/www/sugarcrm:/var/www/sugarcrm/vendor:.:/usr/share/php:/usr/share/pear')
> in /var/www/sugarcrm/custom/modules/Configurator/asterisk_configurator.php
> on line 89, referer:
> http://xxx.xx.xx.xxx/sugarcrm/index.php?module=Administration&action=index&bwcFrame=1
> 
> any clues?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blak3r/yaai/issues/202.

## 

Blake Robertson
Founder, Callinize
blake@callinize.com
@callinize (tw)

**Comment by lucasumberto** [comment]
I'm trying to implement it on SugarCRM Professional, Version 7.2.1 (Build 1096).
The path was wrong! 
I found it on include/SugarSmarty/Sugar_Smarty.php and worked! 

thanks for reply! :)
