### ISSUE TITLE
AsteriskJS on SugarCrm 7

### ISSUE THREAD

**Issue by lucasumberto** [blak3r/yaai#206]
Anyone has some tips on how to make the AsteriskJS.php working on the new layout of sugarcrm?

Im using the v7.2.1 professional, it seems that i don't need to change it (or anything in the logical hook), just customize the phone fields to receive the .phone class and the css add the click to dial button, but it ain't worked for me, i'm doing something wrong or there are something else i didn't noticed...

thanks

**Comment by lucasumberto** [comment]
My new guess is the $_REQUEST and the $GLOBALS arrays don't work the same way that the version 6.
But i cant see what these arrays have inside when they are called by the AsteriskJS.php

**Comment by blak3r** [comment]
Yeah. I have no experience with sugar 7 sorry.

On Friday, January 16, 2015, lucasumberto notifications@github.com wrote:

> My new guess is the $_REQUEST and the $GLOBALS arrays don't work the same
> way that the version 6.
> But i cant see what these arrays have inside when they are called by the
> AsteriskJS.php
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blak3r/yaai/issues/206#issuecomment-70297454.

## 

Blake Robertson
Founder, Callinize
blake@callinize.com
@callinize (tw)
