### ISSUE TITLE
Fixing SuiteCRM 7.2 popup issue

### ISSUE THREAD

**Issue by ravijey** [blak3r/yaai#218]
First of all thanks to the Calinize team for the fantastic work.
I had issues with SuiteCRM 7.2 not generating the popup for the incoming call.
Found out, the handlebar-runtime is a older version in the repo. 
I downloaded the new handlebar (version 4.x) and then compiled the call-template.html with the new version and everything started working.

Thanks

**Comment by lomelisan** [comment]
Hi @ravijey, thanks for your solution!, how did you accomplish the handlebars 4.x v compile? I try in call-template.html

`<script id="entry-template" type="text/x-handlebars-template"> </script>`

or/and this in callpopup.js

`var source   = $("#entry-template").html();
var template = Handlebars.compile(source);`

but I sill get errors and no popup working
