### ISSUE TITLE
Allow each user to have multiple extensions

### ISSUE THREAD

**Issue by blak3r** [blak3r/yaai#22]
Allow a user to have more then one extension associated.  For example, say a user has a softphone and a deskphone and we'd like calls to be associated with a particular user account regardless of which he/she makes the call on.

I'm thinking maybe allowing a comma separated list of extensions the user could specify in their extension list.

Then, inside asteriskLogger / callListener modifying the WHERE clause code to check a list of extensions by ORing all of them together.

**Comment by anthonyscolaro** [comment]
I use Bria to take and places calls on a couple different extensions.  I would love to see this feature happen.

**Comment by blak3r** [comment]
Yeah I tend to use a soft phone more and more myself. 

~blake

**Comment by edokid** [comment]
Is there any hack or modification we can do to make this work?  I'm in the same boat, I own 2 companies and we use the same Sugar and Asterisk system for both.  So I have two extensions one for each company.  Outbound diailing I realize would be harder but just for inbound even it would be nice if it could monitor inbound calls on 2 extensions and not just the one.

**Comment by blak3r** [comment]
Not at the moment.

**Comment by randomf** [comment]
Hi, I'm sending working patch for this issue. The solution works as proposed by Blake - in the extensions column put comma separated extension numbers without spaces. Examples:

"123" - single extension per account, same functionality as before
"123,124" - two extensions per one account, when using click to dial extension 123 will be used
"123,124,125,127,128" - five different extensions extensions associated to the account

Please test it thoroughly before use, I did it just briefly with two extensions and couple inbound / outbound calls. I don't use click to dial on my setup due to custom contexts so please review that bit. 

I haven't mastered GIT yet so I'm not yet maintaining my own fork of the project and submitting the patch this way. 

``` php
diff --git a/SugarModules/modules/Asterisk/asteriskLogger.php b/SugarModules/modules/Asterisk/asteriskLogger.php
index c489fe8..2889e7f 100644
--- a/SugarModules/modules/Asterisk/asteriskLogger.php
+++ b/SugarModules/modules/Asterisk/asteriskLogger.php 
@@ -1597,7 +1600,9 @@
 {
     logLine("### +++ findUserByAsteriskExtension($aExtension)\n");

-   $qry = "select id from users join users_cstm on users.id = users_cstm.id_c where users_cstm.asterisk_ext_c=$aExtension and status='Active'";
+   $qry = "select id from users join users_cstm on users.id = users_cstm.id_c where ".
+          "(users_cstm.asterisk_ext_c='$aExtension' or users_cstm.asterisk_ext_c LIKE '$aExtension,%' ".
+          "OR users_cstm.asterisk_ext_c LIKE '%,$aExtension,%' OR users_cstm.asterisk_ext_c LIKE '%,$aExtension') and status='Active'";
    $result = mysql_checked_query($qry);
    if( $result ) {
        $row = mysql_fetch_array($result);
diff --git a/SugarModules/modules/Asterisk/include/callCreate.php b/SugarModules/modules/Asterisk/include/callCreate.php
index c96525c..785d609 100644
--- a/SugarModules/modules/Asterisk/include/callCreate.php
+++ b/SugarModules/modules/Asterisk/include/callCreate.php
@@ -70,7 +70,9 @@
 //$cUser->retrieve($_SESSION['authenticated_user_id']);
 //$extension   = $cUser->asterisk_ext_c;

-$extension = $current_user->asterisk_ext_c;
+// Use first extension in the list when multiple extensions linked to the account.
+$extensionsArray = explode(',', $current_user->asterisk_ext_c);
+$extension = $extensionsArray[0];

 //printr($current_user);
 //print $extension . "<BR><BR>";
diff --git a/SugarModules/modules/Asterisk/include/callListener.php b/SugarModules/modules/Asterisk/include/callListener.php
index 641c689..2909ea9 100644
--- a/SugarModules/modules/Asterisk/include/callListener.php
+++ b/SugarModules/modules/Asterisk/include/callListener.php
@@ -83,7 +84,19 @@

 // NeedID is the default call state for outbound calls, an entry in asterisk_log is created before a call record is created.  See GITHUB issue #
 $lastHour = date('Y-m-d H:i:s',time() - 1*60*60);
-$query = " SELECT * FROM asterisk_log WHERE \"$lastHour\" < timestampCall AND (uistate IS NULL OR uistate != \"Closed\") AND (callstate != 'NeedID') AND (channel LIKE 'SIP/{$current_user->asterisk_ext_c}%' OR channel LIKE 'Local%{$current_user->asterisk_ext_c}%')";
+$availableExtensionsArray = explode(',', $current_user->asterisk_ext_c);
+$query = " SELECT * FROM asterisk_log WHERE \"$lastHour\" < timestampCall AND (uistate IS NULL OR uistate != \"Closed\") AND (callstate != 'NeedID') AND (";
+if (count($availableExtensionsArray) == 1) {
+   $query .="channel LIKE 'SIP/{$current_user->asterisk_ext_c}%' OR channel LIKE 'Local%{$current_user->asterisk_ext_c}%'";
+}
+else {
+   $queryExtensionsArray = array();
+   foreach ($availableExtensionsArray as $singleExtension) {
+       array_push($queryExtensionsArray, "channel LIKE 'SIP/{$singleExtension}%' OR channel LIKE 'Local%{$singleExtension}%'");
+   }
+   $query .= implode(' OR ', $queryExtensionsArray);
+}
+$query .=")";

 $resultSet = $current_user->db->query($query, false);
 if($current_user->db->checkError()){
```

**Comment by blak3r** [comment]
Thanks Radek.

For future reference, you can make simple patch contributions by editing the files in browser.
https://github.com/blak3r/yaai/wiki/HowTo-Make-a-Simple-Code-Contribution

Since you had to modify like 3 files, this approach isn't really applicable.  But, might be useful for a future patch.

**Comment by blak3r** [comment]
This query is pretty clever... as it doesn't require a REGEX... at first glance I thought that it was going to have issues if one user had extension 100 and another user is extension 7100.  But, it doesn't.

```
+   $qry = "select id from users join users_cstm on users.id = users_cstm.id_c where ".
+          "(users_cstm.asterisk_ext_c='$aExtension' or users_cstm.asterisk_ext_c LIKE '$aExtension,%' ".
+          "OR users_cstm.asterisk_ext_c LIKE '%,$aExtension,%' OR users_cstm.asterisk_ext_c LIKE '%,$aExtension') and status='Active'";
```

I was also going to recommend you change your explode lines to preg_split as this allows for work if user puts spaces as well.
+$extensionsArray = preg_split('\s_,\s_', $current_user->asterisk_ext_c);
But, now I see why you didn't... We should probably implement something that strips spaces when user submits a value with spaces in it.  Not really sure how to add validation to studio fields though.  Would probably have to create a custom logic hook... or do something hacky like iterate through complete user list whenever asteriskLogger starts up and strip spaces then... 

I suppose alternatively we could use REGEX in sql statement.  Probably some really clever way to get it down to a single condition which would allow spaces to be in there....or use 4 conditions like you have with a **space**? after commas.
