### ISSUE TITLE
Error while loading! error in Calendar.

### ISSUE THREAD

**Issue by shyrikoff** [blak3r/yaai#23]
I had an error while loading! during quick edit events in calendar. Only if I'm regular user (without marks in check box "magic button" and "pop up notification" )
The problem was in the file AsteriskJS.php 
It was necessary to add one more condition

if( $_REQUEST['sugar_body_only']!=true && $_REQUEST['action']!='modulelistmenu' && $_REQUEST['action']!='Popup' && empty($_REQUEST['to_pdf']) && ( !empty($_REQUEST['module']) && $_REQUEST['module']!='ModuleBuilder') && empty($_REQUEST['to_csv']))

After  $_REQUEST['sugar_body_only']!=true the problem has gone away...... 

My be it would be useful for anybody!:)

**Comment by blak3r** [comment]
added your fix to the repo... didn't test it though.  So, taking your word for it :)
Thanks for the contribution!!!

**Comment by papaja** [comment]
This fix kind of solved issue for me only half way. Namely, before applying this fix, I couldn't open anything in calendar. Now I can open calls and meetings, but when I click on small "i" icon on any action (call, meeting, task) in firebug I get: "$(".ui-dialog").find(".open").dialog is not a function
https://myIP/SugarCRM/cache/include/javascript/sugar_grp1.js?v=GIQ7LQvEptY70q7HnfldtA
Line 444"

**Comment by blak3r** [comment]
What sugar version are you running?

Sounds to me like sugar uses jQuery for the calendar.  In AsteriskJS.php we load a copy of jQuery as well.  That's probably causing some issues with conflicting versions. 

I wrote a diatribe up about how to properly detect if jQuery is already loaded on the Project TODO page. 

For now try commenting out the line that loads jQuery and see if it works on the calendar afterwards. (it wouldn't work on any other page)

~blake

**Comment by papaja** [comment]
Commenting jQuery out worked. I'm using 6.5 SugarCRM.
