### ISSUE TITLE
Feature Request: Implement queues support

### ISSUE THREAD

**Issue by Guard1an** [blak3r/yaai#24]
Most of the PBX based on asterisk unilize queues.

The inbond call forwarded to the extensions by the queue is treated as an Internal becuase its channel matches the Internal expression (asteriskLogger.php: line 340).

It would be great to implement queues support.

The module configuration option can be added where the comma separated allowed queue numbers are listed.

The following workaround adds queue support by overriding the intenal channel by the one from Queue Join Event (allowed queues are hardcoded):

``` php
 SugarModules/modules/Asterisk/asteriskLogger.php | 43 ++++++++++++++++++------
 1 file changed, 00 insertions(+), 00 deletions(-)

diff --git a/SugarModules/modules/Asterisk/asteriskLogger.php b/SugarModules/modules/Asterisk/asteriskLogger.php
index 3f90a1a..7580aea 100644
--- a/SugarModules/modules/Asterisk/asteriskLogger.php
+++ b/SugarModules/modules/Asterisk/asteriskLogger.php
@@ -43,6 +43,9 @@ $mysql_loq_queries = 0;
 $mysql_log_results = 0;
 $verbose_log = 0;

+$allowedQueueIds = array(111);
+$channel = null;
+
 //
 // Say hello, setup include path(s)
 //
@@ -278,6 +281,11 @@ while (true) {
                dumpEvent($e); // prints to screen


+                if ($e['Event'] == 'Join' 
+                    && !empty($e['Queue']) 
+                    && in_array($e['Queue'], $allowedQueueIds)){
+                    $channel = $e['Channel'];
+                }
                //
                // Call Event
                //
@@ -334,6 +342,13 @@ while (true) {

                    $rgDetectRegex = "/^Local\/RG/i"; // TODO make this a configuration option
                    $rgCellRingRegex = "/^Local\/\d{7,10}/i";// TODO make this a configuration option.... This detects in a RG when an outside line is called (usually for a cellphone)... for some reason the cell shows up as the Channel (aka the source)... We detect this by finding a number thats at least 7-10 characters long..
+
+                    /* Workaround to support allowed queues */
+                    if (!empty($e['ConnectedLineNum'])
+                        && in_array($e['ConnectedLineNum'], $allowedQueueIds)
+                        && $channel){
+                        $e['Channel'] = $channel;
+                    }

                    // Check if both ends of the call are internal (then delete created (** Automatic record **) record)
                    // 2nd condition looks for Local/RG-52-4102152497
```

**Comment by blak3r** [comment]
Looks great. We definitely need queue support! I'm on vacation so I'll take a closer look when I get back in about a week. 

~blake

**Comment by blak3r** [comment]
Still really swamped. :/

**Comment by blak3r** [comment]
Hey @Guard1an, started adding Queue Support today... Adding it along with a feature where i'll start logging the inbound extension the user dialed from the IVR.

I don't have the "ConnectedLineNum" property in my Dial Event.

I'm using asterisk 1.6 so maybe that was added in 1.8.  Could you give me a complete log where you call your trunk and then press extension 1 or 2.  I'm curious if there are additional events which will help determine that as well.

**Comment by pavluhar** [comment]
Hi @blak3r! Do you have any progress with queues support integration? :)

**Comment by blak3r** [comment]
Not really. What version of asterisk are you running?

Asterisk 1.8 added some new stuff to the events which make queue support a lot easier to implement so I was thinking if I ever do get time to implement them... I might make that feature dependent on Asterisk 1.8. 

My company doesn't use queues support so a donation to the project would push things along quicker. 

How many users do you have?

~blake

**Comment by leonjvr** [comment]
Hi, we spoke about this also about 3 weeks back. I would like to know, did you get around implementing this?

**Comment by askhogan** [comment]
This has been implemented in the paid version of yaai, callinize.com
