### ISSUE TITLE
Custom Fields weren't created by installer properly

### ISSUE THREAD

**Issue by tavoip** [blak3r/yaai#28]
Hi everyone!

I don't speak a lot of english, but i´m going try to explain me.

I work on a enterprise where we have SugarCRM Enterprise Edition v6.4.3 and Elastix v2.2 running on separate servers. We would like to have Integrated SugarCRM and Elastix through Yaai.

Actually we have a problem. I followed the guide of installation step by step, but now i´m confused. I have Centos 5.8, PHP 5.3.3 and MySQL 5.5.23 installed and running on my SugarCRM Server.

I have installed Yaai through the Module Loader on Sugar. I see the Asterisk Module Configuration. In this module i have my IP Address, Username, Password and Port configurated. When i run the asteriskLogger.php the connection was made, i saw the connection on my Elastix Server by the port 5038, i saw the events on my Sugar Server when i make a call from PSTN to my Elastix Server. 

The problem comes when i try to configure my Elastix extension, Call notification and Magic Dial Buttons on my User Profile never save the changes. 

I try to validate if the info was saved on the tables of mysql, but i don´t have idea where can be.
## When i try to run a quick repair and rebuild my SugarCRM, i have a message where said: 

/_Checking Custom Fields for module : Users */
/_MISSING IN DATABASE - asterisk_ext_c -  ROW_/
ALTER TABLE users_cstm add COLUMN asterisk_ext_c varchar  NULL ;
/_Checking Custom Fields for module : Calls _/
/_MISSING IN DATABASE - asterisk_caller_id_c -  ROW*/
## ALTER TABLE calls_cstm add COLUMN asterisk_caller_id_c varchar  NULL ;

But never rebuild.

I see the sugarcrm.log and i have the next messages:

---

Wed Jun 27 10:40:32 2012 [8737][1][FATAL]  Query Failed: INSERT INTO calls_cstm (id_c ,asterisk_caller_id_c ) VALUES ('e51d2a97-5154-8412-dfba-4feb2906f702' ,'' ): MySQL error 1054: Unknown column 'asterisk_caller_id_c' in 'field list'
Wed Jun 27 10:46:17 2012 [8737][1][FATAL]  Query Failed: INSERT INTO calls_cstm (id_c ,asterisk_caller_id_c ) VALUES ('e51d2a97-5154-8412-dfba-4feb2906f702' ,'528187486000' ): MySQL error 1054: Unknown column 'asterisk_caller_id_c' in 'field list'
Wed Jun 27 11:03:13 2012 [8736][1][FATAL] Executing repair query:  Query Failed: ALTER TABLE users_cstm add COLUMN asterisk_ext_c varchar  NULL: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1
## Wed Jun 27 11:21:15 2012 [8741][1][FATAL] Executing repair query:  Query Failed: ALTER TABLE users_cstm add COLUMN asterisk_ext_c varchar  NULL: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1

What am i doing wrong? Can you help me?

Regards 
Gustavo Garcia

**Comment by blak3r** [comment]
I have no idea why when you installed yaai those custom fields didn't get created properly.

I'm also don't know why when you repair sugar that doesn't resolve your issue. 

I'd recommend filing a support ticket with sugarcrm to have them figure out why the custom fields aren't getting created in your database.  Until that's working properly it's a sugarcrm problem and not a yaai problem.

**Comment by blak3r** [comment]
@tavoip Did you ever get this issue resolved?  I'm closing the issue for now.  Please post back if you were able to come up with a solution.

**Comment by tavoip** [comment]
Hi Blake,

I get this issue resolved. The problem was on the length of the varchar. 

This is an issue on SugarCRM than will be resolved on the version 6.1. 

Exist a couple of alternatives that resolved the issue in old versions, one of them is running the query adding the length of the varchar, and the other one is replace this line if(preg_match("((?'type'\w+)\s_(?'arg'((?'len'\w+)\s_(,\s_(?'scale'\d+))_))_)", $type, $matches)) by this line  if(preg_match("#(?P<type>\w+)\s_(?P<arg>((?P<len>\w+)\s_(,\s_(?P<scale>\d+))_))_#", $type, $matches)) on the file /include/database/DBManager.php

I hope this can be useful 

Kind Regards
