### ISSUE TITLE
Use it without Asterisk 

### ISSUE THREAD

**Issue by Exiane** [blak3r/yaai#33]
Hello, is it possible to use it without Asterisk? Our phones are directly connected to a  sip provider?

**Comment by blak3r** [comment]
No.  Needs some type of server like Asterisk to report the events back in
to sugar.  One of the contributors to the project got it working with
twilio by rewriting asteriskLogger.php

On Sun, Jul 8, 2012 at 4:12 AM, Exiane <
reply@reply.github.com

**Comment by Exiane** [comment]
My provider has a clik to Call Api:
http://www.ovh.com/fr/soapi/fr/?method=telephonyClick2CallDo
Do you think I could use it with your module.

2012/7/8 Blake Robertson <
reply@reply.github.com

> No.  Needs some type of server like Asterisk to report the events back in
> to sugar.  One of the contributors to the project got it working with
> twilio by rewriting asteriskLogger.php
> 
> On Sun, Jul 8, 2012 at 4:12 AM, Exiane <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Hello, is it possible to use it without Asterisk? Our phones are directly
> > connected to a  sip provider?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/blak3r/yaai/issues/33
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blak3r/yaai/issues/33#issuecomment-6833172

## 

Pierre Saulnier
Directeur associé,
Facenet

cell: +33 (0)6.63.82.85.29
fixe: +33 (0)9.61.26.36.09
skype: pierre_saulnier

3 pl E. F Choiseul,
78180 Montigny le Bx, France

3 rue Kenitra,
Tunis, Tunisie
http://www.facenetservice.com

**Comment by blak3r** [comment]
If you're a developer and are willing to spend 40-60 hours then... maybe.

On Sun, Jul 8, 2012 at 5:40 PM, Exiane <
reply@reply.github.com
