### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by andrewpb** [blak3r/yaai#34]
Hi,

Upon clicking the install button after uploading the script to my SugarCRM (CE) module loader, I am greeted with a licence agreement window. Once the licence has been accepted I am issued with the following line on a blank page (within the Sugar template).

Including: /var/www/html/crm/cache/upload/upgrades/temp/KNpFtR/scripts/pre_install.php 

I have tried to alter the permission on the files and I'm still given the same error.

CentOS 5.8 Final
SugarCRM Version 6.2.6 (Build 6756)
PHP 5.2.17
Apache 2.2.3
MySQL 5.0.95

Cheers,
Andrew

**Comment by blak3r** [comment]
@andrewpb I have no idea :/ Try running the pre_install.php script manually and see if you get errors.  I develop with a PHP 5.3.6 and a MySQL 5.5 instance.

**Comment by andrewpb** [comment]
Hi Blak3r,

I've managed to resolve the problem by upgrading MySQL to 5.5 and PHP to 5.3. Although now I have some more specific questions. I've configured my settings within Sugar and setting calling buttons and they're all displaying OK. Although how do I start the asteriskLogger? I don't have an Asterisk folder in my root SugarCRM directory... So I can't start it via command line because I don't know where the file is. I tried started the script in the "misc" directory although a plethora of errors showed up.

Cheers,
Andrew

**Comment by andrewpb** [comment]
I've managed to locate the right logger file. When running it I receive this:

[root@vmx9605 crm]# php /var/www/html/crm/custom/modules/Asterisk/asteriskLogger.php

*******\* Asterisk Logger Starting **************

# Sugar root set to [/var/www/html/crm/custom/modules/Asterisk/../../../]

PHP Notice:  Undefined index: asterisk_log_file in /var/www/html/crm/custom/modules/Asterisk/asteriskLogger.php on line 121
Logging to:

# Callout prefix is [1]

# Callin prefix is [+1]

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i

# (Config processed)

Selecting DB Name: sugarcrm5
! Trying SOAP login endpoint=[http://XXXXXXXXXXXXXXXXXXXXXX/crm/soap.php] user=[admin] password=[]
PHP Warning:  Attempt to modify property of non-object in /var/www/html/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/html/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/html/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/html/crm/include/nusoap/nusoap.php on line 6160
! Successful SOAP login id=-1 user=admin GUID=-1

# Successfully opened socket connection to 127.0.0.1:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Antarctica/Macquarie' for 'EST/10.0/no DST' instead in /var/www/html/crm/custom/modules/Asterisk/asteriskLogger.php on line 978
[2012-07-10 23:40:02]
! --- Event -----------------------------------------------------------
!                Event -->
! ---------------------------------------------------------------------

Although when I click the magic dial buttons, nothing happens? Not even an error in the event log.

**Comment by andrewpb** [comment]
Sorry to keep adding updates. I've successfully got the logger to work by changing the dial channel back to the default SIP/### and creating a new outbound route to drop the prefixed 1 on the Sugar calls. Now the only thing I need to get working is the pop up windows. They don't pop up when the call connects or anything. Guess I'll have to keep playing.

Cheers,
Andrew

**Comment by blak3r** [comment]
See the user manual. There is troubleshooting which explains each of the dependencies and how to test for each. 

~blake
