### ISSUE TITLE
Event loop? Sugar 6.5

### ISSUE THREAD

**Issue by ghost** [blak3r/yaai#35]
Hi. New install on 6.5 CE with Elastix. Installed, configured, when running asterisklogger.php I get:

*******\* Asterisk Logger Starting **************
# Sugar root set to [/var/www/servistech/crm/custom/modules/Asterisk/../../../]

Logging to: /var/log/sugarasterisk
# Callout prefix is []
# Callin prefix is []

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i
# (Config processed)

Selecting DB Name: sugarcrm
! Trying SOAP login endpoint=[http://crm.servistech.co.uk/soap.php] user=[admin] password=[*****_HIDDEN**_*****]
PHP Warning:  Attempt to modify property of non-object in /var/www/servistech/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/servistech/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/servistech/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/servistech/crm/include/nusoap/nusoap.php on line 6160
! Successful SOAP login id=-1 user=admin GUID=-1
# Successfully opened socket connection to pbx.servistech.co.uk:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

[2012-07-10 21:00:57]
! --- Event -----------------------------------------------------------
!                Event -->
! ---------------------------------------------------------------------
[2012-07-10 21:00:57] # Event loop terminated, attempting to login again
# Successfully opened socket connection to pbx.servistech.co.uk:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

[2012-07-10 21:00:59]
! --- Event -----------------------------------------------------------
!                Event -->
! ---------------------------------------------------------------------
[2012-07-10 21:00:59] # Event loop terminated, attempting to login again
# Successfully opened socket connection to pbx.servistech.co.uk:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

**Comment by blak3r** [comment]
Never seen that before and I can't recall from memory what would cause that. Perhaps try ami connection with telnet and see if you get disconnected similarly.

User manual has a link to a site with more info on ami troubleshooting. 

~blake

**Comment by ghost** [comment]
For goodness' sake, there was a problem with the router I didn't even pick up on, fixed it now and that fixed the AMI rejection/loop issue.

However some more issues have arisen. Unless I'm going nuts, I've lost a dropdown menu somewhere in Sugar. There's nowhere to click to 'send email' or 'call' multiple contacts checked on a listing, or indeed on a single contact record. Is this deliberate?

Outbound click-to-calling works but doesn't create a activityrecord.

When I try to call in it doesn't seem to replace my callerID, do a popup or record the call in Sugar. This is what happens when I try to call in: http://pastebin.com/YvgP3rbT

Definitions: 01415529883 (UK test landline)
Sugar contact TEST McLean has 01415529883 as its office number.
My extension for testing is 1000.
1013403 is the username/account number on our sip trunk.
The 'ST01415529883' is caused by the inbound route and is deliberate, its a CID prefix to distinguish calls.

This is the menu I'm talking about: http://picpaste.com/Sharon_Casey___Leads___servistech_CRM_-_Google_Chrome_2012-07-11_01-36-37-LLVKeDBY.png

Sorry for all the posts.

I went back and reinstalled it, an the dropdown menu disappears as soon as i tick either/both of the 'call notification' or 'magic call buttons' options on my user. Firebug says:

Uncaught TypeError: Object #<Object> has no method 'sugarActionMenu' style.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.rGNJzo6TnG.js:3
(anonymous function) style.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.rGNJzo6TnG.js:3
E.extend.each
E.fn.E.each
SUGAR.append.allMenuBars style.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.rGNJzo6TnG.js:3
f.Callbacks.n sugar_grp1_jquery.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.6NOrcigVw4.js:1
f.Callbacks.o.fireWith sugar_grp1_jquery.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.6NOrcigVw4.js:1
e.extend.ready sugar_grp1_jquery.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.6NOrcigVw4.js:1
c.addEventListener.B sugar_grp1_jquery.js,qv=ajmengBjDeyWjD1oabXDVw.pagespeed.jm.6NOrcigVw4.js:1

**Comment by blak3r** [comment]
See the thread on "support for 6.5". Follow those instructions and thatll fix your problems. 

~blake

**Comment by ghost** [comment]
Reinstalled using that git branch, it now creates call records on both inbound and outbound, but the following is happening now. Thanks so much for all your help and this great addon! :)

-No popup window
-No link between call record and lead/account/contact/opportunity, just me and the soap user are linked to the record

Here's the trace http://pastebin.com/ncdYrH1Q

**Comment by blak3r** [comment]
Read the troubleshooting section of the user manual. There are like 4 things that have to work in harmony.  Probably soap isn't working. 

~blake

**Comment by blak3r** [comment]
@ewanmclean I'm closing this issue now.  Did you ever get it working?

**Comment by ghost** [comment]
Sorry I haven't had time to look at it in detail in reccent weeks, I've got it on my list though and can still update closed issues. Cheers
