### ISSUE TITLE
Edit Button doesn't drop drown

### ISSUE THREAD

**Issue by mic3009** [blak3r/yaai#36]
Hi,

I'm Using Sugar 6.5 and Yaii 2.03.
When i install Yaii the Edit Button is there but there is no drop down function when i click on it.
When i disable Yaii the Edit Button works fine.
The newest Version 2.3 doesn't work thats why is use the 2.03.
What can i do?

Thanks
Micha

**Comment by blak3r** [comment]
@mic3009 Not sure how I can help you.  I don't know why 2.3 wouldn't work for you.  I'm still on version 6.4 so I haven't messed around with Sugar 6.5 extensively... It's likely something related to JQuery.  There is a thread on Sugar 6.5 Support.  Please take a look in there and see if those recommendations fix your issue.
