### ISSUE TITLE
Trixbox or AsteriskNow

### ISSUE THREAD

**Issue by Exiane** [blak3r/yaai#37]
Which one do you recommand with Yaai?

**Comment by blak3r** [comment]
Well... I developed it with a Trixbox install.  But, Trixbox seems to be
old news now.  If I was starting from scratch I think it'd look at Elastix,
FreePBX, or AsteriskNow.  Trixbox CE isn't really being maintained anymore
(I think...).

I'm not aware of anyone that has used AsteriskNow so I don't know what your
issues will be.  YAAI interacts with Asterisk via AMI so it's pretty distro
agnostic.

On Thu, Jul 19, 2012 at 6:34 AM, Exiane <
reply@reply.github.com

**Comment by Exiane** [comment]
Are you aware of anyone that has used Elastix or FreePBX? If yes, what version do you recommand. I need to be sure it will work before to hire a freelance to install it.

**Comment by blak3r** [comment]
I'm going to be switching to a PIAF purple box in a bit.  I'd suggest something 1.8 based as I think when I implement queue support thatll require 1.8. 

Lots of people seem to use both. Search the issues section for either term. 

~blake

**Comment by Exiane** [comment]
Is it Asterisk 1.8 or PIAF 1.8? You do not recommand to go higher (2.x)? Do you any link for download?
Pierre

**Comment by blak3r** [comment]
Asterisk 1.8. 

I use lylix so I didn't install but it's available if you google it. I haven't developed against it yet though just letting you know that's what I'm personally going to be using. 

My addon works with asterisk directly through ami so any flavor should be fine. 

~blake

**Comment by Exiane** [comment]
I installed PIAF on Amazon EC2. Do you recommand to install Sugar + Yaai in the same PIAF centerOS vm or in a different vm (but in the same Amazon instance)?

**Comment by blak3r** [comment]
Yaai doesn't care. Your sugar performance might suffer. Generally a good idea to split them up. 

~blake
