### ISSUE TITLE
Call duration is not computed correctly

### ISSUE THREAD

**Issue by ghost** [blak3r/yaai#40]
The problems are:
1. The duration is counted from the moment the phone starts ringing, not from the moment the parties start to actually talk. That is not what most people want.
2. While ringing and talking, the duration indicator in the popup window shows insane values: it starts at 120 minutes and counts downwards. After hangup the correct duration shows up, but includes the ringing time (point 1).
3. After the call is hung up and saved, the Start Date in Calls screen shows a value two hours larger than the real one.

I have two simple extensions on Asterisk, 01234 and 11. Dial in/out prefixes are set empty, the Sugar Admin user has assigned the Asterisk Extension 11. There is only one Contact in the system, Franta Voves, with Office Phone set to 01234.

What I did:
1. I made a call 01234 -> 11, using a hardware phone.
2. The call popup showed, with 'Ringing' state and a duration of 120 minutes. It started counting downwards.
3. I picked up 11, the state changes, but duration still goes steadily downwards.
4. I hung up, the correct duration showed up.
5. I clicked  Save without filling in the subject. The call showed up in Calls, with the correct Contat but the start time 2 hours off.

First I thought it was a timezone issue, as +2 hours is exactly my UTC offset. But then I reset every timezone I could to UTC: on the Asterisk server, on the Sugar server, in the Sugar server php.ini, in the Sugar user properties, even on my desktop (to make sure it's not picking anything from the browser) and restarted everything (Asterisk, Apache, asteriskLogger, browser). No good, still 120 min. And the counting downwards is also weird, regardless of timezones.

Tested in version 2.4. The manager account has all/all permissions.

I will try to attach logs and screenshots documenting the issue.

**Comment by ghost** [comment]
A sequence of screenshots illustrating the duration problem: http://img9.imageshack.us/img9/2308/illustrationt.png. In total I spent 1 minute ringing and 1 minute talking; the final duration is show as 2 min instead of expected 1 min. What happens during the call is even wilder.

A screenshot illustrating the incorrect call start time in Calls: http://img692.imageshack.us/img692/2491/crop4hilitetimes.png

asteriskLogger output: https://gist.github.com/3169303

**Comment by blak3r** [comment]
I've seen this issue before.  Never was able to isolate it and it just went away.
Might be something in the troubleshooting section.
Are you using php 5.2 by any chance?

I agree the duration would probably be better going from Link to End.  I believe there is a reason for it being this way though.  Maybe it was just important for detecting initial call duration to determine whether or not it was a failure... 
Or maybe I was just feeling lazy and didn't want to handle the case separately if Link timestamp isn't set.

**Comment by ghost** [comment]
Using PHP 5.3. I think I have tracked down the issue. More in a few minutes.

**Comment by ghost** [comment]
It indeed is a timezone issue. More precisely, the problem is when there is a timezone difference between MySQL and PHP. Even more precisely, the root cause is a design issue in the (My)SQL DATETIME type and the NOW() function. It's explained e.g. at http://billauer.co.il/blog/2009/03/mysql-datetime-epoch-unix-time/. When asteriskLogger creates the record in `asterisk_log`, it uses the MySQL `NOW()` function, which stores the _local_ time (according to the MySQL server timezone) to the database. When callListener.php reads `asterisk_log`, it gets the time as a string, _in MySQL server timezone_. Then it calls the strtotime() function on that string, which interprets it as if it were in PHP's local timezone and converts it to a timestamp (which is timezone-agnostic by definition). If the MySQL and PHP timezones differ, the resulting timestamp is incorrect.

In my case, I had GMT+2 on the MySQL server and GMT in PHP (first by mistake, then for debug reasons).  When I created the call at 9:42 GMT, the `NOW()` function returned '11:42' according to the MySQL server timezone and that value was saved to the database. callListener then got the '11:42' from the SELECT query and converted it to a timestamp using its local timezone: GMT. Resulting in a timestamp representing the time 11:42 GMT, instead of the correct 9:42 GMT = 11:42 GMT+2. That timestamp was 2 hours in the future for the script, i.e. the computed duration of the call was negative (at the start it was -120 min, then it slowly climbed to -119, etc.). The sign was dropped somewhere during the formatting of the duration for its display in the UI. Therefore what I saw wasn't decreasing time but increasing negative time, just with the minus sign not visible.

I understand this is not a big problem, as most people have their MySQL server in the same timezone, probably even on the same machine as the webserver. But if not (e.g. when there is a dedicated mysql server machine), other problems could occur. Because `NOW()` uses not only the server _timezone_ but also the server _time_, which is then compared to the client time in PHP to compute the direction. So if the clocks of the MySQL and PHP server differed by e.g. 5 minutes (easy to happen without NTP), the call duration show will be off by 5 minutes (unpleasant, but better than 2 hours).

The correct solution would probably be to get rid of `NOW()`, compute the "current time" in PHP and the store it into MySQL, preferably in GMT format (so that timezone changes don't screw up the records). The most ideal thing would be to store the unix timestamp as an integer, but that would require a schema change (datetime -> integer) and I don't know how much that is feasible with Sugar modules (problems with upgrades, etc.). So as an alternative, storing the GMT string in the DATETIME column should work, too.

**Comment by ghost** [comment]
And as for the ringing time, I think that it would be correct to consider calls that haven't got a timestampLink yet to have a duration of zero. For those who have it, compare the current time against it. It should mean adding one `if` to the place(s) where duration is computed.

**Comment by ghost** [comment]
As for detecting failed calls: those never get a Link event. Therefore any call without a timestampLink is failed. You don't event have to apply any kind of "too short" heuristics.

**Comment by blak3r** [comment]
@kerio-fstedronsky Thanks for investigating this.  I definitely could see that causing issues.  
I think the time in the mysql is stored as GMT time.  Wouldn't make sense for it to be stored any other way.  For now i'll add a note in the troubleshooting section.  Did you fix it by just setting your php timezone?

Feel free to change the call duration behavior.  It's somewhere in asteriskLogger.  I agree with you.

**Comment by ghost** [comment]
Yes, I fixed it by setting the MySQL server and PHP server timezones the same.

It doesn't make sense but that's how it works. Well, not exactly. DATETIME stores the date/time not as a timestamp but as a string. Perhaps it's not internally stored as a string (that would be inefficient) but it works as if it were. Using SQL you store a string, e.g. '2012-07-24 12:40:25', and when you query it, you get the same string back, always, regardless of timezone. Which clearly shows that the DATETIME column is unsuitable for storing local time. But as the referenced article mentions, the real problem is not DATETIME but NOW(), which returns _local_ time (as a string). That string then gets stored into the column, which has no way of knowing whether it represents local or UTC time. That is up to the user to decide.

To illustrate:

```
[root@fstedronsky-esx-arch ~]# ln -sf /usr/share/zoneinfo/GMT /etc/localtime
[root@fstedronsky-esx-arch ~]# date
St čec 25 06:11:07 GMT 2012
[root@fstedronsky-esx-arch ~]# systemctl restart mysqld.service
[root@fstedronsky-esx-arch ~]# echo 'select NOW()' |mysql -u root SUGAR_DB_6_5_2_yaai24 
NOW()
2012-07-25 06:11:41
[root@fstedronsky-esx-arch ~]# echo 'select timestampCall from asterisk_log;' |mysql -u root SUGAR_DB_6_5_2_yaai24 
timestampCall
2012-07-24 12:40:25
2012-07-24 14:58:58
2012-07-24 12:59:49
[root@fstedronsky-esx-arch ~]# ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime
[root@fstedronsky-esx-arch ~]# date
St čec 25 08:12:33 CEST 2012
[root@fstedronsky-esx-arch ~]# systemctl restart mysqld.service
[root@fstedronsky-esx-arch ~]# echo 'select NOW()' |mysql -u root SUGAR_DB_6_5_2_yaai24 
NOW()
2012-07-25 08:13:28
[root@fstedronsky-esx-arch ~]# echo 'select timestampCall from asterisk_log;' |mysql -u root SUGAR_DB_6_5_2_yaai24 
timestampCall
2012-07-24 12:40:25
2012-07-24 14:58:58
2012-07-24 12:59:49
```

When changing timezone, the stored times stay the same, the NOW() value changes. You see why this is not what anyone wants. Therefore, the combination of DATETIME + NOW() to store timestamps is BAD.

A simple fix would be to use the UTC_TIMESTAMP() function instead of NOW() in order to store UTC time in the database. Then you would have to also interpret it as UTC in php, i.e. using [strptime](http://cz.php.net/manual/en/function.strptime.php) + [gmmktime](http://cz.php.net/manual/en/function.gmmktime.php) instead of [strtotime](http://cz.php.net/manual/en/function.strtotime.php). That would fix the timezone differences but not the time differences. To fix the time differences, you would have to generate the UTC time string in php (using [gmstrftime](http://cz.php.net/manual/en/function.gmstrftime.php)) and put it in the query instead of the UTC_TIMESTAMP() SQL call (which is handled on the server).

A better solution would be to drop DATETIMEs and store timestamps as an integer, that would rid you of having to format and parse date/time strings all over again. But it require a schema change, as noted earlier. I probably won't have time to fix this but if I do, I'd like to know whether such change would be doable/acceptable/worth the effort (esp. concerning upgrades from older versions).

**Comment by blak3r** [comment]
I'm not really against a scheme change.  Asterisk_log table isn't really needed.  The data for the most part thats really useful is in Calls.  There is no way to query any of it
from inside sugar.

It's probably fairly easy to make the pre-install script automatically create new columns,convert the dates over, then remove the old columns. 

I really appreciate the time you put into identifying this bug! I personally don't have time to make the changes though either :/ but I'm sure someone would appreciate it and it'd be great to have other developers know the codebase well. :D

**Comment by trustmaster** [comment]
I've also encountered this bug. Thanks for digging this, @kerio-fstedronsky.

The way I fixed it for now is quick and simple, I replaced all "NOW()" instances in queries with this:

``` php
FROM_UNIXTIME(".time().")
```

In future I agree that probably changing DATETIME to INT would be better. And probably date_default_timezone_set() call in asteriskLogger.php might be helpful for PHP 5.3+.

**Comment by trustmaster** [comment]
Update: as SugarCRM uses UTC timestamps by default, we need our timestamps to be UTC too. Thus, a more correct solution is this:

At the beginning of asteriskLogger.php set all PHP timestamps to UTC:

``` php
date_default_timezone_set('UTC');
```

and then replace all NOW() calls with UTC_TIMESTAMP() as suggested in previous comments.

**Comment by blak3r** [comment]
Can you create a pull request for this?

~blake

**Comment by trustmaster** [comment]
Sure I can but I'm quite puzzled by the plenty of branches available. Which one do I patch?

**Comment by blak3r** [comment]
Master. Those were all topic branches I probably shouldn't have made remote versions. 

~blake

**Comment by blak3r** [comment]
By the way, I get an hour to work on yaai. Trying to fix the configuration stuff right now. If you think of any other config options I should add now let me me know. 

~blake

**Comment by trustmaster** [comment]
Yes, please add 'asterisk_recordings'. I'm gonna commit a patch for listening and downloading call records soon. It is for a local folder where call records are stored.

**Comment by blak3r** [comment]
Just a boolean or do you need like a path for recordings etc

~blake

**Comment by trustmaster** [comment]
``` php
$asterisk_config['asterisk_recordings'] = '/var/spool/asterisk/monitor';
```

``` php
// Added from SugarAsterisk
$javascript->addFieldGeneric("asterisk_recordings", "varchar", $mod_strings['LBL_ASTERISK_RECORDINGS'], TRUE, "");
```

and the lang string:

``` php
$mod_strings['LBL_ASTERISK_RECORDINGS'] = 'Path to recorded calls folder';
```

**Comment by ghost** [comment]
@trustmaster The UTC_TIMESTAMP() solution is not exactly correct as it uses MySQL server time. It may than break because of a time difference, not a timezone difference. The correct way would be probably to set MySQL timezone to UTC (`SET time_zone='+00:00';`) and then use FROM_UNIXTIME. See http://stackoverflow.com/questions/5544038/how-can-i-convert-a-unix-timestamps-to-utc-date-in-mysql.

**Comment by trustmaster** [comment]
According to http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_utc-timestamp it does return UTC time regardless of the server timezone. It is NOW() which returns time in the server's timezone.

**Comment by ghost** [comment]
@trustmaster Of course. The timezone issue is fixed by `UTC_TIMESTAMP`. But I was not talking about timezone now, I was talking about the actual _time_. If the MySQL server is a different (virtual) machine, its clock can be e.g. 5 minutes off and then the call duration is incorrect by 5 minutes (quite a lot). It's not a big problem, just if you are looking for the _correct_ solution, I'm noting this is not it.

**Comment by trustmaster** [comment]
I don't think `(SET time_zone='+00:00';)` is the cure then. If there is a time shift between MySQL server and Asterisk machine (say 5 minutes, which is not a timezone difference), then you have to determine it somehow and adjust to all timestamps on PHP side.

**Comment by trustmaster** [comment]
Oh, and there can be time differences between all 4 servers if they are on different machines: Asterisk, asteriskLogger, MySQL and SugarCRM.

**Comment by ghost** [comment]
I'm suggesting the `SET time_zone` along with `FROM_UNIXTIME` and a  _client-provided timestamp_ (as suggested in [your earlier comment](https://github.com/blak3r/yaai/issues/40#issuecomment-8801062)). This removes the MySQL <-> PHP difference and very easily. The additional `SET time_zone` step is used just to ensure `FROM_UNIXTIME` returns the time in UTC (which is not strictly neccessary but it's definitely cleaner and prevents breakage upon timezone _changes_). The crucial point here is using a PHP-provided timestamp. Even though MySQL is often not on a different machine, this is much cleaner and more elegant than comparing timestamps created by PHP and MySQL.

Where Asterisk is doesn't matter, we are not using any timestamps generated by Ast AFAIK. As for asteriskLogger <-> Sugar, I don't know any fix for that.

**Comment by trustmaster** [comment]
Sounds good! Let's do it this way.

Another question: does everybody agree that we change the 15 second threshold to a timestampLink check to determine if the call is Held or Missed?

I've also noticed that @blak3r has commented this check for outbound calls:

``` php
// BR: 3/16/2012 I originally had this check to make sure call was longer then 5 seconds... I don't know why. Whey you have callStatus of Missed it creates a task which is undesirable.
                                // So i'm commenting it out.  If it's April and I still haven't deleted this comment it's safe to delete this code.
                                //if ($callDurationRaw > 02) {
                                    $callStatus = 'Held';
```

Can anybody confirm Sugar still creates a task if the outbound call is missed?

**Comment by blak3r** [comment]
It does create a task if it's missed. 

I actually created a new config option yesterday that we can let the user pick whether they want status to be "held" or "missed". 
So no worries there. I'll also add a config for the duration so it's also configurable. 

Thanks to both of you for your help in improving yaai!

~blake

**Comment by trustmaster** [comment]
I actually uncommented that code on my customer's site to see if it would create tasks or not and it didn't. Some SugarCRM option in effect maybe?

**Comment by blak3r** [comment]
I'll have to look at it closer.  I unfortunately seem to always be on my mobile when I have time to respond to github issues :/

~blake

**Comment by trustmaster** [comment]
No problem, this isn't urgent :)
