### ISSUE TITLE
Configured context ignored for transfers

### ISSUE THREAD

**Issue by ghost** [blak3r/yaai#41]
When I initiate a transfer to extension 14 from the YAAI popup window, this gets send to my Asterisk:

```
ACTION: Redirect
Channel: SIP/01234-00000024
Context: from-internal
Exten: 14
Priority: 1
```

Despite my having set the Asterisk context to `sip-locals` in the configuration manager (and verified that setting in config_override.php. No wonder: the from-internal value is hardcoded.

**Comment by ghost** [comment]
Sent a pull req with the trivial fix

**Comment by blak3r** [comment]
Fix Merged and added you as a contributor on main page.  Thanks for this you really made my morning!  You should put your email address in your github profile.
