### ISSUE TITLE
Translation of soap calls

### ISSUE THREAD

**Issue by miksir** [blak3r/yaai#44]
After finishing the call, asteriskLogger.php set "Held" status as `$mod_strings['CALL_STATUS_HELD']`. If this string was translated to other language, it's saved to _calls_ table as is (as translated string) . As a result - "Sugar" does not see that this call is "Held".

**Comment by blak3r** [comment]
Sounds like a bug.  Fix it if you know how. @trustmaster helped with the localization and as soon as I have time  I want to work on new things. :)

**Comment by miksir** [comment]
Yep, look like need to revert translation of status field. Because it's key, not text. And text for this keys translated well in Sugar.

**Comment by trustmaster** [comment]
Yeah, sorry guys, missed that. Should be pretty easy to fix.
