### ISSUE TITLE
Call popup notification logic error

### ISSUE THREAD

**Issue by miksir** [blak3r/yaai#45]
Subj alert. This is happens very often. Usually if you refresh page with popup. Only relog (logout+login) help to close popup.

**Comment by blak3r** [comment]
I noticed it happening a little more too. 
Were you using Internet explorer? 

There's a workaround to this in the open pull request but wanted to track down what would cause this in the first place. 

Something in the JavaScript of when the chat box is first created. 

~blake

**Comment by miksir** [comment]
Chrome v.20
I get alert popup after load AJAX page. So if I press link which use AJAX (contact, account etc) - after it popup can't be closed. If (even after this alert) I switch to page without AJAX (for example: Employers) - after it I can close popup without any alert.
May be AJAX load some JS again and overwrite some vars?
Tell me if you need more information.

**Comment by blak3r** [comment]
That's a great observation.  So if I understand you correctly

On an account detail view...
If I press create contact and the Ajax form loads... From there on out I will not be able to close popups until I go I
Like employees?

Give me the step by step recipe if you will.

**Comment by miksir** [comment]
Yes, or just open any other page - almost all pages loaded with ajax in default setup.
As quick fix i'm turned ajax off (in Sugar settings you can disable ajax for specific modules).

**Comment by blak3r** [comment]
You're using 6.5 right? Its not that bad on 6.4 

~blake

**Comment by miksir** [comment]
Yes, it's 6.5.1
Lot of ajax calls.

**Comment by blak3r** [comment]
Hmm. I thought version 6.4 is where all the major Ajax changes were made though so I'm surprised. But I guess the switch over to jQuery from YUI could have more of an impact then previously expected.  

I've been too busy with weddings and bachelor parties and weekends to look at this stuff.  :/ 
Like I said though, There wa a workaround posted as a pull request that will probably alleviate the issue so you can reenable ajax

**Comment by miksir** [comment]
Idk about 6.4, I just started to use Sugar. But in 6.5 almost all pages loaded with ajax (but it can be controlled in settings). If i'm right and it's ajax trouble - just need to skip all JS echo's if request if ajaxed.
I'll try to debug more at next week after rewrite of asteriskLogger.

**Comment by blak3r** [comment]
I thought I had already figured out all the things that had to be ignored in the AsteriskJS.php. 

If ya search for AsteriskJS in the issues, I explained the process of how to use chrome to find other things that may need to be ignored. 

~blake

**Comment by blak3r** [comment]
Ok.  I just committed some changes.  Please verify it now works for you with AJAX enabled then i'll post on sugarforge.

**Comment by miksir** [comment]
I tried HEAD, look like all work nice, error gone. Will make some more tests tomorrow.

**Comment by blak3r** [comment]
Thanks for the update 

~blake

**Comment by blak3r** [comment]
Marking this as closed... even though we haven't figured out the source of the issue.  The workaround is good enough for now.
