### ISSUE TITLE
Add OpenCNAM support [enhancement]

### ISSUE THREAD

**Issue by askhogan** [blak3r/yaai#5]
When there is no match between caller and sugarcrm records we only have the phone # to draw from.  This creates situations where marketers or customers who call in on a new phone # are unknown to the person answering.  http://www.opencnam.com/ is a service that provides callerid information and an easy to use API.

**Comment by rdegges** [comment]
Hey all, I'm one of the founders of OpenCNAM, and lead developer. If you guys want to add support, I'd be happy to provide some API keys for testing, or whatever I can do to help.

I don't really do PHP (more of a Python guy), but let me know.

**Comment by blak3r** [comment]
Hey rdegges,

That'd be great.  Looks pretty easy to do so.
Hell... it'll take longer to add the configuration option in our application then it will to implement that code.  Heh.

~blake

**Comment by blak3r** [comment]
Hogan, 

I don't know off hand what to use in sugar to make an http request without having to add extensions like curl or HttpRequest.  If you have a snippet for making a webrequest and getting body that'd be helpful.  It's timely with my refactoring of callListener to add it now.

**Comment by askhogan** [comment]
Sweet.  I implemented WhitePages API in my other phone app and kept
hitting their limitation (100 queries a day).  Very good bits of
information to see when you have a new caller coming through.

On Tue, May 1, 2012 at 9:29 PM, Blake Robertson
reply@reply.github.com
wrote:

**Comment by askhogan** [comment]
nope.  Ask eggers though he may know.  All my outside web requests in
sugar use jquery.  Maybe look at the facebook or twitter plugins and
copy them?

On Tue, May 1, 2012 at 9:37 PM, Blake Robertson
reply@reply.github.com
wrote:

**Comment by blak3r** [comment]
Just did a quick search for sugarcrm and rest client and found this article John wrote.  I'll add that in shortly.
http://www.ibm.com/developerworks/library/x-sugarcrmrest/index.html

**Comment by blak3r** [comment]
rdegges, 

Got rudimentary support working last night.  

It seems (at least in my browser) I have to make a call twice to get back results.  The first time my browser posts for a "NEW" phone number it returns "".  The second time it returns a result.  My guess would be it's only returning results which are already in your cache?

**Comment by rdegges** [comment]
@blak3r the way it works is that, for our free plan:
- If we don't' have the number in our cache, we return a 404 and asynchronously do a lookup. The next time you query us, we should have finished the lookup and have the number to return.

For our paid plan, we return realtime results. That's the main difference.

I can give you an API key so you can get realtime results if you'd like. Our paid service is still in beta, but it may help you while testing stuff out.

If you'd like a key, just send me an email (staff@opencnam.com) and I'll get you setup.

**Comment by blak3r** [comment]
A version which uses the "free api" is included with v2.3.0.9.  
Next release we'll add configuration options to use their paid API.
