### ISSUE TITLE
Event loop terminated

### ISSUE THREAD

**Issue by sollostech** [blak3r/yaai#50]
Trying out the latest version 2.4 with SugarCRM 6.5 connecting to Elastix 2.3 running Asterisk 1.8.13. Getting the following looping failure. 

*******\* Asterisk Logger Starting **************
# Sugar root set to [/Library/Server/Web/Data/Sites/Sollos/sales/custom/modules/Asterisk/../../../]

Logging to: /Library/Server/Web/Data/Sites/Sollos/sales/asterisk.log
# Callout prefix is [1]
# Callin prefix is [+1]

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i
# (Config processed)

Selecting DB Name: sollos_sugar
! Trying SOAP login endpoint=[http://sales.sollos.com/soap.php] user=[soapy] password=[1a1f41db41e227b8cbfecfdae954bd38]
! Successful SOAP login id=d118e7de6b433c6d0b090beb7e67dfb5 user=soapy GUID=42a0977a-ec43-0deb-d00f-5011dbde2ad5
# Successfully opened socket connection to 192.168.2.12:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

[2012-07-28 00:34:09]
! --- Event -----------------------------------------------------------
!                Event -->  
! ---------------------------------------------------------------------
[2012-07-28 00:34:09] # Event loop terminated, attempting to login again
# Successfully opened socket connection to 192.168.2.12:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

[2012-07-28 00:34:11]
! --- Event -----------------------------------------------------------
!                Event -->  
! ---------------------------------------------------------------------
[2012-07-28 00:34:11] # Event loop terminated, attempting to login again
# Successfully opened socket connection to 192.168.2.12:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

From the asterisk command line I can see it logged in for a second, but it doesn't have a name for the manager user. 

  Username         IP Address       Start       Elapsed     FileDes   HttpCnt   Read   Write
  admin            127.0.0.1        1342560713  865320      10        0         08191  08191
  admin            127.0.0.1        1342560713  865320      11        0         08191  08191
  admin            127.0.0.1        1342560713  865320      12        0         08191  08191
  humbug           127.0.0.1        1342560716  865317      28        0         01027  00000
  admin            127.0.0.1        1342560717  865316      29        0         08191  08191
  admin            127.0.0.1        1342560717  865316      30        0         08191  08191
  aastra-xml       127.0.0.1        1342560719  865314      31        0         04223  04223
  aastra-xml       127.0.0.1        1342560719  865314      32        0         04223  04223
                   192.168.2.10     0           1343426033  43        0         00000  00000

Elastix is on a Centos machine and SugarCRM is on a Mac server.

**Comment by blak3r** [comment]
I recommend following the steps on this page and testing using telnet to see if you can successfully issue commands via AMI. 

http://www.the-asterisk-book.com/unstable/asterisk-manager-api.html

**Comment by blak3r** [comment]
Randomly... I just encountered this.
I didn't have my username set properly for the Asterisk AMI user.  

The 

```
! AMI Login action returned with rc=Asterisk Call Manager/1.1
```

line is deceiving.  Note: I also just found that I have to enter my SOAP Password each time I go to save.  Does yours load the password each time or not?

**Comment by sollostech** [comment]
Correct, I do have to enter my password each time for SOAP. I'll check on the username for AMI.

**Comment by blak3r** [comment]
yep.  I have no idea what I did differently when I added the SOAP Password property... looks identical to the others but doesn't work the same.  The project uses this Configurator class which makes adding new properties the biggest chore in the world.

If ya got a minute, perhaps your eyes will spot the issue.  Here's the commit diff. 
https://github.com/blak3r/yaai/commit/fb842199d3d32fd7973b1b5d753890f27c726c5a

**Comment by sollostech** [comment]
I made a new AMI user and I think it is working now. I will test again, but I might have not had the right permissions for the user. I will try to find a time to debug, but today has been a massive one.

**Comment by blak3r** [comment]
cool. Thanks!

~blake

**Comment by blak3r** [comment]
I'm closing this issue out.  If you wouldn't mind sending me an email to blake.robertson at gmail i'm trying to gather a email list of users.
