### ISSUE TITLE
Click To Dial Doesn't popup

### ISSUE THREAD

**Issue by gvijay** [blak3r/yaai#52]
Hi,

The asterisk works fine with inbound and outbound calls but integration with sugarcrm doesn't work

Server info:
a) nginx
b) php-5.3.13
# manager.conf 

[eventsdaemon]
secret = pa55w0rd321
permit = 0.0.0.0/0.0.0.0
read = all
write = all

[root@ip-10-119-2-187 sugarcrm]# php ./custom/modules/Asterisk/asteriskLogger.php
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php.d/memcache.ini on line 24 in Unknown on line 0
PHP Warning:  Module 'apc' already loaded in Unknown on line 0

*******\* Asterisk Logger Starting **************
# Sugar root set to [/srv/wordpress/sugarcrm/custom/modules/Asterisk/../../../]

Logging to: /srv/wordpress/sugarcrm/asterisk.log
# Callout prefix is []
# Callin prefix is []

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i
# (Config processed)

Selecting DB Name: sugarcrm
! Trying SOAP login endpoint=[http://ec2-50-117-213-97.compute-1.amazonaws.com:8095/soap.php] user=[admin] password=[0192023a7bbd73250516f069df18b500]
PHP Warning:  Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160

Warning: Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160

Warning: Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160

Warning: Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160

Warning: Attempt to modify property of non-object in /srv/wordpress/sugarcrm/include/nusoap/nusoap.php on line 6160
! Successful SOAP login id=6pioak3120u2i0hounklced7n7 user=admin GUID=1
# Successfully opened socket connection to 127.0.0.1:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

[2012-08-02 09:35:14]
! --- Event -----------------------------------------------------------
!                Event -->
! ---------------------------------------------------------------------
[2012-08-02 09:36:14] Timeout or Error
# Php logs

[02-Aug-2012 13:38:48 UTC] PHP Warning:  fopen(./sugarcrm.log): failed to open stream: Permission denied in /srv/wordpress/sugarcrm/include/SugarLogger/SugarLogger.php on line 182
[02-Aug-2012 13:38:48 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /srv/wordpress/sugarcrm/include/SugarLogger/SugarLogger.php on line 195

Are we missing something.

**Comment by blak3r** [comment]
Haven't seen that fwrite warning error. 

It's unclear to me why works and what doesn't. Have you looked at the troubleshooting section in the manual?

~blake

**Comment by gvijay** [comment]
Thanks for the response.

Yes I did take a look at the troubleshooting manual. It does create a call 

# Attached logs from chrome 

Request URL:http://ec2-50-117-213-97.compute-1.amazonaws.com:8095/index.php?entryPoint=AsteriskCallCreate&phoneNr=16175282100&contactId=1
Request Method:GET
Status Code:200 OK
Request Headersview source
Accept:_/_
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:PHPSESSID=46853mnu2rfpf3vjfpfd8mal54; sugar_user_theme=Sugar5
Host:ec2-50-117-213-97.compute-1.amazonaws.com:8095
Referer:http://ec2-50-117-213-97.compute-1.amazonaws.com:8095/index.php?module=Users&action=DetailView&record=1
User-Agent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11
X-Requested-With:XMLHttpRequest
Query String Parametersview URL encoded
entryPoint:AsteriskCallCreate
phoneNr:16175282100
contactId:1
Response Headersview source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:keep-alive
Content-Type:text/html; charset=UTF-8
Date:Thu, 02 Aug 2012 10:59:21 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=10
Pragma:no-cache
Server:nginx/1.2.1
Set-Cookie:ck_login_id_20=1; expires=Wed, 31-Oct-2012 10:59:20 GMT; path=/; domain=ec2-50-117-213-97.compute-1.amazonaws.com:8095, ck_login_language_20=en_us; expires=Wed, 31-Oct-2012 10:59:20 GMT; path=/; domain=ec2-50-117-213-97.compute-1.amazonaws.com:8095, sugar_user_theme=Sugar5; expires=Fri, 02-Aug-2013 10:59:20 GMT
Transfer-Encoding:chunked
X-Powered-By:PHP/5.3.13

**Comment by blak3r** [comment]
Thanks but that's completely useless :P

See: https://github.com/blak3r/yaai/wiki/Debugging-With-Chrome

**Comment by gvijay** [comment]
Find the output from the Response:

# 8662 is the extension configured in asterisk.

Warning: fopen(./sugarcrm.log): failed to open stream: Permission denied in /srv/wordpress/sugarcrm/include/SugarLogger/SugarLogger.php on line 182

Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/wordpress/sugarcrm/include/SugarLogger/SugarLogger.php on line 195
Login Response: Asterisk Call Manager/1.1

Notice: Undefined index: asterisk_prefix in /srv/wordpress/sugarcrm/custom/modules/Asterisk/include/callCreate.php on line 103
Originate Params: Number: 16175282100, Channel: SIP/8662, Context: from-internal, Exten: 16175282100...
Originate/Logout Response: Response: Success

**Comment by blak3r** [comment]
Why isn't logging working on your server?  That's why you get all those warnings in SugarLogger.php

Are you sure you're sitting at the phone with extension 8662?
If so, then you 

Try setting your context in the Administration section to something wrong and see if you get an error message instead of "Success".
Perhaps it always returns Success b/c it was successful in logging out... 

```
Login Response: Asterisk Call Manager/1.1
Originate Params: Number: 16175282100, Channel: SIP/8662, Context: from-internal, Exten: 16175282100...
Originate/Logout Response: Response: Success
```

Also, try setting your Asterisk Manager username and password to something that is definitely wrong and see if you get an error message about invalid username/password.

**Comment by gvijay** [comment]
# I changed the Dial Context to "dont-work" and it still gives me a success.

Login Response: Asterisk Call Manager/1.1

Notice: Undefined index: asterisk_prefix in /srv/wordpress/sugarcrm/custom/modules/Asterisk/include/callCreate.php on line 103
Originate Params: Number: 16175282100, Channel: SIP/8662, Context: dont-work, Exten: 16175282100...
Originate/Logout Response: Response: Success

# However when I provide wrong username/password, I get a Response Error

Login Response: Asterisk Call Manager/1.1

Notice: Undefined index: asterisk_prefix in /srv/wordpress/sugarcrm/custom/modules/Asterisk/include/callCreate.php on line 103
Originate Params: Number: 16175282100, Channel: SIP/8662, Context: dont-work, Exten: 16175282100...
Originate/Logout Response: Response: Error

**Comment by blak3r** [comment]
Going to need to get into your asterisks logs then and see what the errors are.  Chances are something isn't set correctly in your config like your dial command. 

I don't remember how to do this off hand so you'll have to google that. 

I'm printing everything AMI is sending back so the protocol isn't being very helpful then. 

~blake

**Comment by gvijay** [comment]
Thanks for all you help. Will revert with the findings.

Vijay G.

**Comment by blak3r** [comment]
@gvijay Any luck?

**Comment by gvijay** [comment]
It worked, but the tough part is what changed made it to work. (Tried many changes with dial plan, installing some asterisk_click2dial on openerp and many more). I have an older snapshot of the image and will compare the current working one with it and update exactly what change made it to work.

**Comment by blak3r** [comment]
Hate when that happens... I think it was probably related to dial plan.  Glad you got it working.  Would be interested to know what it was if you find it.
