### ISSUE TITLE
Outbound call display, and making calls on leads?

### ISSUE THREAD

**Issue by edokid** [blak3r/yaai#58]
Two questions.  

1) When my users make outbound calls with click to call from Sugar, the outbound caller ID shows the main outbound ID for our trunk, and not the users actual caller ID the way it would if they pick up their extension and call someone.  How do I set it to use the users's caller ID and not our main line?

2) I want to use the click to call from Leads, as I like how it can click and pop up for notes and time the call. However it keeps saying pick a contact, and if I just type notes and save them, they don't seem to go anywhere.  Is it not possible to have the notes from a call save to the lead?

**Comment by blak3r** [comment]
1.  I'm not sure.  Take a look at CallCreate.php it's probably possible but I'm guessing you'll need to specify a separate callerid for
   Each user in sugar.  It uses the "originate" command which might allow you to override the caller ID.  I'm not an asterisk expert.  I'd be interested to know what you learn. 
2. Lead support isn't available at this time. It wouldn't be too hard to copy the code that creates a link for relate contact and make another for relate to lead. It'll make the interface gross though. 

~blake

**Comment by DavidBogar** [comment]
I'm going to work on lead support and submit the code - Has anyone done this yet?

**Comment by blak3r** [comment]
Nope.  I'd recommend starting with making asteriskLogger.php support it first.  Got a refactored callListener.php coming out shortly so merging your changes will be quite challenging there.

**Comment by DavidBogar** [comment]
Gracias! Thats where i was going to start... I'm going to first search for accounts/contacts, than if no match there search in leads. When do you see the new callListener being completed?

**Comment by askhogan** [comment]
It is almost done on my end.  I am just doing real live testing inside an
office.  All callListener.php functionality was removed to controller.php

https://github.com/askhogan/yaai/blob/master/SugarModules/modules/Asterisk/include/controller.php

**Comment by maotm** [comment]
Hello,
is this ready somehow?
I would like to have a working version, which is searching for leads
Can you please post an update.
Thank you
I have Sugar 6.5, Asterisk 10.2 and FreePBX 2.10, just installed last week.
Pop-up not working yet, but if it will, I'll need it for leads.

**Comment by blak3r** [comment]
No progress on our end.

**Comment by blak3r** [comment]
Leads support has been added in a paid version in case you're still interested.  Lots of other goodies as well.  See www.callinize.com for more.
