### ISSUE TITLE
SOAP issues when using LDAP auth

### ISSUE THREAD

**Issue by jkramarz** [blak3r/yaai#59]
If you are using LDAP auth to SugarCRM, SOAP password is generated in a little bit other way.

$ldap_enc_key = 'LDAP_ENCRYPTION_KEY'; // key from SugarCRM config
$ldap_enc_key = substr(md5($ldap_enc_key),0,24);
$iv = 'password';  // just a "password" string
$password = bin2hex(mcrypt_cbc(MCRYPT_3DES, $ldap_enc_key, $password, MCRYPT_ENCRYPT, $iv));

**Comment by blak3r** [comment]
Thanks. This is good to know. 

If you could provide some sort of IF statement that could detect If the sugar auth type is ldap, I'd get it in the next releases codebase. 

~blake

**Comment by jkramarz** [comment]
You can use following code instead of line 160 in asteriskLogger.php:

$q = mysql_query('select value from config where category=\'system\' and name=\'ldap_enabled\''); 
$r = mysql_fetch_assoc($q);
if($r['value'] != 1){
    $sugarSoapCredential = md5($sugar_config['asterisk_soappass']);
}else{
    $q = mysql_query('select value from config where category=\'ldap\' and name=\'enc_key\'');
    $r = mysql_fetch_assoc($q);
    $ldap_enc_key = substr(md5($r['value']),0,24);
    $sugarSoapCredential = bin2hex(mcrypt_cbc(MCRYPT_3DES, $ldap_enc_key, $sugar_config['asterisk_soappass'], MCRYPT_ENCRYPT, 'password'));
}

**Comment by blak3r** [comment]
Thanks for your contribution. Can you send me an email to Blake.robertson at gmail. Putting together a user email list. 

~blake

**Comment by blak3r** [comment]
I added your change to the asteriskLogger.php and pushed to the repo.
If you could test that everything still runs that'd be great.
