### ISSUE TITLE
Call Popups aren't working (I use Zeno SMS also)

### ISSUE THREAD

**Issue by Damola** [blak3r/yaai#61]
Hello,

Thank you for support.

Please advise where to put dialout.js and how to put it to show click to dial button for Sugar Pro 6.5.2 vs Asterisk 1.8.

Thank you. Waiting support.

**Comment by blak3r** [comment]
Just install it with module loader in sugar. Then follow the user manual 

~blake

**Comment by Damola** [comment]
Thank you very much for your swift response.

Please advise click to dial button showing on user phone number, but not on leads and contacts phone number, how to fix?

**Comment by Damola** [comment]
Please ignore above inquiry. Found out, there's conflict of interest btw an already exisitng module, izeno sms.. which we use for sms... but once we removed from applied fields, it worked with the phones.. so now, trying to fix that.

**Comment by Damola** [comment]
Please advise, pop up not working for both incoming and outging sugarcrm 6.5.2 using asterisk 1.8 on yaai 2.4.1..

**Comment by blak3r** [comment]
Take a look at your browser logs.  Probably some kind of jquery related conflict.

**Comment by Damola** [comment]
Thanks. I have in the last 2 weeks hired two different developers, and they've not been able to make sugar crm pro 6.5.2 work with the latest yaii, and even one destroyed all of my servers. Can I get you or someone that's very good on this to do this.. I have a fresh install sugar pro... so just need asterisk working with it. Thank you. I will be glad to pay a reasonable fee for this service.

**Comment by joshelson** [comment]
Damola- I'll do this for you.  No charge until it's working.  Contact info in my profile.

**Comment by Damola** [comment]
ok, sent you an email already.

**Comment by Damola** [comment]
I will appreciate if I can get someone to get my sugarpro working with yaai.. this is affecting my work.. and rx4change hasn't been responding to mails... Anyone please.

**Comment by blak3r** [comment]
What's your email address?

**Comment by Damola** [comment]
damola@damola.com or info.supergroup@gmail.com Thank you. Waiting..

**Comment by blak3r** [comment]
I worked with Damola.  His issue was the AMI account wasn't created in his freepbx install properly.  Closing this issue.
