### ISSUE TITLE
Pop up not Popping 

### ISSUE THREAD

**Issue by asifaleem** [blak3r/yaai#62]
using asterisk 1.8,yaai 2.4.1 and sugarcrm 6.5.2 .Click to dial is working but pop up  is not popping with both incoming and outgoing calls.

**Comment by blak3r** [comment]
Going to have to be more specific.  There's lots of things it could be.  Please check the troubleshooting section of the User Manual.  

There are also a number of other people who have had this issue on this forum.  Try searching "Click to dial works" and see what worked for them.

**Comment by asifaleem** [comment]
please check the logs.

 ConnectedLineName --> 08080133404
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------

# +++ findCallByAsteriskDestId(1346419137.52)

! FindCallByAsteriskDestId - Found entry in asterisk_log recordId=4ff2a5a5-01df-3be0-73ad-5040b9620515
Looking for user extension number in: SIP/100-00000025
Channel Matched SIP/### style regex.  Ext is:100

# +++ findUserByAsteriskExtension(100)

! Assigned user id set to 1

# Measured call duration is 25341 seconds

# +++ find AccountByPhoneNumber(08080133404)

Found a matching account, relating to account instead of contact

# Establishing relation to Accounts... Call ID: 4ff2a5a5-01df-3be0-73ad-5040b9620515 to Bean ID: 1e390e85-08da-e2d6-7a88-4e54e57deab9

PHP Notice:  Undefined index: error in /var/www/html/Paykobo.com/custom/modules/Asterisk/asteriskLogger.php on line 1359
PHP Notice:  Undefined index: result_count in /var/www/html/Paykobo.com/custom/modules/Asterisk/asteriskLogger.php on line 1363
! No results returned
! Call start was 2012-08-31 06:18:57

# (INBOUND) now updating record in /Calls/ id=4ff2a5a5-01df-3be0-73ad-5040b9620515...

Array
(
    [bitter] => Array
        (
            [id] => 5
            [call_record_id] => 4ff2a5a5-01df-3be0-73ad-5040b9620515
            [asterisk_id] => 1346419135.51
            [callstate] => Connected
            [uistate] =>
            [callerID] => 08080133404
            [callerName] =>
            [channel] => SIP/100-00000025
            [remote_channel] => DAHDI/1-1
            [timestampCall] => 2012-08-31 13:18:57
            [timestampLink] => 2012-08-31 13:19:02
            [timestampHangup] =>
            [direction] => I
            [hangup_cause] =>
            [hangup_cause_txt] =>
            [asterisk_dest_id] => 1346419137.52
            [contact_id] =>
            [opencnam] =>
        )

```
[sweet] => Array
    (
        [assigned_user_name] => Administrator
```
