### ISSUE TITLE
pop up not popping

### ISSUE THREAD

**Issue by asifaleem** [blak3r/yaai#63]
pop up not poping please see the logs.

 ConnectedLineName --> 08080133404
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
# +++ findCallByAsteriskDestId(1346419137.52)

! FindCallByAsteriskDestId - Found entry in asterisk_log recordId=4ff2a5a5-01df-3be0-73ad-5040b9620515
Looking for user extension number in: SIP/100-00000025
Channel Matched SIP/### style regex.  Ext is:100
# +++ findUserByAsteriskExtension(100)

! Assigned user id set to 1
# Measured call duration is 25341 seconds
# +++ find AccountByPhoneNumber(08080133404)

Found a matching account, relating to account instead of contact
# Establishing relation to Accounts... Call ID: 4ff2a5a5-01df-3be0-73ad-5040b9620515 to Bean ID: 1e390e85-08da-e2d6-7a88-4e54e57deab9

PHP Notice:  Undefined index: error in /var/www/html/Paykobo.com/custom/modules/Asterisk/asteriskLogger.php on line 1359
PHP Notice:  Undefined index: result_count in /var/www/html/Paykobo.com/custom/modules/Asterisk/asteriskLogger.php on line 1363
! No results returned
! Call start was 2012-08-31 06:18:57
# (INBOUND) now updating record in /Calls/ id=4ff2a5a5-01df-3be0-73ad-5040b9620515...

Array
(
    [bitter] => Array
        (
            [id] => 5
            [call_record_id] => 4ff2a5a5-01df-3be0-73ad-5040b9620515
            [asterisk_id] => 1346419135.51
            [callstate] => Connected
            [uistate] =>
            [callerID] => 08080133404
            [callerName] =>
            [channel] => SIP/100-00000025
            [remote_channel] => DAHDI/1-1
            [timestampCall] => 2012-08-31 13:18:57
            [timestampLink] => 2012-08-31 13:19:02
            [timestampHangup] =>
            [direction] => I
            [hangup_cause] =>
            [hangup_cause_txt] =>
            [asterisk_dest_id] => 1346419137.52
            [contact_id] =>
            [opencnam] =>
        )

```
[sweet] => Array
    (
        [assigned_user_name] => Administrator
```

**Comment by joshelson** [comment]
Try setting:

error_reporting(0);

At the top of your index.php.

**Comment by blak3r** [comment]
Interesting... This fixed an issue for you?  You can also do this by setting the appropriate property in php.ini .

**Comment by joshelson** [comment]
Yep.  Harder if you're in a shared type environment, though obviously that method isn't upgrade safe.

The issue I was seeing was that outbound calls to https://api.opencnam.com/v1/phone/ were failing.

If you have errors being printed to screen, this messes up the JSON response the client listener is expecting and it actually will break polling.  Just suppressing the errors gets you past that one.

**Comment by blak3r** [comment]
I'm going to close out this issue.  I think the best solution is to add a option in the configuration to enable/disable opencnam.  Been meaning to do that.  Opencnam has been getting really slow recently.  Guess their beta is picking up steam.
