### ISSUE TITLE
AsteriskLogger - where to run?

### ISSUE THREAD

**Issue by southwestcrm** [blak3r/yaai#64]
We have 
  Sugar running in the cloud on one of our own dedicated servers
  an Asterisk phone system running in the office on a dedicated Linux box (on the stnd 198.162.... IP)

I am not sure where to run AsteriskLogger.  

If I run from the shell in the Sugar site it logs in to Sugar OK but then I see an Error 101 - time out connecting to Asterisk
If I run from the shell in the Asterisk box it does not have access to <sugarroot>/custom/modules/Asterisk folder

I think I am missing something.

Any help would be much appreicated

Simon

**Comment by blak3r** [comment]
You run it from your sugar box. 

Not sure what the Error 101 perhaps you could do some research by searching for php and that error message. 

It's normal for the script to timeout once every minute. It's a defense mechanism to keep the connection active. 

~blake

**Comment by Laureano** [comment]
You could check your Asterisk logs for the string "**NOTICE[17384] utils.c: Timed out trying to write**" (PID will vary). By default, Asterisk Manager Sessions are configured with a 100 ms timeout for writing operations over the network. If the latency between both servers happens to be over this value, Asterisk will timeout the connection and disconnect the AsteriskLogger process.
Configuring the value "**writetimeout**" to a higher value could solve this issue.

Also, you could run a packet capturing process to verify which box is sending the packet with the FIN flag to identify which process is disconnecting.

**Comment by Glen206** [comment]
Hello all, hoping for some guidance here with executing the asteriskLogger.php file. this is what I have, I am running Elastix 2.3.0 with Asterisk 1.8.11.0 hosted here in my office. and I am building on a newly installed Sugar 6.5.4 hosted in the cloud. Currently all I have loaded in Sugar is YAAI at this time, and then will build up form there once YAAI is full operational.

I have completed all the prerequisites that I am aware of such as
- created user in the manager.conf file and permitted my Sugar IP address found in my cPanel of my host site 
- set up the Asterisk Configuration under admin in Sugar

I am running the asteriskLogger.php file via SSH with the following command

php -f public_html/vc/custom/modules/Asterisk/asteriskLogger.php

*******\* Asterisk Logger Starting **************

# Sugar root set to [/home/veritas9/public_html/vc/custom/modules/Asterisk/../../../]

Logging to:

# Callout prefix is [1]

# Callin prefix is [+1]

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i

# (Config processed)

Selecting DB Name: veritas9_suga729
! Trying SOAP login endpoint=[https://veritascrm.com/vc/soap.php] user=[admin] password=[737046037665b221521800e7f645f05e]
! Successful SOAP login id=q6m5fpmma3lp4qqdd648jqknk2 user=admin GUID=1
! Error 110 connecting to Asterisk: Connection timed out
! Error 110 connecting to Asterisk: Connection timed out
! Error 110 connecting to Asterisk: Connection timed out....

---

I have gone into my manager.conf file and added writetimeout = 10000, but this does not seem to effect the error.

I'm not sure if i have the right IP address set in the Asterisk Configuration for my Asterisk box but when I do change it back to the default IP of 127.0.0.1, i get the following error...

 Error 111 connecting to Asterisk: Connection refused!

Hope I've given enough description and explained well enough but do let me know if you need more information. Thank you for your feed back

Glen

**Comment by blak3r** [comment]
Glen,

The ip address you specify in the sugar admin section should not be 127.0.0.1 it should be the IP address of your asterisk server.

As for the timeout, I'm not sure but you probably don't have AMI setup properly.  There is a link in the User Manual for getting this setup properly and how to test it using telnet to verify it's setup properly.  Please check that out.

~blake

**Comment by Laureano** [comment]
Glen,
I agree with @blak3r, the problem seems to be related with the setup of the AMI access.

Try to run _netstat -tpna_ to double check that Asterisk is listening for incoming sessions on port 5038 and the interface being used by Asterisk to listen for incoming sessions is the right one. Some Asterisk's setup might come with the manager interface disabled by default or listening only on the loopback interface (localhost access).

You could continue by trying to connect from your laptop or desktop (or any box outside the cloud) to the AMI's public interface using telnet or netcat on Linux or putty on Windows. If you are unable to connect and receive the welcome message from the manager session, then there might be some problem with the Asterisk box setup. Maybe the firewall is blocking incoming connections.

Then you could try to connect from the Sugar SSH console using telnet or netcat. Some cloud providers block outgoing connections to unusual ports. If you are able to connect, you could check the PHP settings, given that some providers do not allow PHP scripts to use sockets to initiate outbound connections. I've faced this kind of restrictions a few times in the past.

Let us know if you can solve this issue.

**Comment by southwestcrm** [comment]
With refernce to the original question, thanks for the update the issue was resolved once we opened up the port to the local Asterisk box.  Sugar couldn't find it :)

We now seem to hit a brick wall in that the screen pops when the phone rings but the window that opens does not look up the number in CRM.  Having read through your manuals it suggest we look at changing SIP/## but we are not sure what to change it to.  

When daliing out, our extension rings fine, but when we pick up the phone the line is dead (it does not dial the number that has been clicked)

Can you advise where we start to look for this information.

thanks

**Comment by Laureano** [comment]
Glad to hear that you figured it out Simon.

Let's begin with the dialing out issue: your call are probably being connected with an invalid dialout context in Asterisk. If so, you should see some lines in the Asterisk log (either console or full file, depending on your conf):

**_VERBOSE[16267] logger.c:   == Starting SIP/8002-09480b30 at outbound,0016502530000,1 failed so falling back to exten 's'_**
**_VERBOSE[16267] logger.c:   == Starting SIP/8002-09480b30 at outbound,s,1 still failed so falling back to context 'default'_**
**_WARNING[16267] pbx.c: Channel 'SIP/8002-09480b30' sent into invalid extension 's' in context 'default', but no invalid handler_**

The snippet is related with an click2call to the number +1-650-253-0000. YMMV depending on your dialplan.
Double check that the dialout context configured in SugarCRM has extensions within the format of the number to dial.

Regarding the dialin issue, it will be probably easier if you could post the lines before and after the lines indicated as "find AccountByPhoneNumber" and "find ContactByPhoneNumber" on the log. Please edit any sensitive information that could be included along with this log.

**Comment by blak3r** [comment]
@Laureano Thanks for providing the nice troubleshooting details.  Any chance you could merge them into the User Manual under a troubleshooting AMI issues section?

**Comment by southwestcrm** [comment]
Great support - thanks guys!

So, it seems that our dialout prefix is adding a 1 instead of a 0 (possibly could be our issue).  We cannot change this in sugar it seems.   Everytime we edit the Asterisk Configuration Dialout prefix from the default of 1 and set it to 0 and save, the next time we go into this screen it just displays 1.

**Comment by blak3r** [comment]
@trustmaster identified that bug today coincidently. 

The whole Configurator script makes me wanna shoot myself whenever I gotta edit it. Had similar problem with soap password. 

I'll try to get to it soon but my weekend is booked and got a deadline for my job that's keeping me late on a Friday :(

~blake

**Comment by trustmaster** [comment]
The fallback dialout prefix change is quite easy, see #66 (note if you have already installed the module, then you need to edit custom/modules/Configurator/asterisk_configurator.php).

The SOAP password saving indeed acts weirdly though.

**Comment by blak3r** [comment]
Closing since this was fixed in a recent commit which will find it's way into next release.  Reopen if it's not fixed.
