### ISSUE TITLE
Make OpenCNAM support optional

### ISSUE THREAD

**Issue by trustmaster** [blak3r/yaai#69]
OpenCNAM is quite useless outside of U.S. and it's confusing users when they get something like "ROCKINGHAM NC" for a call from a local mobile. Please add an option to disable it both in asteriskLogger and callListener.

**Comment by blak3r** [comment]
Fixed in latest commit.

**Comment by rdegges** [comment]
Hey there, I'm the lead developer at OpenCNAM. Just wanted to chime in quickly: we actually have pretty good coverage in all of NANPA territory right now, and are in the process of expanding coverage from a variety of new sources. Next week we'll be publicly launching a new API version along with some internal updates, at which point I'd love to see what you guys think.

Sorry for any issues!

**Comment by blak3r** [comment]
@rdegges Thanks Randall.  Will the new API be more "realtime"?

**Comment by rdegges** [comment]
Yep! The new API (we're launching it towards the end of this week) is a lot better, faster, and simpler for integration as well. We'll still have cached results for hobbist users (free users), but you'll be able to plug your API key in and get instant real-time updates. Right now we do this, but data can be more than 2 weeks old under some circumstances. In the new system, even for free users, responses are always 2 weeks old or realtime, nothing less.

**Comment by rdegges** [comment]
We've also got a new PBX serialization format that makes integration super easy. It's built for PBX hook-ups. You can just append '?format=pbx' and it'll work as desired (only showing results if there is CNAM available).

**Comment by blak3r** [comment]
I noticed the PBX extension the other day. That's was a good idea as I will no longer have to handle the "currently running a lookup" case now. 

Looking forward to the new API. I added the API Key and username to our configurable properties a couple commits ago. So, we now support both the free and paid Apis. 

The API URL isn't changing is it?

~blake

**Comment by rdegges** [comment]
Heya @blak3r--you can keep the same URL if you want. I'd suggest upgrading to our new API URL syntax, however, which looks like:

https://api.opencnam.com/v2/phone/+18182223333 # it will now accept ANY phone number, in any format

And you can optionally specify credentials using basic authentication, or query strings, eg:

https://accountsid:authtoken@api.opencnam.com/v2/phone/+18182223333

or

https://api.opencnam.com/v2/phone/+18182223333?account_sid=xxx&auth_token=xxx

There are lots of benefits to the v2 API (speed, redundancy, and other stuff).

**Comment by blak3r** [comment]
Great.  I just changed it over.  Thanks Randall.

**Comment by blak3r** [comment]
@rdegges Just realized you changed the authentication param names.  
account_sid == username & auth_token == api_key?

or is auth_token like an oauth style token.  Perhaps I should hold off until your have v2 documentation :D

**Comment by rdegges** [comment]
@blak3r Ah yes, I'd hold off on the switchover for now. We're not releasing it until later this week (or possibly Monday). I'll post an update here when the time comes.

I'll also give you a new V2 account SID + auth token (or you can create one automatically on the site). Anyhow, will post more updates as they come :)

**Comment by rdegges** [comment]
Hey @blak3r, just wanted to make an update. We have officially launched the new V2 API, so you can officially integrate it now :)

There are two modes:
- The free tier (no registration / account required). This is the simplest to integrate, eg: https://api.opencnam.com/v2/phone/+12024561111?format=pbx
- The paid tier (unlimited lookups, all real-time). This requires two numbers that users get when they register on our website: https://www.opencnam.com/, to make these lookups work, all you have to do is append the user's credentials, eg: https://api.opencnam.com/v2/phone/+12024561111?format=pbx&account_sid=XXX&auth_token=XXX

**Comment by blak3r** [comment]
Thanks @rdegges I'll get these rolled into the next release.
