### ISSUE TITLE
asteriskLogger returns Soap Login Failed

### ISSUE THREAD

**Issue by sofienazzouz** [blak3r/yaai#71]

**Comment by blak3r** [comment]
Is your password set in the admin config ?

**Comment by blak3r** [comment]
Go to administration -> asterisk config -> asterisk pass 

~blake

**Comment by blak3r** [comment]
You don't appear to have a soap user password set.... 

> ! Trying SOAP login endpoint=[/soap.php] user=[] password=[REDACTED]

Set the Asterisk Soap-User in admin config.

BTW, you should probably change your admin password now since you posted the hashed version in the log snippet above.
