### ISSUE TITLE
YAAI and Sugar CRM with MS SQL Server as the database engine

### ISSUE THREAD

**Issue by ramartin** [blak3r/yaai#76]
Dear
I have an installation of Sugar CRM  with Microsoft SQL Server database, having this type of database engine I can use asterisk yaii integrating it with 100% or only works with MySQL?
Best regards

**Comment by blak3r** [comment]
Only works with mysql.  For a donation of in the $1k - $2k USD range, I'm sure we could come up with a solution. Still pretty cheap compared to alternate solutions which require per user license costs and probably also don't support MSSQL and aren't as full featured.  My contact info is @ http://www.blakerobertson.com/contact

If you decide to rewrite it, please donate the fixes back to the project!

**Comment by ramartin** [comment]
Hi Blake,
Thank you very much for your answer, really not a high cost compared to other solutions. We will discuss it with several clients and if we decide I will contact with you, in the same way, if we decided to carry out the development of the module, we will donate the fixes to the project gladly .
Best regards

**Comment by blak3r** [comment]
Sounds good! Just let me know.

**Comment by blak3r** [comment]
@ramartin I don't suppose you ever added MSSQL support did ya?

**Comment by blak3r** [comment]
I have added support for this.  It's not yet committed.  Stay tuned for 3.7

Email me if you want to try it out now.  Not sure when i'm gonna get around to building the module.
blake [at] callinize.com
