### ISSUE TITLE
No Popups

### ISSUE THREAD

**Issue by DavidBogar** [blak3r/yaai#79]
Hello - I've read, read, and re-read the documentation so many times. I just can't figure out where I am screwing up. I don't get any popups and click do dial does not work. I'm hoping someone can point me in the right direction! Here is a call from and internal extension back out and into the one assigned to the admin account in sugar. 

Logging to: /logy
# (Config processed)

Selecting DB Name: sugarcrm
! Trying SOAP login endpoint=[http://10.0.0.40/soap.php] user=[sugar] password=[db4017f4d3d7ccf1a1ea05f0e03764a0]
! Successful SOAP login id=0mo1k73gmv08a2der5bb2uqf37 user=sugar GUID=54f65b81-09e0-1f5c-1f3f-507ce54dde54
# Successfully opened socket connection to 10.0.0.20:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

[2012-10-16 13:17:40]
! --- Event -----------------------------------------------------------
!                Event -->  
! ---------------------------------------------------------------------
[2012-10-16 13:18:03]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid  
!            Privilege --> call,all  
!              Channel --> SIP/301-00000015  
!          CallerIDNum --> 301  
!         CallerIDName --> David Laptop  
!             Uniqueid --> 1350407881.21  
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: 301
  [2012-10-16 13:18:04]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewCallerid  
  !            Privilege --> call,all  
  !              Channel --> SIP/301-00000015  
  !          CallerIDNum --> 18888577787  
  !         CallerIDName -->  
  !             Uniqueid --> 1350407881.21  
  !      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
  ! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: 18888577787
  [2012-10-16 13:18:04]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewCallerid  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000016  
  !          CallerIDNum --> 818888577787  
  !         CallerIDName -->  
  !             Uniqueid --> 1350407881.22  
  !      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
  ! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: 18888577787
  [2012-10-16 13:18:04]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial  
  !            Privilege --> call,all  
  !             SubEvent --> Begin  
  !              Channel --> SIP/301-00000015  
  !          Destination --> SIP/flowroute-00000016  
  !          CallerIDNum --> 18888577787  
  !         CallerIDName --> <unknown>  
  !     ConnectedLineNum --> <unknown>  
  !    ConnectedLineName --> <unknown>  
  !             UniqueID --> 1350407881.21  
  !         DestUniqueID --> 1350407881.22  
  !           Dialstring --> flowroute/18888577787  
  ! ---------------------------------------------------------------------
  ! Dial Event src=SIP/301-00000015 dest=SIP/flowroute-00000016
  ! Successfully created CALL record with id=59604bed-f9d3-1f41-e239-507d960f2ea4
- CallerID is: 18888577787
  OUTBOUND state detected... /^(sip\/[1-9][0-9][0-9]?-|Local)/i is astMatchInternal eChannel= SIP/301-00000015 eDestination=SIP/flowroute-00000016
  [2012-10-16 13:18:07]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewCallerid  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000017  
  !          CallerIDNum --> +18888577787  
  !         CallerIDName --> +18888577787  
  !             Uniqueid --> 1350407884.23  
  !      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
  ! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: +18888577787
  [2012-10-16 13:18:08]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewAccountCode  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000016  
  !             Uniqueid --> 1350407881.22  
  !          AccountCode -->  
  !       OldAccountCode -->  
  ! ---------------------------------------------------------------------
  [2012-10-16 13:18:08]
  ! --- Event -----------------------------------------------------------
  !                Event --> Bridge  
  !            Privilege --> call,all  
  !          Bridgestate --> Link  
  !           Bridgetype --> core  
  !             Channel1 --> SIP/301-00000015  
  !             Channel2 --> SIP/flowroute-00000016  
  !            Uniqueid1 --> 1350407881.21  
  !            Uniqueid2 --> 1350407881.22  
  !            CallerID1 --> 18888577787  
  !            CallerID2 --> 818888577787  
  ! ---------------------------------------------------------------------
  [2012-10-16 13:18:24]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewCallerid  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000017  
  !          CallerIDNum --> +18888577787  
  !         CallerIDName --> +18888577787  
  !             Uniqueid --> 1350407884.23  
  !      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
  ! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: +18888577787
  [2012-10-16 13:18:24]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial  
  !            Privilege --> call,all  
  !             SubEvent --> Begin  
  !              Channel --> SIP/flowroute-00000017  
  !          Destination --> SIP/111-00000018  
  !          CallerIDNum --> +18888577787  
  !         CallerIDName --> +18888577787  
  !     ConnectedLineNum --> <unknown>  
  !    ConnectedLineName --> <unknown>  
  !             UniqueID --> 1350407884.23  
  !         DestUniqueID --> 1350407902.24  
  !           Dialstring --> 111  
  ! ---------------------------------------------------------------------
  ! Dial Event src=SIP/flowroute-00000017 dest=SIP/111-00000018
  ! Successfully created CALL record with id=c65f3870-1d4f-4647-6a63-507d96d32299
- CallerID is: +18888577787
  Inbound state detected... /^(sip\/[1-9][0-9][0-9]?-|Local)/i is astMatchInternal eChannel= SIP/flowroute-00000017 eDestination=SIP/111-00000018
  [2012-10-16 13:18:45]
  ! --- Event -----------------------------------------------------------
  !                Event --> Hangup  
  !            Privilege --> call,all  
  !              Channel --> SIP/111-00000018  
  !             Uniqueid --> 1350407902.24  
  !          CallerIDNum --> 111  
  !         CallerIDName --> device  
  !     ConnectedLineNum --> +18888577787  
  !    ConnectedLineName --> +18888577787  
  !                Cause --> 16  
  !            Cause-txt --> Normal Clearing  
  ! ---------------------------------------------------------------------
  # +++ findCallByAsteriskDestId(1350407902.24)
  ! FindCallByAsteriskDestId - Found entry in asterisk_log recordId=c65f3870-1d4f-4647-6a63-507d96d32299
  Looking for user extension number in: SIP/111-00000018
  Channel Matched SIP/### style regex.  Ext is:111
  # +++ findUserByAsteriskExtension(111)
  ! Assigned user id set to 1
  # Measured call duration is 0 seconds
  Adding INBOUND Failed Call, id=1350407902.24, call_id = c65f3870-1d4f-4647-6a63-507d96d32299
  # +++ find AccountByPhoneNumber(+18888577787)
  ! No results returned
  # +++ find ContactByPhoneNumber(+18888577787)
  findSugarObjectByPhoneNumber: Contact query components- Phone: 8577787   RegEx: (8[^\d]_5[^\d]_7[^\d]_7[^\d]_7[^\d]_8[^\d]_7[^\d]_)$
  ! No results returned
  ! Invalid Arguments passed to setRelationshipBetweenCallAndBean# (INBOUND) now updating record in /Calls/ id=c65f3870-1d4f-4647-6a63-507d96d32299...
  NAME: *_ Automatic record **
  DESCRIPTION: 
  Cleaning up Failed Calls part1, asterisk_id = 1350407884.23
  [2012-10-16 13:18:46]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial  
  !            Privilege --> call,all  
  !             SubEvent --> End  
  !              Channel --> SIP/flowroute-00000017  
  !             UniqueID --> 1350407884.23  
  !           DialStatus --> NOANSWER  
  ! ---------------------------------------------------------------------
  [2012-10-16 13:18:46]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewCallerid  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000017  
  !          CallerIDNum --> +18888577787  
  !         CallerIDName --> +18888577787  
  !             Uniqueid --> 1350407884.23  
  !      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
  ! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: +18888577787
  [2012-10-16 13:18:46]
  ! --- Event -----------------------------------------------------------
  !                Event --> NewCallerid  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000017  
  !          CallerIDNum --> +18888577787  
  !         CallerIDName --> +18888577787  
  !             Uniqueid --> 1350407884.23  
  !      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
  ! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: +18888577787
  [2012-10-16 13:18:56]
  ! --- Event -----------------------------------------------------------
  !                Event --> Unlink  
  !            Privilege --> call,all  
  !             Channel1 --> SIP/301-00000015  
  !             Channel2 --> SIP/flowroute-00000016  
  !            Uniqueid1 --> 1350407881.21  
  !            Uniqueid2 --> 1350407881.22  
  !            CallerID1 --> 18888577787  
  !            CallerID2 --> 818888577787  
  ! ---------------------------------------------------------------------
  [2012-10-16 13:18:56]
  ! --- Event -----------------------------------------------------------
  !                Event --> Hangup  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000016  
  !             Uniqueid --> 1350407881.22  
  !          CallerIDNum --> 818888577787  
  !         CallerIDName --> <unknown>  
  !     ConnectedLineNum --> 18888577787  
  !    ConnectedLineName --> <unknown>  
  !                Cause --> 16  
  !            Cause-txt --> Normal Clearing  
  ! ---------------------------------------------------------------------
  # +++ findCallByAsteriskId(1350407881.22)
  ! Found entry in asterisk_log recordId=59604bed-f9d3-1f41-e239-507d960f2ea4
  # [1350407881.22] FOUND outbound CALL
  Looking for user extension number in: SIP/301-00000015
  Channel Matched SIP/### style regex.  Ext is:301
  # +++ findUserByAsteriskExtension(301)
  ! Assigned user will be set to Administrator.
  # [1350407881.22] Measured call duration is -14352 seconds
  # +++ find AccountByPhoneNumber(18888577787)
  ! No results returned
  # +++ find ContactByPhoneNumber(18888577787)
  findSugarObjectByPhoneNumber: Contact query components- Phone: 8577787   RegEx: (8[^\d]_5[^\d]_7[^\d]_7[^\d]_7[^\d]_8[^\d]_7[^\d]_)$
  ! No results returned
  ! Invalid Arguments passed to setRelationshipBetweenCallAndBean# [1350407881.22](OUTBOUND) Now updating record in /Calls/ id=59604bed-f9d3-1f41-e239-507d960f2ea4...
  NAME: *_ Automatic record **
  DESCRIPTION: 
  [2012-10-16 13:18:57]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial  
  !            Privilege --> call,all  
  !             SubEvent --> End  
  !              Channel --> SIP/301-00000015  
  !             UniqueID --> 1350407881.21  
  !           DialStatus --> ANSWER  
  ! ---------------------------------------------------------------------
  [2012-10-16 13:18:57]
  ! --- Event -----------------------------------------------------------
  !                Event --> Hangup  
  !            Privilege --> call,all  
  !              Channel --> SIP/301-00000015  
  !             Uniqueid --> 1350407881.21  
  !          CallerIDNum --> 18888577787  
  !         CallerIDName --> <unknown>  
  !     ConnectedLineNum --> <unknown>  
  !    ConnectedLineName --> <unknown>  
  !                Cause --> 16  
  !            Cause-txt --> Normal Clearing  
  ! ---------------------------------------------------------------------
  # +++ findCallByAsteriskId(1350407881.21)
  ! Warning, results set was empty!
  [1350407881.21] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)
  [2012-10-16 13:18:57]
  ! --- Event -----------------------------------------------------------
  !                Event --> MessageWaiting  
  !            Privilege --> call,all  
  !              Mailbox --> 101@default  
  !              Waiting --> 1  
  !                  New --> 44  
  !                  Old --> 0  
  ! ---------------------------------------------------------------------
  [2012-10-16 13:18:57]
  ! --- Event -----------------------------------------------------------
  !                Event --> Hangup  
  !            Privilege --> call,all  
  !              Channel --> SIP/flowroute-00000017  
  !             Uniqueid --> 1350407884.23  
  !          CallerIDNum --> +18888577787  
  !         CallerIDName --> +18888577787  
  !     ConnectedLineNum --> 111  
  !    ConnectedLineName --> device  
  !                Cause --> 16  
  !            Cause-txt --> Normal Clearing  
  ! ---------------------------------------------------------------------
  # +++ findCallByAsteriskDestId(1350407884.23)
  ! Warning, FindCallByAsteriskDestId results set was empty!
  [2012-10-16 13:19:57] Timeout or Error
  [2012-10-16 13:20:57] Timeout or Error

my config (lines i'm not sure about): 
Dial Context: from-internal
Dialout Prefix: 8
Dialin Prefix: +1
Dialpattern for inbound/outbound matching: ^(sip\/[1-9][0-9][0-9]?-|Local)
Dialout Channel: SIP/###
Custom User Ext Match Regex: Local\/(?:.*?)(\d\d\d?\d?\d?)@

Any help would be highly appreciated.

**Comment by blak3r** [comment]
It appears that extension 111 is not mapped to a user.  Did you add the fields in studio?  And are you logged in as a user which has extension 111 assigned.

```
Looking for user extension number in: SIP/111-00000018 Channel Matched SIP/### style regex. Ext is:111 
# +++ findUserByAsteriskExtension(111) ! Assigned user id set to 1 
```

user id 1 == administrator

Is that who you're logged in as?

For the click to dial, see the troubleshooting section of the User-Manual.  There is information about how to troubleshoot it using chrome.

Also, please send me an email here: http://www.blakerobertson.com/contact so I can add you to the email list.  Please keep all support questions here though.

**Comment by DavidBogar** [comment]
That was fast! I did add the fields in studio, both boxes are checked and '111' is entered under asterisk extension. 
Yes I am loged in and it is mapped to the admin or administrator account.

**Comment by blak3r** [comment]
Any javascript errors on the pages?  Is this a fresh install of SugarCRM or do you have other modules which could be conflicting potentially and what version of SugarCRM?

**Comment by DavidBogar** [comment]
Not 100% what i'm looking for in chrome: here is a screen shot: 
http://i1241.photobucket.com/albums/gg513/dbphoto84/screen2_zps2f78174d.png

Its fresh install of 6.5.5
No other modules installed

**Comment by blak3r** [comment]
That's not helpful.  The screenshots have arrows which show you were to
click.

**Comment by DavidBogar** [comment]
Shouldn't I be seeing something references "CallCreate" ? 
What exactly am i looking for in here? Just javascript errors?

**Comment by blak3r** [comment]
RTFM!
https://github.com/blak3r/yaai/wiki/Debugging-With-Chrome

**Comment by DavidBogar** [comment]
I'm not getting the same results: 

Request URL:http://XXXXXXXXXXX:81/index.php?entryPoint=AsteriskCallCreate&phoneNr=17178297630&contactId=662ad432-ac37-3ec2-34fe-507ce934c8c5
Request Method:GET
Status Code:200 OK
Request Headersview source
Accept:_/_
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:Accounts_divs=accounts_detia_photography_1_v%3D%23project_v%3D%23; sugar_theme_menu_load=true; PHPSESSID=6uecmdu68e766fuaiva0h4vlg4; sugar_user_theme=Sugar5f
Host:rxxxxxxxm:81
Referer:http://rxxxxxxxxxio.com:81/index.php?action=ajaxui
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4
X-Requested-With:XMLHttpRequest
Query String Parametersview URL encoded
entryPoint:AsteriskCallCreate
phoneNr:17178297630
contactId:662ad432-ac37-3ec2-34fe-507ce934c8c5
Response Headersview source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:12237
Content-Type:text/html; charset=UTF-8
Date:Tue, 16 Oct 2012 18:12:06 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=15, max=98
Pragma:no-cache
Server:Apache/2.2.16 (Debian)
Set-Cookie:ck_login_id_20=1; expires=Mon, 14-Jan-2013 18:12:06 GMT; path=/; domain=xxxxxxxm:81
Set-Cookie:ck_login_language_20=en_us; expires=Mon, 14-Jan-2013 18:12:06 GMT; path=/; domain=rxxxxxxm:81
Set-Cookie:sugar_user_theme=Sugar5; expires=Wed, 16-Oct-2013 18:12:06 GMT
Vary:Accept-Encoding
X-Powered-By:PHP/5.3.3-7+squeeze14

Under Response Its just 1411 lines of HTML

**Comment by blak3r** [comment]
Please paste response.  It's probably a sugar error message.  Like a
redirect to the login or a permission error.
You can use the Preview tab to view the rendered html.  It'd be easier to
read.

**Comment by DavidBogar** [comment]
Thanks! Through much more investigating I found the problem :) You pointed me in the right direction!

**Comment by blak3r** [comment]
What was the issue?  Any feedback on how documentation should be improved?

It's a wiki so feel free to add notes. 

~blake

**Comment by DavidBogar** [comment]
Thanks - The issue was a javascript issue, but i couldn't pin point it. I believe it was an erorr during the install of the module. After trying it on another crm system it worked fine. I think the install failed to install 100% due to the PHP memory limit being set to low. During the install the package actual hung at 100%. I would recommend ensuring the php memory limit is set appropriately to avoid any install issues on 6.5.5 I was able to replicate the issue with a brand new install as well.

**Comment by blak3r** [comment]
That's good to know. What's the memory limit that it fails with?

~blake

**Comment by DavidBogar** [comment]
It failed at 32MB - I doubled it to 64MB no problem. I have since lowered it again to 32 after the install and no problems...
