### ISSUE TITLE
Outgoing callerID Problems

### ISSUE THREAD

**Issue by DavidBogar** [blak3r/yaai#80]
The problem I am having is my toll free number is showing in the popup as the number called. Both with the click to dial and the manual dialing. I can't figure out for sure if this is an asterisk config problem or yaai. I am not really that familiar with the asterisk API. 

Why or what is changing the CallerID multiple times here? 

[2012-10-17 22:09:41]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/111-000000f3
!          CallerIDNum --> 111
!         CallerIDName --> David Home
!             Uniqueid --> 1350526178.245
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
# \* {e['UniqueId']} CallerID  Changed to: 111

[2012-10-17 22:09:41]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/111-000000f3
!          CallerIDNum --> 18888577787
!         CallerIDName -->
!             Uniqueid --> 1350526178.245
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
# \* {e['UniqueId']} CallerID  Changed to: 18888577787

[2012-10-17 22:09:41]
! --- Event -----------------------------------------------------------
!                Event --> NewCallerid
!            Privilege --> call,all
!              Channel --> SIP/flowroute-000000f4
!          CallerIDNum --> 819194435574
!         CallerIDName -->
!             Uniqueid --> 1350526178.246
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)
! ---------------------------------------------------------------------
# \* Stripping prefix: 8\* {e['UniqueId']} CallerID  Changed to: 19194435574

[2012-10-17 22:09:41]
! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> Begin
!              Channel --> SIP/111-000000f3
!          Destination --> SIP/flowroute-000000f4
!          CallerIDNum --> 18888577787
!         CallerIDName --> <unknown>
!     ConnectedLineNum --> <unknown>
!    ConnectedLineName --> <unknown>
!             UniqueID --> 1350526178.245
!         DestUniqueID --> 1350526178.246
!           Dialstring --> flowroute/19194435574
! ---------------------------------------------------------------------
! Dial Event src=SIP/111-000000f3 dest=SIP/flowroute-000000f4
Array
(
    [id] => 7674da0d-389d-fc0f-1074-507f644d4acc
    [error] => Array
        (
            [number] => 0
            [name] => No Error
            [description] => No Error
        )

)
! Successfully created CALL record with id=7674da0d-389d-fc0f-1074-507f644d4acc
# CallerID is: 18888577787

OUTBOUND state detected... /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i is astMatchInternal eChannel= SIP/111-000000f3 eDestination=SIP/flowroute-000000f4
[2012-10-17 22:09:55]
! --- Event -----------------------------------------------------------
!                Event --> NewAccountCode
!            Privilege --> call,all
!              Channel --> SIP/flowroute-000000f4
!             Uniqueid --> 1350526178.246
!          AccountCode -->
!       OldAccountCode -->
! ---------------------------------------------------------------------
[2012-10-17 22:09:55]
! --- Event -----------------------------------------------------------
!                Event --> Bridge
!            Privilege --> call,all
!          Bridgestate --> Link
!           Bridgetype --> core
!             Channel1 --> SIP/111-000000f3
!             Channel2 --> SIP/flowroute-000000f4
!            Uniqueid1 --> 1350526178.245
!            Uniqueid2 --> 1350526178.246
!            CallerID1 --> 18888577787
!            CallerID2 --> 819194435574
! ---------------------------------------------------------------------
[2012-10-17 22:10:12]
! --- Event -----------------------------------------------------------
!                Event --> Unlink
!            Privilege --> call,all
!             Channel1 --> SIP/111-000000f3
!             Channel2 --> SIP/flowroute-000000f4
!            Uniqueid1 --> 1350526178.245
!            Uniqueid2 --> 1350526178.246
!            CallerID1 --> 18888577787
!            CallerID2 --> 819194435574
! ---------------------------------------------------------------------
[2012-10-17 22:10:12]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SIP/flowroute-000000f4
!             Uniqueid --> 1350526178.246
!          CallerIDNum --> 819194435574
!         CallerIDName --> <unknown>
!     ConnectedLineNum --> 18888577787
!    ConnectedLineName --> <unknown>
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
# +++ findCallByAsteriskId(1350526178.246)

! Found entry in asterisk_log recordId=7674da0d-389d-fc0f-1074-507f644d4acc
# [1350526178.246] FOUND outbound CALL

Looking for user extension number in: SIP/111-000000f3
Channel Matched SIP/### style regex.  Ext is:111
# +++ findUserByAsteriskExtension(111)

! Assigned user id set to 1
# [1350526178.246] Measured call duration is 18 seconds
# +++ find AccountByPhoneNumber(18888577787)

! No results returned
# +++ find ContactByPhoneNumber(18888577787)

  findSugarObjectByPhoneNumber: Contact query components- Phone: 8577787   RegEx: (8[^\d]_5[^\d]_7[^\d]_7[^\d]_7[^\d]_8[^\d]_7[^\d]*)$
! No results returned
! Invalid Arguments passed to setRelationshipBetweenCallAndBean! Call start was 2012-10-18 02:09:41
# [1350526178.246](OUTBOUND) Now updating record in /Calls/ id=7674da0d-389d-fc0f-1074-507f644d4acc...

NAME: *\* Automatic record **
DESCRIPTION:
[2012-10-17 22:10:15]
! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> End
!              Channel --> SIP/111-000000f3
!             UniqueID --> 1350526178.245
!           DialStatus --> ANSWER
! ---------------------------------------------------------------------
[2012-10-17 22:10:15]
! --- Event -----------------------------------------------------------
!                Event --> Hangup
!            Privilege --> call,all
!              Channel --> SIP/111-000000f3
!             Uniqueid --> 1350526178.245
!          CallerIDNum --> 18888577787
!         CallerIDName --> <unknown>
!     ConnectedLineNum --> <unknown>
!    ConnectedLineName --> <unknown>
!                Cause --> 16
!            Cause-txt --> Normal Clearing
! ---------------------------------------------------------------------
# +++ findCallByAsteriskId(1350526178.245)

! Warning, results set was empty!
[1350526178.245] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error)
[2012-10-17 22:11:15] Timeout or Error

**Comment by blak3r** [comment]
Don't know off hand. Search through the issues here I feel like someone else may of had this issue also. 

~blake

**Comment by DavidBogar** [comment]
I saw a at least two other people having the same problem, but I didn't exactly see a solution.

**Comment by DavidBogar** [comment]
https://github.com/blak3r/yaai/issues/75  <-- currently open for same problem.
