### ISSUE TITLE
Not getting Call Popups (Solved: issue was internal -> internal calls don't popup)

### ISSUE THREAD

**Issue by bickus** [blak3r/yaai#81]
I've installed your module and have some problem. I've read all documentation, but  it wasn't helpfull for me :(
Don't see any popup window. I've read user manual,  I've done debugging with Chrome - everything seems OK.

Response:
HTTP/1.1 200 OK
Date: Fri, 19 Oct 2012 07:59:06 GMT
Server: Apache/2.2.22 (Fedora)
X-Powered-By: PHP/5.3.13
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: ck_login_id_20=90d06eae-0608-71f8-d1b8-503203fe9396; expires=Thu, 17-Jan-2013 07:59:07 GMT; path=/; domain=xxx.xx.xx
Set-Cookie: ck_login_language_20=ru_ru; expires=Thu, 17-Jan-2013 07:59:07 GMT; path=/; domain=xxx.xx.xx
Set-Cookie: sugar_user_theme=Sugar5; expires=Sat, 19-Oct-2013 07:59:07 GMT
Content-Length: 181
Content-Type: text/html; charset=UTF-8

Login Response: Asterisk Call Manager/1.1
Originate Params: Number: 7072, Channel: SIP/7073, Context: callservice_out, Exten: 7072...
Originate/Logout Response: Response: Success

Could you help me please?

**Comment by blak3r** [comment]
Ok so is click to dial working?  From that log it looks like it's making a call.

Call popups don't occur on internal calls.  You should try making a call to an external number.

**Comment by bickus** [comment]
Oh, i've missed somewhere about popups only on external, my mistake( Well, it's working on outbound calls, but i can't see any popups on incoming. Where can i find some help about this? My softphone sees incoming call.
Thnx for your help!

**Comment by blak3r** [comment]
Do you have Ring Groups for your incoming calls?  (Forexample: when calling extension X, does it call SIP extension X and also call a cell phone?

If possible create a simple extension and get that working first to isolate the problem.

There are some regex's to detect internal ring groups.  Take a look at your asteriskLogger output.  When the call created you should see some lines about trying to associate the call with a particular user.

**Comment by bickus** [comment]
<<Do you have Ring Groups for your incoming calls? (Forexample: when calling extension X, does it call SIP extension X and also call a cell phone?

No.

! --- Event ----------------------------------------------------------- ! 
    Event --> NewCallerid ! 
    Privilege --> call,all ! 
    Channel --> SIP/5061-b7db0748 ! 
    CallerIDNum --> 506003006 ! 
    CallerIDName --> 506003006 ! 
    Uniqueid --> 1350974098.16334 ! 
    CID-CallingPres --> 0 (Presentation Allowed, Not Screened) 
! --------------------------------------------------------------------- 
    CallerID Changed to: 506003006 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
[2012-10-23 06:34:58] ! --- Event ----------------------------------------------------------- ! 
    Event --> NewCallerid ! 
    Privilege --> call,all ! 
    Channel --> SIP/5061-b7db0748 ! 
    CallerIDNum --> 0506003006 ! 
    CallerIDName --> 506003006 ! 
    Uniqueid --> 1350974098.16334 !
    CID-CallingPres --> 0 (Presentation Allowed, Not Screened) 
! --------------------------------------------------------------------- 
    CallerID Changed to: 0506003006 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 !
AMI Event 'Newstate surpressed. 
[2012-10-23 06:35:16] ! --- Event ----------------------------------------------------------- ! 
    Event --> Dial ! 
    Privilege --> call,all ! 
    SubEvent --> End ! 
    Channel --> SIP/5061-b7db0748 ! 
    UniqueID --> 1350974098.16334 ! 
    DialStatus --> CHANUNAVAIL ! --------------------------------------------------------------------- 
[2012-10-23 06:35:23] ! --- Event ----------------------------------------------------------- ! 
    Event --> Hangup ! 
    Privilege --> call,all ! 
    Channel --> SIP/5061-b7db0748 ! 
    Uniqueid --> 1350974098.16334 ! 
    CallerIDNum --> 0506003006 ! 
    CallerIDName --> 506003006 ! 
    Cause --> 20 ! 
    Cause-txt --> Unknown ! --------------------------------------------------------------------- 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
    # +++ findCallByAsteriskId(1350974098.16334) 
Deprecated: Function eregi() is deprecated in /var/www/crm_test/custom/modules/Asterisk/asteriskLogger.php on line 1685 ! 
Warning, results set was empty! [1350974098.16334] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error) 
[2012-10-23 06:36:23] Patiently Waiting...! 
[2012-10-23 06:37:23] Patiently Waiting...! 
! AMI Event 'Newchannel surpressed. ! 
AMI Event 'Newstate surpressed. 
[2012-10-23 06:37:45] ! --- Event ----------------------------------------------------------- ! 
    Event --> NewCallerid ! 
    Privilege --> call,all ! 
    Channel --> SIP/5061-b7803708 ! 
    CallerIDNum --> 506003006 ! 
    CallerIDName --> 506003006 ! 
    Uniqueid --> 1350974265.16335 ! 
    CID-CallingPres --> 0 (Presentation Allowed, Not Screened) 
! --------------------------------------------------------------------- 
    CallerID Changed to: 506003006 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
[2012-10-23 06:37:45] ! --- Event ----------------------------------------------------------- ! 
    Event --> NewCallerid ! 
    Privilege --> call,all ! 
    Channel --> SIP/5061-b7803708 ! 
    CallerIDNum --> 0506003006 ! 
    CallerIDName --> 506003006 ! 
    Uniqueid --> 1350974265.16335 ! 
    CID-CallingPres --> 0 (Presentation Allowed, Not Screened) ! ---------------------------------------------------------------------  CallerID Changed to: 0506003006 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 ! 
    AMI Event 'Newstate surpressed. ! 
    AMI Event 'Newchannel surpressed. [2012-10-23 06:37:51]
 ! --- Event ----------------------------------------------------------- !
    Event --> Dial ! 
    Privilege --> call,all ! 
    SubEvent --> Begin !
    Channel --> SIP/5061-b7803708 ! 
    Destination --> SIP/7073-09f2b3b8 ! 
    CallerIDNum --> 0506003006 ! 
    CallerIDName --> 506003006 ! 
    UniqueID --> 1350974265.16335 ! 
    DestUniqueID --> 1350974271.16336 ! 
    Dialstring --> 7073
 ! --------------------------------------------------------------------- ! 
    Dial Event src=SIP/5061-b7803708 dest=SIP/7073-09f2b3b8 ! 
Successfully created CALL record with id=9a2f81b2-aa9b-2f95-97b0-50863b3e4593 Stripping callout prefix: Stripping callin prefix: CallerID is: 0506003006 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
    INTERNAL call detected, Deleting Call Record 9a2f81b2-aa9b-2f95-97b0-50863b3e4593
[2012-10-23 06:37:53] ! --- Event ----------------------------------------------------------- ! 
    Event --> NewCallerid ! 
    Privilege --> call,all ! 
    Channel --> SIP/7073-09f2b3b8 ! 
    CallerIDNum --> 5 ! 
    CallerIDName --> ! 
    Uniqueid --> 1350974271.16336 ! 
    CID-CallingPres --> 0 (Presentation Allowed, Not Screened) 
! --------------------------------------------------------------------- 
    CallerID Changed to: 5 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 ! 
    AMI Event 'Newstate surpressed. ! 
    AMI Event 'Newstate surpressed. 
[2012-10-23 06:38:02] ! --- Event ----------------------------------------------------------- ! 
    Event --> Bridge ! 
    Privilege --> call,all ! 
    Bridgestate --> Link ! 
    Bridgetype --> core ! 
    Channel1 --> SIP/5061-b7803708 ! 
    Channel2 --> SIP/7073-09f2b3b8 ! 
    Uniqueid1 --> 1350974265.16335 ! 
    Uniqueid2 --> 1350974271.16336 ! 
    CallerID1 --> 0506003006 ! 
    CallerID2 --> 5 
! --------------------------------------------------------------------- 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
Internal Bridge Event Detected Internal Didn't match regex. 
[2012-10-23 06:38:08] ! --- Event ----------------------------------------------------------- ! 
    Event --> Unlink ! 
    Privilege --> call,all ! 
    Channel1 --> SIP/5061-b7803708 ! 
    Channel2 --> SIP/7073-09f2b3b8 ! 
    Uniqueid1 --> 1350974265.16335 ! 
    Uniqueid2 --> 1350974271.16336 ! 
    CallerID1 --> 0506003006 ! 
    CallerID2 --> 5
 ! --------------------------------------------------------------------- 
[2012-10-23 06:38:08] ! --- Event ----------------------------------------------------------- ! 
    Event --> Hangup ! 
    Privilege --> call,all ! 
    Channel --> SIP/7073-09f2b3b8 ! 
    Uniqueid --> 1350974271.16336 ! 
    CallerIDNum --> 5 ! 
    CallerIDName --> ! 
    Cause --> 16 ! 
    Cause-txt --> Normal Clearing 
! --------------------------------------------------------------------- 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
    # +++ findCallByAsteriskId(1350974271.16336) 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 ! 
Warning, results set was empty! [1350974271.16336] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error) 
[2012-10-23 06:38:08] ! --- Event ----------------------------------------------------------- ! 
    Event --> Dial ! 
    Privilege --> call,all ! 
    SubEvent --> End ! 
    Channel --> SIP/5061-b7803708 ! 
    UniqueID --> 1350974265.16335 ! 
    DialStatus --> ANSWER 
! --------------------------------------------------------------------- 
[2012-10-23 06:38:08] ! --- Event ----------------------------------------------------------- ! 
    Event --> Hangup ! 
    Privilege --> call,all ! 
    Channel --> SIP/5061-b7803708!  
    Uniqueid --> 1350974265.16335 ! 
    CallerIDNum --> 0506003006 ! 
    CallerIDName --> 506003006 ! 
    Cause --> 16 ! 
    Cause-txt --> Normal Clearing 
! --------------------------------------------------------------------- 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
    # +++ findCallByAsteriskId(1350974265.16335) 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 ! 
Warning, results set was empty! [1350974265.16335] FAILED TO FIND A CALL (note: there are two hangups per call, so this might not be an error) ! 

As you can see - logger doesn't associate call with user or find contact in crm.
(Sugar 6.5.2, latest yaai from github)

**Comment by blak3r** [comment]
That call is detected as an internal call again... hence the reason it's not showing up in popups.

! --- Event ----------------------------------------------------------- !
Event --> Dial ! 
Privilege --> call,all ! 
SubEvent --> Begin !
Channel --> SIP/5061-b7803708 !  <---- this is 5061 (detected as internal)
Destination --> SIP/7073-09f2b3b8 !    <---- this is 7073 (which is detected as internal
CallerIDNum --> 0506003006 ! 
CallerIDName --> 506003006 ! 
UniqueID --> 1350974265.16335 ! 
DestUniqueID --> 1350974271.16336 ! 
Dialstring --> 7073
! --------------------------------------------------------------------- ! 
Dial Event src=SIP/5061-b7803708 dest=SIP/7073-09f2b3b8 ! 
Successfully created CALL record with id=9a2f81b2-aa9b-2f95-97b0-50863b3e4593 Stripping callout prefix: Stripping callin prefix: CallerID is: 0506003006 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
Deprecated: Function eregi() is deprecated in /var/www/xxx/custom/modules/Asterisk/asteriskLogger.php on line 1685 
**INTERNAL call detected, Deleting Call Record 9a2f81b2-aa9b-2f95-97b0-50863b3e4593**

**Comment by bickus** [comment]
Yes, now i understand what was the problem. Thank you!
