### ISSUE TITLE
How to save calls to leads and accounts modules, where is the code???

### ISSUE THREAD

**Issue by blackbird666** [blak3r/yaai#87]
Hay everybody I was making some updates to the application so that it popup calls for leads and accounts if there are a phone that matches the incoming one,  and finally i did it by adding some queries in callListener.php and  some "if-then"s in ShowCall.html, i was manipulating the code to work with minimum code changes but it work fine anyway.

However the call record is not saved to  the leads and accounts (not related to them)  likewise the contacts , i try digging in the asterisklogger.php and try (as a test) to replace all the references to contacts with leads but it didn't work. anyway i just want to know where is the code that saves the call record to sugar and relate it to a contact so that i can update it?? ... thanks for your time, and btw that is  a great application you guys saved my life in my first work project :)

**Comment by blak3r** [comment]
You were looking in the right spot.

asteriskLogger will need to be modified for Leads.
You'll also need to add another column to the database to store the
relationsion type (Leads, vs Contacts)...
controller.php setContactId action will need to be modified.

I think i've gone into more detail on this in other issues.  Might be worth
a search.

Good luck it'd be great to have this new functionality.

**Comment by blackbird666** [comment]
Thanks for the quick reply :)

I'll update the controller.php file and i'll tell you if i achieved something new.

Regards.

**Comment by blak3r** [comment]
Little late to bring this up but @askhogan refactored the UI and it'll be in yaai 3.0. His refctoring will be available for testing in a week or two. 

There is another issue thread that is active within last two days on adding lead support also you might want to collaborate with him. 

Also shoot me you email at http://www.blakerobertson.com/contact 

~blake

**Comment by blak3r** [comment]
@blackbird666 just curious if you ever moved forward with this at all?

**Comment by blak3r** [comment]
Lead support is available in a paid version of callinize.  Checkout www.callinize.com.
