### ISSUE TITLE
EXternal incoming calls (CallerIDName --> <unknown>)

### ISSUE THREAD

**Issue by wessam** [blak3r/yaai#88]
I can't detect caller id in case of external incoming calls.
Any help .

! --- Event -----------------------------------------------------------
!                Event --> NewCallerid  
!            Privilege --> call,all  
!              Channel --> DAHDI/2-1  
!          CallerIDNum -->  
!         CallerIDName -->  
!             Uniqueid --> 1352623086.8  
!      CID-CallingPres --> 0 (Presentation Allowed, Not Screened)  
! ---------------------------------------------------------------------
- {e['UniqueId']} CallerID  Changed to: 
  # +++ mysql_checked_query()
  ! SQL: UPDATE asterisk_log SET CallerID='', callstate='Dial' WHERE asterisk_id='1352623086.8'
  --> Rows affected: 0
  # +++ mysql_checked_query()
  ! SQL: UPDATE asterisk_log SET CallerID='', callstate='Dial' WHERE asterisk_id='1352623086.8'
  --> Rows affected: 0
  # +++ mysql_checked_query()
  ! SQL: UPDATE asterisk_log SET CallerID='', callstate='Dial' WHERE asterisk_id='1352623086.8'
  --> Rows affected: 0
  --> Rows affected: 0
  [2012-11-11 10:38:13]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial  
  !            Privilege --> call,all  
  !             SubEvent --> Begin  
  !              Channel --> DAHDI/2-1  
  !          Destination --> SIP/110-00000006  
  !          CallerIDNum --> <unknown>  
  !         CallerIDName --> <unknown>  
  !     ConnectedLineNum --> <unknown>  
  !    ConnectedLineName --> <unknown>  
  !             UniqueID --> 1352623086.8  
  !         DestUniqueID --> 1352623095.9  
  !           Dialstring --> 110  
  ! ---------------------------------------------------------------------
  ! Dial Event src=DAHDI/2-1 dest=SIP/110-00000006
  ! Successfully created CALL record with id=
- CallerID is: <unknown>
  Inbound state detected... /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i is astMatchInternal eChannel= DAHDI/2-1 eDestination=SIP/110-00000006
  # +++ mysql_checked_query()
  ! SQL: INSERT INTO asterisk_log (asterisk_id, call_record_id, channel, remote_channel, callstate, direction, CallerID, timestampCall, asterisk_dest_id) VALUES('1352623086.8','','SIP/110-00000006','DAHDI/2-1','Dial','I','<unknown>',NOW(),'1352623095.9')
  --> Rows affected: 1
  # +++ mysql_checked_query()
  ! SQL: INSERT INTO asterisk_log (asterisk_id, call_record_id, channel, callstate, direction, CallerID, timestampCall) VALUES('','','SIP/110-00000006','Dial','I','<unknown>',NOW())
  --> Rows affected: 1
  [2012-11-11 10:38:13]
  ! --- Event -----------------------------------------------------------
  !                Event --> Dial  
  !            Privilege --> call,all  
  !             SubEvent --> Begin  
  !              Channel --> DAHDI/2-1  
  !          Destination --> SIP/110-00000006  
  !          CallerIDNum --> <unknown>  
  !         CallerIDName --> <unknown>  
  !     ConnectedLineNum --> <unknown>  
  !    ConnectedLineName --> <unknown>  
  !             UniqueID --> 1352623086.8  
  !         DestUniqueID --> 1352623095.9  
  !           Dialstring --> 110  
  ! ---------------------------------------------------------------------
  ! Dial Event src=DAHDI/2-1 dest=SIP/110-00000006
  ! Successfully created CALL record with id=
- CallerID is: <unknown>
  Inbound state detected... /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i is astMatchInternal eChannel= DAHDI/2-1 eDestination=SIP/110-00000006
  # +++ mysql_checked_query()
  ! SQL: INSERT INTO asterisk_log (asterisk_id, call_record_id, channel, remote_channel, callstate, direction, CallerID, timestampCall, asterisk_dest_id) VALUES('1352623086.8','','SIP/110-00000006','DAHDI/2-1','Dial','I','<unknown>',NOW(),'1352623095.9')
  --> Rows affected: 1
  # +++ mysql_checked_query()
  ! SQL: INSERT INTO asterisk_log (asterisk_id, call_record_id, channel, callstate, direction, CallerID, timestampCall) VALUES('','','SIP/110-00000006','Dial','I','<unknown>',NOW())
  --> Rows affected: 1

**Comment by blak3r** [comment]
Is that an internal call?
Those don't get detected. 

What kind of hardware are you using?

~blake

**Comment by blak3r** [comment]
@wessam 
Did you mean to reopen this issue?

**Comment by wessam** [comment]
Dear Blake ,
thanks a lot for following up but no i think i have closed this issue

Best regards
