### ISSUE TITLE
no connect to SOAP 

### ISSUE THREAD

**Issue by sergeymx** [blak3r/yaai#94]
Hi !
( sorry bad my english )

I use LDAP(389DS), CentOS 6.3, Sugar 6.5.8, yaai 2.6.0b.zip.
i see :   __FATAL: SOAP login failed, something didn't get set by login... check your site_url, and make sure sugarcrm is running.
i see - https://github.com/blak3r/yaai/issues/26

?
new in 2.6.0b  ( ldap enable ): 
    $ldap_enc_key = substr(md5($r['value']),0,24);
    $sugarSoapCredential = bin2hex(mcrypt_cbc(MCRYPT_3DES, $ldap_enc_key, $sugar_config['asterisk_soappass'], MCRYPT_ENCRYPT, 'password'));

user admin in sugarcrm no admin in LDAP.
works ?

**Comment by blak3r** [comment]
Are you using LDAP?

**Comment by sergeymx** [comment]
Yes. I use LDAP ( 389DS) 
Admin - no LDAP,
Other users in LDAP

**Comment by blak3r** [comment]
Ok... hmm well I'm not sure how to fix that off hand.... here's the code in asteriskLogger

``` php
// Get SOAP config
$sugarSoapEndpoint = $sugar_config['site_url'] . "/soap.php"; //"/soap.php";
$sugarSoapUser = $sugar_config['asterisk_soapuser'];
$sugarSoapCredential = md5($sugar_config['asterisk_soappass']);

// Here we check if LDAP Authentication is used, if so we must build credential differently
$q = mysql_query('select value from config where category=\'system\' and name=\'ldap_enabled\'');
$r = mysql_fetch_assoc($q);
if ($r['value'] != 1) {
    $sugarSoapCredential = md5($sugar_config['asterisk_soappass']);
} else {
    $q = mysql_query('select value from config where category=\'ldap\' and name=\'enc_key\'');
    $r = mysql_fetch_assoc($q);
    $ldap_enc_key = substr(md5($r['value']), 0, 24);
    $sugarSoapCredential = bin2hex(mcrypt_cbc(MCRYPT_3DES, $ldap_enc_key, $sugar_config['asterisk_soappass'], MCRYPT_ENCRYPT, 'password'));
}
```

We need to alter that query to also check if the $sugarSoapUser is configured to use LDAP also.
I suspect if you look in the Users database table it probably has a column for authentication type: LDAP vs. Sugar Managed.

**Comment by blak3r** [comment]
It's probably the Users.external_auth_only column.
Try this adding this query: 

``` sql
select external_auth_only from Users where user_name='$sugarSoapUser'
```

Then adding an AND condition to that if($r['value]!=1) line.

**Comment by sergeymx** [comment]
Thanks ! 
I'll try tomorrow morning.

I see mysql table sugarcrm.users, field hash for users from LDAP - empty, no LDAP - fill 
i use its ?

**Comment by blak3r** [comment]
That'd probably work.  Let me know how it goes and I'll pull your fix in.

**Comment by sergeymx** [comment]
i tested its.
No works :(
I comment all LDAP section !
// Here we check if LDAP Authentication is used, if so we must build credential differently
No work ! :(
 Trying SOAP login endpoint=[http://alfresco.gpm.int/sugarcrm/soap.php] user=[admin] password=[fd08c61638ebf7b9d0c50d1af86b8eaf]
  **FATAL: SOAP login failed, something didn't get set by login... check your site_url, and make sure sugarcrm is running.  SessionID
: user=admin GUID=**
  Sleeping for 5 seconds then retrying...

soap server from 6.5.8 woks ? i see in https://github.com/blak3r/yaai/issues/26
... > I'm still using the legacy soap.php" ...

?

**Comment by blak3r** [comment]
Not sure :/
If you took out the LDAP stuff, and you have the soap username and password
correct it should just work.

I'd dig around in the forums.  Most people find they made some weird
mistake.  You could also try the asteriskLogger in the V3 branch on github
just to see if that works differently somehow.

**Comment by sergeymx** [comment]
?
http://developers.sugarcrm.com/wordpress/2012/05/16/new-for-sugar-6-5-–-stronger-password-storage-encryption/
i insert 2 line :
$sugarSoapUser       = "admin";
$sugarSoapCredential = md5("admin_pass");

No works :(
Unfortunaly I do not know how to authorize soap server. Not sure whether to just sugarSoapCredential tektovym password ...

**Comment by sergeymx** [comment]
## i create :

<?php

$options = array(
    "location" => 'http://alfresco.gpm.int/sugarcrm/soap.php',
    "uri" => 'http://alfresco.gpm.int/sugarcrm',
);
$client = new SoapClient(NULL, $options);

$user_auth = array(
'user_name' => 'admin',
'password' => MD5('pass'),
'version' => '.01'
);

$response = $client->login($user_auth, 'Soap tested application');

$session = $response->id;
$response = $client->get_available_modules($session);
var_dump($response->modules);

## ?>

Connect ! No problems !

**Comment by sergeymx** [comment]
## i create and use:

<?php

define('sugarEntry', TRUE);
require_once('/var/www/html/sugarcrm/include/nusoap/nusoap.php');

$client = new nusoap_client('http://alfresco.gpm.int/sugarcrm/soap.php?wsdl',true);

$auth_array = array(
    'user_auth' => array(
          'user_name' => 'admin',
          'password' => md5('pass')
    )
);

$login_results = $client->call('login',$auth_array);
$session_id = $login_results['id'];
$user_guid = $client->call('get_user_id',$session_id);

printf("\n".$auth_array['user_auth']['user_name'].' has a GUID of ' . $user_guid . "\n\n");

## ?>

PHP Warning:  Attempt to modify property of non-object in /var/www/html/sugarcrm/include/nusoap/nusoap.php on line 6160
wait...wait...wait
PHP Warning:  Attempt to modify property of non-object in /var/www/html/sugarcrm/include/nusoap/nusoap.php on line 6160
wait
...
admin has a GUID of

END

**Comment by sergeymx** [comment]
I get http://sourceforge.net/projects/nusoap/files/nusoap/0.9.5/ and compare include sugar6.5.8(0.9.5)
http://itmages.ru/image/view/792839/032bd5f0
( left sugar658, right original 0.9.5 )
its good ?

**Comment by blak3r** [comment]
The warnings are normal. I'm not sure why it's not working. I haven't tested with 6.5.8 I use 6.5.5 is there anything in the sugar release notes which would indicate a change was made that might effect soap?

~blake

**Comment by sergeymx** [comment]
I compared the SOP of sugar versions 6.5.8 and 6.5.5 are the same.
Why is script (written above) with a library pnp-soap works without problems. And with the help of the library can nusoap no connect to the server soap ?

**Comment by sergeymx** [comment]
Sorry.
in CentOS 6.3 use PHP-5.3.3. 
nusoap+php5.3 normal ?
... http://nusoapforphp53.sourceforge.net/

Thanks.

**Comment by blak3r** [comment]
There isn't really a good reason to use Nusoap anymore.  This code existed
before php 5 native soap support.
Perhaps you could just rewrite that soap class and be done with it.

I find the nusoap warnings annoying.

**Comment by askhogan** [comment]
REST is the best :)

**Comment by sergeymx** [comment]
i did its ! :)
Change nusoap in sugar 6.5.8 to normal nusoap 0.95 and connect now ! 

new problem :(
$login_results = $client->call('login',$auth_array);
$session_id = $login_results['id'];
print $session_id;

> > > oa2m37t900541dbnmg6sfn4hk1 
> > > $user_guid = $client->call('get_user_id',$session_id);
> > > print $user_guid;
> > > -1
> > > How is this possible?

**Comment by askhogan** [comment]
Checkout https://github.com/asakusuma/SugarCRM-REST-API-Wrapper-Class

The code is really easy to implement and in my experience has been very
fast.

**Comment by sergeymx** [comment]
sorry in normal nusoap 0.9.5 class name - nusoap_client.
I change : class SugarSoap extends nusoapclient ( file: asteriskLogger.php )
to : class SugarSoap extends nusoap_client
I ALL WORKS ! NO PROBLEM !
All thanks. :)
