### ISSUE TITLE
dialout.js not included

### ISSUE THREAD

**Issue by bludauma** [blak3r/yaai#95]
Hey,

ich got some Problems with yaai and sugarcrm 6.4.5 CE.
The dial buttons are not showing up and i followed the steps in the user manual. After taking a look to the sourcecode i figured out that dialout.js is not included. What can i do to fix this issue?

Best regards

**Comment by bludauma** [comment]
Now i was able to include the javacripts into the sugarwebpage but there are no magic dial buttons

**Comment by blak3r** [comment]
Dialout got renamed to callPopups recently. That should have been loaded. What version are you using?

What steps have you followed from user manual? 

~blake

**Comment by bludauma** [comment]
I am using 2.6.0b

"custom/modules/Asterisk/include/javascript/dialout.js"
and 
"custom/modules/Asterisk/include/javascript/callpopups.js" are included and i have enabled magic dial buttons on my sugar account settings, but the buttons aren't showing up

I followed Step 1-4 (5 is optinal for me because i focus on detail view of records)

**Comment by blak3r** [comment]
Did you look at the troubleshooting sections?

**Comment by bludauma** [comment]
Yes i did but i am not very skilled in php progamming. 

I changed nothing but now there are javascript errors on my sugarsite:

error: ReferenceError: AST_UserExtention is not defined
Quelldatei: http://.../sugarcrm/custom/modules/Asterisk/include/javascript/dialout.js
Line: 57

error: ReferenceError: SER_IB2 is not defined
Quelldatei: http://.../sugarcrm/index.php?module=Accounts&action=DetailView&record=660fb4b2-0173-b4de-4d39-500678680acd
Line: 976

I am sure that this extension is working because i can get out calls with it

**Comment by blak3r** [comment]
Are you using V3? That's a dev branch. 

Do you have a user extension defined in the user preferences? 

Getting click to dial working has a lot less dependencies the inbound.  Check out the troubleshooting section in the user manual to isolate the issue. 

~blake

**Comment by bludauma** [comment]
Hey blake,

outbound calls are working know.

Greets Malte

**Comment by cubicova17** [comment]
For me using quoting trick from https://github.com/blak3r/yaai/issues/65 solved the same issue

**Comment by blak3r** [comment]
@cubicova17 thanks for that. Did you change any of the other regex's?

**Comment by cubicova17** [comment]
No. For solving that issue I just added quotes. I used latest production version.
